### ISSUE TITLE
Could not find required mod: slight-gui-modifications requires 

### ISSUE THREAD

**Issue by Axodouble** [blackd/Inventory-Profiles#1]
Could not find required mod: slight-gui-modifications requires {cloth-client-events-v0 @ [>=2-]}

Is a error that always pops up when I try to launch it, Am I missing a dependancy?

EDIt
Sometimes this;

Could not find required mod: inventoryprofilesnext requires {fabricloader @ [>=0.11.6]}

**Comment by Tygoar** [comment]
I know that you will need the very latest versions of everything, i had to install the new fabric loader and api for one.

**Comment by blackd** [comment]
It requires latest versions of fabric, [fabric api](https://modrinth.com/mod/fabric-api) and [ModMenu](https://modrinth.com/mod/modmenu)

**Comment by Axodouble** [comment]
Still get this issue;
`A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: inventoryprofilesnext requires {fabricloader @ [>=0.11.6]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177)
	... 5 more`

**Comment by Tygoar** [comment]
Did you install the latest Fabric Loader?
https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.4/fabric-installer-0.7.4.jar

**Comment by Axodouble** [comment]
> Did you install the latest Fabric Loader?
> https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.4/fabric-installer-0.7.4.jar

affirmative, i am quite sure I got that exact version too

**Comment by blackd** [comment]
Try to download the [latest release](https://github.com/blackd/Inventory-Profiles/releases/latest)
It removes the hard requirement for Fabric API... But the loader is the same, so I'm not sure it will help.

**Comment by Axodouble** [comment]
i tried that aswell, Still the same bug, Maybe a issue with other mods I am running?

**Comment by blackd** [comment]
What other mods do you have installed.

I've tested the latest build with
ATLauncher, MultiMC and the Official and it works fine

**Comment by blackd** [comment]
Also can you upload the whole log here https://gist.github.com/ so we can see it

**Comment by Axodouble** [comment]
https://gist.github.com/Magiclime/d1c2f09806ea960f435e9f7c0b0f681c

**Comment by Axodouble** [comment]
> https://gist.github.com/Magiclime/d1c2f09806ea960f435e9f7c0b0f681c

mod list is included at the bottom of the logs

**Comment by Tygoar** [comment]
I can see this in that log "Minecraft client fabric-loader-0.11.3-1.17 is ready to start."
The new loader isn't being used.

**Comment by blackd** [comment]
@Magiclime which launcher are you using. 
I guess if I'm to support this I need to have them all :-)

**Comment by Axodouble** [comment]
> @Magiclime which launcher are you using.
> I guess if I'm to support this I need to have them all :-)

using the vanilla launcher

**Comment by blackd** [comment]
Click on Installations find the Fabric Loader .... click on the "..." button then on edit. 
In the version combobox you should have all installed versions of fabric .... i guess

**Comment by Axodouble** [comment]
I got fabric-loader-0.11.3-1.17 as my release of fabric loader

**Comment by Axodouble** [comment]
It may be the load order of the mod or something idk

**Comment by Axodouble** [comment]
All the other mods work fine

**Comment by blackd** [comment]
you need fabric-loader-0.11.6-1.17

Here are some very easy instructions how to install it https://fabricmc.net/wiki/player:tutorials:install_mcl:windows

**Comment by Axodouble** [comment]
Well that should fix it, Sorry, Was a unforeseen issue on my side, To any other people who might have this issue in the future, Make sure to have the latest version of fabric loader installed, If the issue persists reinstall fabric and check the launcher and manually select the most recent version, Fixed it for me, Thank you all for the help!

**Comment by Tygoar** [comment]
Just to add on that, if you have the launcher open it won't update it, so make sure to close the MC launcher before you run the fabric installer.
