### ISSUE TITLE
In-game subtitle for the refill ping uses technical name

### ISSUE THREAD

**Issue by Arrowpuppet** [blackd/Inventory-Profiles#101]
![image](https://user-images.githubusercontent.com/43303412/150648624-929d0bf3-4725-4f70-89a1-1ab82808863b.png)
The new sound for refilling broken/near-broken items is labeled in the subtitle dialog as its technical name; "subtitles.inventoryprofilesnext.refill_ping", instead of a common name like "Tool is refilled".

**Comment by blackd** [comment]
I knew I was forgetting something

**Comment by blackd** [comment]
since we have dedicated visual alert I'll remove the subtitle in the next release
