### ISSUE TITLE
Failed to replace stone axe with stone axe

### ISSUE THREAD

**Issue by ClassyCircuit** [blackd/Inventory-Profiles#102]
Sometimes I get an error message across the entire screen (very annoying): Failed to replace stone axe with stone axe.

I have one stone axe in inventorio slot and one stone axe in regular slot (in my hand).
Not really sure when it's triggered, but sometimes I switch between my axe and some random other tool, try to cut down a tree and then it throws this error.

What is causing this and how can it be avoided?

I am using this mod alongside with Inventorio.

**Comment by blackd** [comment]
these notifications can be controlled in the configuration screen which opens with R+C
In the Auto Refill section

![Config Screen](https://user-images.githubusercontent.com/333840/151359863-ef9212c4-1462-4a12-ab9d-94c68091e701.png)

**Comment by ClassyCircuit** [comment]
Could you release a bug fix for this issue?
If there are some logs that I can provide, let me know.

**Comment by blackd** [comment]
well IPN doesn't understand Inventorio slots. From IPN point of view they don't exist.

**Comment by blackd** [comment]
Also the vanilla click functions that IPN uses to manipulate the inventory doesn't work with Inventorio slots. Well don't work while the inventory is not opened.

**Comment by blackd** [comment]
checking if it's even possible to have more tight integration  https://github.com/Lizard-Of-Oz/Inventorio/issues/104

**Comment by blackd** [comment]
Well this seals more integration with Inventorio as not really possible https://github.com/Lizard-Of-Oz/Inventorio/issues/104#issuecomment-1023573192
