### ISSUE TITLE
Toggle option to refill from locked slots [Suggestion]

### ISSUE THREAD

**Issue by Arrowpuppet** [blackd/Inventory-Profiles#103]
One of the big things that annoys me about item refilling is that, as of yet, there is no option to allow item refilling to grab items from locked slots. This is especially frustrating with totems of undying; I don't want them to be sorted along with the rest of my items, but if I put the totems in a locked slot, then they won't be refilled automatically. I can see how this could be useful if you don't actually want an item to always refill, so this seems like something that should have a config option.

**Comment by ryantheleach** [comment]
+1 to this, I use locked slots to ensure that I always have a slot reserved of something for refilling purposes.

**Comment by blackd** [comment]
done in ff48219
