### ISSUE TITLE
Try to detect which ways is the inventory organised so sort by rows and columns work as expected.

### ISSUE THREAD

**Issue by Soulplexis** [blackd/Inventory-Profiles#105]
use the fabric version for 1.18.1
1. go into a chest with many items.
2. click "Sort in rows" button
3. it will appear that the items were sorted into vertical columns instead of rows
4. click "Sort by Columns"
5. it will appear that the items were sorted into horizontal rows instead of columns

**Comment by blackd** [comment]
Unfortunately it's random which button will do what. It even may be deferent on every game start. It's related on how is the inventory represented internally by the game it self.

**Comment by blackd** [comment]
this is fixed as fixed it can be.

sorting in columns and rows looks like reversed if there are too many item types 

In general these work best if the items types number is less or equal to the column/row number
