### ISSUE TITLE
Colorize items by category

### ISSUE THREAD

**Issue by KTibow** [blackd/Inventory-Profiles#107]
If you have a lot of types of items in one chest, it can be confusing. I feel like if you made different slots in a chest be colored by their creative inventory category, that would help.

**Comment by blackd** [comment]
This makes sense. I'm not sure if it will be possible for the modded storages but for standard chests sure. 
Always using the same colour for given category might be a problem for modded also. 

Thanks for the suggestion!

**Comment by KTibow** [comment]
Right. Another implementation might be adding whitespace in between different creative categories

**Comment by blackd** [comment]
as in:
```
item, item, item, empty slot, item, item
```

**Comment by KTibow** [comment]
Yes, just an empty slot(s).

**Comment by blackd** [comment]
with the changes in 1.18.2 I expect major changes in Items organisation and handling. So I prefer to wait for 1.19 before implementing something like this

**Comment by KTibow** [comment]
Sounds good. Can't wait to see what's next.

**Comment by xotrikspl** [comment]
How to off green color>? xD

**Comment by blackd** [comment]
> How to off green color>? xD
> 

don't hijack issues
and do better search
