### ISSUE TITLE
Re-Implement Feature from original "Inventory Profiles" mod

### ISSUE THREAD

**Issue by Lord-Memester** [blackd/Inventory-Profiles#108]
>[Tweaks] instantMiningCooldown

This was an incredibly useful tweak to have, and I'm sad to see it not present in the "next" version. Could this functionality be regained?

**Comment by blackd** [comment]
https://github.com/blackd/sbt/releases

**Comment by blackd** [comment]
these will not be back in the main mod due to being reason for blacklisting it on some servers
