### ISSUE TITLE
Disable item refill

### ISSUE THREAD

**Issue by XeroOl** [blackd/Inventory-Profiles#109]
I really enjoy this mod for its ability to sort chests and create inventory profiles, but I am used to vanilla item behavior and get confused when this mod shuffles tools and items around my inventory.

Although there are detailed options to adjust the way auto refilling works, it seems like there isn't a way to toggle it off in all cases.
It would be nice if there were a way to turn auto refill completely off.

**Comment by blackd** [comment]
all feature disable/enable are in Mod Settings

**Comment by XeroOl** [comment]
Ahh, I didn't spot that, because I only checked the auto refill settings. Thank you very much!
