### ISSUE TITLE
You can still quick move items into locked slots

### ISSUE THREAD

**Issue by Haano137** [blackd/Inventory-Profiles#11]
Basically the title

**Comment by blackd** [comment]
Yes! this is rather annoying and for a simple shift click action the complexity of fixing it considerably higher the one might expect.

It requires reimplementing most of the inventory handing in the game. I'll continue looking into it but I doubt it will be a fast fix.

**Comment by Haano137** [comment]
I'll leave this here instead of making a new issue since it's kinda related.

locked empty slots can still pick up dropped items.

**Comment by blackd** [comment]
Well... that one seems even harder to fix. :)

**Comment by blackd** [comment]
Unfortunately any possible way to handle this on servers leads to broken vanilla inventory management. So I can't really implement it.
