### ISSUE TITLE
Problem of positioning with the mod Diet.

### ISSUE THREAD

**Issue by macgivre07** [blackd/Inventory-Profiles#112]
Hello,

I have noticed a small problem of placement of the icon with the mods diet.
Is it possible to move the "Sort inventory" icon above "Sort inventory by columns".
![image](https://user-images.githubusercontent.com/11701116/154814366-a3c5a3fa-8e60-4158-8a85-6cb7112ae9ed.png)

**Comment by blackd** [comment]
yes it is


do you see an small button with a square icon in the top left of the screen? click it

**Comment by macgivre07** [comment]
Yes, now that you say, really sorry for asking the question without having noticed little detail to position the icons.

Also all my apologies.

**Comment by blackd** [comment]
Don't worry about it.
The problem with the ui clashing with other mods was problem for so long... I just wanted to brag with my shiny new editor

**Comment by macgivre07** [comment]
And bin congratulations then, it's very successful.
Even bravo and happy to see you take care of your mod, so practical and useful.
Congratulations to you.
