### ISSUE TITLE
Suggestion: Differentiate between map's IDs

### ISSUE THREAD

**Issue by Laifsyn** [blackd/Inventory-Profiles#115]
I dropped a ID:n map and it get replaced by a ID:n+1 map. Also don't know if it needs specific coding for compatibility(specifically More Villager's Fortresses/bastion maps, end city maps etc)

**Comment by blackd** [comment]
This mods works by simulating clicks on the inventory slots
The rest is handled by the server. Even in single player there is an embedded server which handles the real drop/move/use and so on.

**Comment by blackd** [comment]
The items are in no way manipulated by the mod. Actually when ever the mod needs to access the items the object data is copied before doing anything with it. So any anomalies with the items are caused by something else.
