### ISSUE TITLE
Hotkey for AutoRefill

### ISSUE THREAD

**Issue by GalaxysWithFiles** [blackd/Inventory-Profiles#116]
Could be nice to have a hotkey for autorefill, or be able to disable it with shulkers.

**Comment by blackd** [comment]
It is possible to disable auto refill for any type of item

it's a comma separated list

![Screenshot_20220227_095815-bured](https://user-images.githubusercontent.com/333840/155874040-b1fc439a-6ef2-4579-9132-e9784190b383.png)


to disable it for all shulker boxes you need to add these.
```
minecraft:shulker_box
minecraft:black_shulker_box
minecraft:blue_shulker_box
minecraft:brown_shulker_box
minecraft:cyan_shulker_box
minecraft:gray_shulker_box
minecraft:green_shulker_box
minecraft:light_blue_shulker_box
minecraft:light_gray_shulker_box
minecraft:lime_shulker_box
minecraft:magenta_shulker_box
minecraft:orange_shulker_box
minecraft:pink_shulker_box
minecraft:purple_shulker_box
minecraft:red_shulker_box
minecraft:white_shulker_box
minecraft:yellow_shulker_box

```

**Comment by blackd** [comment]
adding hotkey to temporary disable auto refill will have no effect because the moment the player enables it again refills with still valid conditions will be executed.
