### ISSUE TITLE
Ingoring screen and Container on a block that has both - crafting grid and inventory seemingly does nothing.

### ISSUE THREAD

**Issue by Lordomus** [blackd/Inventory-Profiles#117]
![image](https://user-images.githubusercontent.com/28005641/156702525-06653d0b-7c3f-4b16-b37a-b28454e867ed.png)

It looks like this. It works fine with igoring container buttons, but screen seemingly does nothing. Cannot even edit placement of those buttons (these two in the middle of crafting grid especially annoying)

MC 1.16
Forge: 36.2.29
Terraqueous:1.7.20
InvProfilesNext: 1.3.4

**Comment by blackd** [comment]
the 2 in the middle doesn't look like IPN buttons
also if you want to disable the buttons just select ignore and leave the rest. 

Ignore for both container and screen is the best in most cases but depending on the situation only one may be required 

the combination between ignore and player side only has. quite complex effect and is required in very specific cases

**Comment by Lordomus** [comment]
Nevermind, i've been dumb. I forgot i have quark. Those buttons look too similar sometimes. Sleepless nights do happen to get me.
