### ISSUE TITLE
Swipe moving doesn't work for hoppers.

### ISSUE THREAD

**Issue by blackd** [blackd/Inventory-Profiles#122]
### Original report by @flooorian1 moved from #121
This Feature doesn't work in Hoppers any more (Hopper -> Inventory is not working; Inventory -> Hopper still works). It worked with the 1.18.1 Version, but since updating to 1.18.2 its not working. I always have to click on every Stack in the Hopper, insteads of pressing Shift and swiping over the other Items.

**Comment by blackd** [comment]
Due to the changes in 1.18.2 which look like half baked 1.19 I'm postponing any fixed/features for after 1.19 release.

**Comment by blackd** [comment]
My tests show swipe move works fine.
But swipe throw doesn't but I'm sure it never did.

**Comment by flooorian1** [comment]
I tried again, without any other mods, just with:
- fabric release 0.13.3-1.18.2
- InventoryProfilesNext-fabric-1.18.2-1.3.5
- fabric-api-0.47.10+1.18.2
But its not working for me :/

https://user-images.githubusercontent.com/99684355/159170612-04a425c6-8d19-4a17-bed1-b63a860765ae.mp4

**Comment by blackd** [comment]
also post the list of mods

if you have other inventory management mods try disabling them
like:
mouse wheely
inventory scroller
inventory sorter

**Comment by flooorian1** [comment]
hi, below you can find all mods I have installed. But as mentioned, I put all mods (except InvTweaks and Fabric API) in a folder and tried without them, but this didn't work too.

bobby-3.1.1.jar
Capes-1.2.2+1.18   (1).jar
cloth-config-6.2.57-fabric   (1).jar
continuity-1.1.0+1.18.2.jar
cubeside-1.18.2-1.2.9.jar
fabric-api-0.47.10+1.18.2   (1).jar
fabric-language-kotlin-1.7.1+kotlin.1.6.10   (1).jar
indium-1.0.2+mc1.18.2.jar
InventoryHUD-fabric-[1.18]+-3.4.2   (2).jar 
InventoryProfilesNext-fabric-1.18.2-1.3.5   (1).jar
iris-mc1.18.2-1.2.2-build.32.jar
lambdynamiclights-2.1.0+1.17   (1).jar
litematica-fabric-1.18.2-0.11.0   (1).jar
logical_zoom-0.0.14.jar
malilib-fabric-1.18.2-0.12.0   (1).jar
minihud-fabric-1.18.2-0.22.0   (1).jar
modmenu-3.1.0 (1).jar
sodium-extra-mc1.18.2-0.4.2.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
tweakeroo-fabric-1.18.2-0.13.1   (1).jar
WorldEditCUI-1.18.2+01 (1).jar
XaerosWorldMap_1.20.3.1_Fabric_1.18.2   (1).jar
Xaeros_Minimap_22.3.0_Fabric_1.18.2   (1).jar

**Comment by blackd** [comment]
May be you have it disabled?

r+c opens the config
Mod Settings -> Also swipe move from chests or something like that

**Comment by flooorian1** [comment]
Oh well, it was actually disabled. The option Tweaks -> "Swipe Move Crafting Result Slot". was on false.

Just for your information: This is disabled by standard. I did a clean reinstall of Minecraft+Fabric+InvTweaks and it was on false there too.

Thank you for your help :)

**Comment by blackd** [comment]
I would appreciate if you start using the right name. You know it show some level of respect for the original author of this mod and me as some one that continues to keep it alive


Also I don't have this enabled and it still works for me. So you have some other problem.

**Comment by flooorian1** [comment]
Are you using the fabric 1.18.2 version? Because I don't know why you can't recreate the problem. I used a clean reinstall of Fabric, Fabric API and InvProfiles and shifting Items out of a Hopper does not work for me here. 

Maybe there is another option that can enable this, but I can't find it.

[> r+c opens the config Mod Settings -> Also swipe move from chests or something like that
](https://github.com/blackd/Inventory-Profiles/issues/122#issuecomment-1073283425)

I can't find that option.

**Comment by blackd** [comment]
Yes I'm absolutely sure which versions of the mod, minecraft, and fabric I'm testing with.
And that part of the code haven't been changed since I introduced the chest swipe move. Which is the setting just above the one you found.

Anyway you found solution to your problem. I will call it workaround. And will keep in mind to do more testing related to hoppers support.

**Comment by AspieGamer13** [comment]
I've had this same problem with the default settings for a while (since at least v1.3.5 when I first downloaded this mod), but the solution mentioned above does also work for me.

I tested both SMP and SSP.

For full clarity, my mod list:
	- appleskin 2.3.0+mc1.18.1
	- architectury 3.7.22
	- authme 2.2.0
	- betterf3 1.2.2
	- blur 2.4.1
	- bobby 3.1.0
	- carpet 1.4.57
	- cloth-config 6.2.57
	- entityculling 1.5.0
	- fabric 0.46.4+1.18
	- fps 1.18-1.1.0-Fabric
	- horsestatsvanilla 4.1.10
	- inventoryprofilesnext 1.5.0
	- iris 1.2.0-pre
	- lambdynlights 2.1.0+1.17
	- lightoverlay 6.0.4
	- litematica 0.10.2
	- lithium 0.7.7
	- malilib 0.11.7
	- minihud 0.21.3
	- modmenu 3.0.1
	- phosphor 0.8.1
	- raised 1.18.1-1.0.0
	- resounding 1.0.0-bc.8
	- shulkerboxtooltip 3.0.5+1.18
	- sodium 0.4.0-alpha6+build.14

Edit: (On re-read, I see fix won't be until 1.19 release)

**Comment by blackd** [comment]
for some unknown reason the hopper slots became more like crafting slots the like storage. And are now detected as crafting.
I'll probably have time for this at the end of the next month.

**Comment by blackd** [comment]
hopper handling updated to include all inventory management in 1.7.0
