### ISSUE TITLE
Filling Hoppers from a chest

### ISSUE THREAD

**Issue by LambertsCode** [blackd/Inventory-Profiles#123]
when I use a chest to store items to go into a hopper for coal or ore it doesn't take from the next slot once the current slot is empty. It will only take from the first slot. For some reason it works with seeds just fine.

**Comment by blackd** [comment]
Our mod doesn't in any way influence how hoppers and chests work. 
The reason for your problem is else ware. 
I guess you can test this it by removing the mod and see of the problem persists.
