### ISSUE TITLE
[1.18.2][Fabric] Inmpatibility with Fabrication

### ISSUE THREAD

**Issue by Anoaxx** [blackd/Inventory-Profiles#124]
Soo... i tested it out. This two mods somehow don't work with other. It not depends on config. This is my [latest.log](https://github.com/blackd/Inventory-Profiles/files/8356449/latest.log)
 
 Im gonna investigate this more, but im don't know how much time is gonna take. im waste half of a day on founding this one incompatibility. If anything is gonna pop out im gonna add that to the post.

**Comment by Anoaxx** [comment]
oh! and this is the place i get Fabrication for 1.18.2: https://github.com/unascribed/Fabrication/releases/tag/v2.3.0 but short investigate on latest.log showed me that the problem is with IPN not Fabrication. I don't know what currently breaks, but something is.

**Comment by blackd** [comment]
Well for now I can tell that something is loading my classes before the mod entry point have been executed. 
The leave the mod internals not initialised ad causes the exception.

**Comment by blackd** [comment]
I need to prevent the happening in future.

IPN over reliance on unchanged startup sequence has a part in the issue and it will be better that I rework this part of the code.

**Comment by blackd** [comment]
@Anoaxx :1st_place_medal:  Kudos for being so thorough and finding the other incompatible mods.

**Comment by Anoaxx** [comment]
> @Anoaxx 🥇 Kudos for being so thorough and finding the other incompatible mods.

8 hours of a day wasted, but thanks <3

**Comment by blackd** [comment]
removed the possibility of this happening again with  4836dbd, release to fallow.
