### ISSUE TITLE
Offer: sort by number of items

### ISSUE THREAD

**Issue by DrSigma4164** [blackd/Inventory-Profiles#125]
You can add a sort rule that would sort the contents of the inventory according to the following rule: first there will be the most items in the inventory, then less, and so on.
That is, if I have in stock 156 wheat, 20 apples and 70 fish, then first there will be 2 and a half (approximately) stacks of wheat, then 1.5 stacks of fish and then 20 apples.

**Comment by blackd** [comment]
well I forgot about this. it has been available for some time now
