### ISSUE TITLE
How to disable this

### ISSUE THREAD

**Issue by toffi3** [blackd/Inventory-Profiles#127]
I am on latest version of 1.18.1
![obraz](https://user-images.githubusercontent.com/84127414/162640106-93d16d1a-1562-4537-9892-320e3d30e1b1.png)
i am asking cause it's very annoying. It wasn't a feature on forge version

**Comment by blackd** [comment]
R+C in game opens the config.
All related settings are in the auto refill tab in the notification s section you can change, enable and disable  the notifications
