### ISSUE TITLE
change button location

### ISSUE THREAD

**Issue by Epikest** [blackd/Inventory-Profiles#129]
this mod and another mod i use share the same button space, is there a way to change where the buttons appear?
![image](https://user-images.githubusercontent.com/45499416/163297187-608a5250-612a-44be-94ad-fdf13207f32d.png)

**Comment by Epikest** [comment]
i got it, was `r` + `g`

**Comment by blackd** [comment]
Just out of curiosity. Did you ask the same question the other mod developers?

**Comment by Epikest** [comment]
> Just out of curiosity. Did you ask the same question the other mod developers?

nope, just opened an issue here and then surfed mod menu for a bit
