### ISSUE TITLE
Locked empty slots can still pick up dropped items.

### ISSUE THREAD

**Issue by blackd** [blackd/Inventory-Profiles#13]
I'll leave this here instead of making a new issue since it's kinda related.

locked empty slots can still pick up dropped items.

_Originally posted by @Cinmyr in https://github.com/blackd/Inventory-Profiles/issues/11#issuecomment-869184393_

**Comment by blackd** [comment]
I've found a way to fix this. And I'm making it configurable. The question is should I change the current behaviour... potentially angering the crowd or should I leave it.

In both cases this will be configurable.

**Comment by blackd** [comment]
fixed in 5ec8b0b

**Comment by Haano137** [comment]
Thank you for your hard work

**Comment by blackd** [comment]
Well this doesn't seem to work on servers well i've tested with paper so far

**Comment by blackd** [comment]
Well it looks the client plays no part in the decision where to put the picked up items when connected to a server. So far it looks like the client just receives a packet telling it what happened.

I guess an elaborate scheme where stuff are moved around/thrown away after the fact is possible so I'll leave this open for now.

**Comment by blackd** [comment]
fixed for servers in b5c55961d3d3cf84243b4ebf637ab91953e253a8
