### ISSUE TITLE
Crash when loading world java.lang.NoSuchMethodError: 'java.util.Set net.minecraft.world.item.Item.getTags()'

### ISSUE THREAD

**Issue by BrandonKhoo** [blackd/Inventory-Profiles#130]
Fresh install of both forge 1.18.2 and latest InventoryProifilesNext-forge-1.18.2

Crash log attached
[crash-2022-04-16_16.16.41-client.txt](https://github.com/blackd/Inventory-Profiles/files/8500719/crash-2022-04-16_16.16.41-client.txt)

**Comment by blackd** [comment]
IPN is not even part of the execution!

**Comment by BrandonKhoo** [comment]
Looks like running JEI and IPN at the same time crashes for some reason
