### ISSUE TITLE
Rule @Default not Found

### ISSUE THREAD

**Issue by GalaxysWithFiles** [blackd/Inventory-Profiles#131]
Whenever i sort, it just move the items into a kind of "neat" way but doesnt actually sort them, whenever i click the button it says this:
![image](https://user-images.githubusercontent.com/95949301/163697380-a44dfc44-b048-4d94-b70f-7aeab7284b74.png)
And ive reset the confgi folder 2 times and redid my settings and it doesnt fix it.

**Comment by blackd** [comment]
This is the second time I've seen this. Last time the mod file was corrupted during download.
Can you please attach the mod file you have. And then download it again.

**Comment by blackd** [comment]
Also can you attach the log file from a run with the error present.

**Comment by GalaxysWithFiles** [comment]
[New Compressed (zipped) Folder.zip](https://github.com/blackd/Inventory-Profiles/files/8500987/New.Compressed.zipped.Folder.zip)
and idk how to send a log without it just being random characters
![image](https://user-images.githubusercontent.com/95949301/163700564-2cc346bf-4975-443c-ba26-8db9987982a2.png)

**Comment by blackd** [comment]
what is the minecraft version

**Comment by GalaxysWithFiles** [comment]
its the 22w15a snapshot

**Comment by blackd** [comment]
snapshots do introduce incompatibilities. that is why I put 22w13a is in the name.
At some point I'll update it.

**Comment by blackd** [comment]
fixed 
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/3781592
