### ISSUE TITLE
Paragliders "incompatibility"

### ISSUE THREAD

**Issue by Answordy** [blackd/Inventory-Profiles#132]
I don't know where I should post this issue, which mod is causing it. It's not a total incompatibility, rather a visual issue.
On the bargain screen of the Godess and Horned statues the icons of the items dissapaer. Everything else works, it's just a rather annoying visual problem, not a technical one. I tried to customize and turn off inventory profiles on the bargain screen with the overlay editor, but it didn't help nor work properly, because most of the things are being rendered off-screen, they are getting cut no matter the screen resolution, as shown on the second picture.
![2022-04-22_23 46 58](https://user-images.githubusercontent.com/82783515/164801211-e7534dd9-5906-4e83-8527-a077c09851f0.png)
![2022-04-22_23 57 10](https://user-images.githubusercontent.com/82783515/164801217-af6b87ca-4596-4db9-b64e-d303f5817f2a.png)
Also, for reference, it should look like this:
![2022-04-23_00 01 44](https://user-images.githubusercontent.com/82783515/164801554-3668642e-eb0c-4bea-b81e-cb6fe41395e8.png)

**Comment by blackd** [comment]
Hi,

Try setting Ignore first for the screen then for the container and then for both. One of these could help.

**Comment by blackd** [comment]
Oh you don't even see these... that is strange

**Comment by Answordy** [comment]
I tried to add them to the "player-defined" config, also created a config named paraglider in the folder with the contents: 
{
    "tictim.paraglider.client.screen.StatueBargainScreen": {
        "ignore": true
    },
    "tictim.paraglider.recipe.bargain.StatueBargainContainer": {
        "ignore": true
    }
}
I don't know if it's the right way, i just copied what i found there already, however it didn't help.

**Comment by blackd** [comment]
So far I can tell Paragliders is doing something strange while rendering the screen. That is why my editor is not showing properly and probably why he JEI icon is shifted.
I think Paragliders devs are in better position to handle this.

**Comment by Answordy** [comment]
Okay, thanks for your time! I created an issue there too, will see the results.

**Comment by blackd** [comment]
The editor usually looks like this
![2022-04-23_04 03 48](https://user-images.githubusercontent.com/333840/164845048-b9467472-3e97-4cd1-b86f-2d880ca91f6b.png)

**Comment by Answordy** [comment]
Yeah, i noticed the Jei icon being cut too, strange.

**Comment by blackd** [comment]
closing sice Paragliders intentionally try to mess with other mods UI
