### ISSUE TITLE
Compatibility with Inventorio?

### ISSUE THREAD

**Issue by maxface14** [blackd/Inventory-Profiles#133]
My dream combination of mods is Inventory Profiles Next and Inventorio, which was finally updated recently to support 1.8.2. The mods don't cause crashes with one another (except when trying to load a profile using a keyboard shortcut), but Santa Clause's reputation as Top Gift Giver would quake in fear of the gift of having these mods work in harmony together, allowing the utility belt, tool belt, and deep pockets inventory to be sorted with a button press and be configured with profiles.

**Comment by blackd** [comment]
My tests show that profiles are working fine both from the GUI and with shortcuts.
Please post logs from the crash. Also which modloader, version of the said modloader, version of both IPN and Inventorio.

**Comment by blackd** [comment]
I've tested with both Forge and Fabric and IPN and Inventorio they both work fine together.
Without logs I can't do more

**Comment by blackd** [comment]
closed due to lack of interest
