### ISSUE TITLE
Remove Update Nags or Allow Disabling

### ISSUE THREAD

**Issue by wendall911** [blackd/Inventory-Profiles#136]
Update nags are a real problem in modded Minecraft. I understand the intent, but when running 100 mods, which isn't unusual, if everyone does this, it is very annoying. I"d like to see this able to be configured. There are mechanisms in forge to do proper update lookups through mods.toml.

**Comment by blackd** [comment]
As everything else provided by this mod "update available" message can be disabled from the configuration screen.
The easiest way to open the config is pressing R+C in game.

**Comment by blackd** [comment]
Since this mod is modloader agnostic I try to keep the modloader specific parts at an absolute minimum, and the behaviour as close as possible.

So there will be no Forge specific update mechanism that makes the experience different from what the fabric version offers.
