### ISSUE TITLE
[1.16.5] Incompatibility with CoraiTombstone 

### ISSUE THREAD

**Issue by DrSigma4164** [blackd/Inventory-Profiles#137]
If I have a blocked Hotbar (ie I used to alt and cling to Hotbar, and now he's red), then after death, when I take things from the Corailtombstone grave they can't return to Hotbar, which is mod to turn things on Hotbari on Hotbar.
  Maybe I have turned on a feature that prevents items in these slots or something like that I attached my settings.

IPN version:1.3.8
CorailTombstone version: 6.7.5
Forge: 36.2.33
MyProfile: https://gist.github.com/a5c6eba1774ea7fceaa522e81cb8668c.git

**Comment by blackd** [comment]
there is a setting "Enable Picking Items into Empty Locked Slots" you might try toggling
