### ISSUE TITLE
Suggestion: items blacklist

### ISSUE THREAD

**Issue by lynrayy** [blackd/Inventory-Profiles#143]
Add list for items that will not be picked-up or taken from chest. For example: rotten flash, diorite, granite, string, spider eye etc.

**Comment by blackd** [comment]
So you want to modify how move all works. I don't really like this. 

you can currently achieve this by move only the matching items and/or move only single type of items.

**Comment by lynrayy** [comment]
I want to disable picking up rotten flash etc. when mining in cave. I can block slots but then I won't be able to pick up useful resources

**Comment by blackd** [comment]
this was already suggested #18 and rejected

**Comment by lynrayy** [comment]
Any alternative then?

**Comment by blackd** [comment]
I solve this problem by spreading the desired items in the empty slots.
Like if you want to only pickup stone put 1 stone into all empty slots.
