### ISSUE TITLE
How to change mods to another language

### ISSUE THREAD

**Issue by beryl801** [blackd/Inventory-Profiles#144]
Sorry my English is not very good, I want to change the language of the mod to Chinese. How can I do this?

**Comment by blackd** [comment]
if minecraft language is set to Chinese the mod will automatically be in Chinese

**Comment by beryl801** [comment]
> if minecraft language is set to Chinese the mod will automatically be in Chinese

Because I'm using Traditional Chinese, but the mod translation is Simplified Chinese
If I switch the game language to Simplified Chinese, the mod will be automatically translated
But if I switch back to the traditional Chinese , it will automatically run back to English
I want the game to use traditional Chinese and the mod to use simplified Chinese
Is there a way to manually set the language of the mod?
Thank you!

**Comment by blackd** [comment]
> I want the game to use traditional Chinese and the mod to use simplified Chinese
> Is there a way to manually set the language of the mod?

this is not possible. 
but if you want you can translate the Simplified Chinese to Traditional and I'll include it in the next release.

**Comment by beryl801** [comment]
> > I want the game to use traditional Chinese and the mod to use simplified Chinese
> > Is there a way to manually set the language of the mod?
> 
> this is not possible. but if you want you can translate the Simplified Chinese to Traditional and I'll include it in the next release.

OK,
Thank you for such a quick reply
i will try to translate it
