### ISSUE TITLE
[Feature] Save item positions in inventory in addition to the hotbar

### ISSUE THREAD

**Issue by gael-vanderlee** [blackd/Inventory-Profiles#145]
Coming from Inventory tweaks, it would be nice for this mod to sort your inventory as well as your hotbar.

**Comment by blackd** [comment]
you can arrange the hotbar with the profiles

https://inventory-profiles-next.github.io/profiles/

**Comment by blackd** [comment]
hmm the title and the description say different thing

which one is it

**Comment by gael-vanderlee** [comment]
The only item positions that are saved in the profiles are those in the hotbar. The rest of the inventory is rearranged when you apply the profile. It would be nice to be able to save item positions in the inventory as well. 
For example if I always put my torches somewhere in the inventory (not the hotbar), itn would be nice to have a way for the mod to remember that.

**Comment by blackd** [comment]
you can use profiles and locked slots to achieve similar results

alt+click locks the slot

**Comment by gael-vanderlee** [comment]
Sounds good! I'll try this. 

Adding some ideas here so as not to create many requests, though I can if you'd prefer. Here they are in order of importance. 
- Ability to overwrite profile rather than create a new one each time you press the Save Shortcut
- Have a way to keep certain slots empty
- Ability to select item categories when editing the txt (minecraft:cooked_food for example). I guess you could add all items in that category one by one but that's not really user friendly. 
- Ability to share profiles between saves
- Have a tutorial which presents the features of this mod (video or text). Much like the one you have for profiles which is quite good. 
- Have the mod settings along with the other mod settings (in the mod menu)

**Comment by blackd** [comment]
> * Ability to overwrite profile rather than create a new one each time you press the Save Shortcut

the idea is to save multiple settings so the player can save all the states they need before editing the files

> * Have a way to keep certain slots empty

it is possible 
```
profile Naked
    HEAD
    CHEST
    LEGS
    FEET
```

> * Ability to select item categories when editing the txt (minecraft:cooked_food for example). I guess you could add all items in that category one by one but that's not really user friendly.

this information is not available/usable client side 


> * Ability to share profiles between saves

you will need to expand on this. I suggest you join our discord server and we can talk.


> * Have a tutorial which presents the features of this mod (video or text). Much like the one you have for profiles which is quite good.


this is work in progress 

> * Have the mod settings along with the other mod settings (in the mod menu)


it's been there for as long a this and the original mod have existed

**Comment by gael-vanderlee** [comment]
Thanks for the response! I'll take this discussion to the discord.
