### ISSUE TITLE
[Suggestion] Support for non-English keyboards

### ISSUE THREAD

**Issue by agent-LuluDodo** [blackd/Inventory-Profiles#148]
### Suggestion
Hi, I noticed some Keys get displayed incorrectly with Keyboard layouts different from English. My Keyboard for example has the 'y' and 'z' keys flipped. They still work as intended, so it's just a minor incontinence. 
My guess is that you get the key code and use a lookup table for the character. 
Also, the mod is awesome!
### Implementation
I have no experience with Kotlin, but I did some research and found the functions [getDisplayLabel()](https://developer.android.com/reference/android/view/KeyEvent.html#getDisplayLabel%28%29) and [getUnicodeChar()](https://developer.android.com/reference/android/view/KeyEvent.html#getUnicodeChar()). I don't know if you already use these / they are not usable in the situation or if the Problem is just something with me, but I thought I would let you know :)

**Comment by blackd** [comment]
yes a lookup table is used

the suggested apis are android specific. 

minecraft uses opengl scan codes I'll check if there is information about the scan code translation.

**Comment by agent-LuluDodo** [comment]
Oh, ok.
