### ISSUE TITLE
Wrong Modloader check?

### ISSUE THREAD

**Issue by XiNaru** [blackd/Inventory-Profiles#149]
sry but Inventory Profiles Next-forge-1.16.5-1.5.3 is not working. my minecraft still says I need FABRIC although the file name explicitly says forge.
same with the 1.5.2...
its very bad.........

**Comment by blackd** [comment]
can you post screenshot

**Comment by XiNaru** [comment]
I have to apologize.
I must have been BLIND.....
It wasn't the message because of the mod, but because curseforge didn't uninstall the fabric api when uninstalling the fabric version that was accidentally installed. THIS is why the error came. now it works.

I really have to apologize again.

**Comment by blackd** [comment]
can you pleases post that the problem isn't cased by the mod on curseforge too

**Comment by XiNaru** [comment]
I changed my post on curseforge and wrote wrong post. I don't want to spread false errors :)
