### ISSUE TITLE
[Suggestion] 1.18.2 Add InventoryProfiles sorting type for AE2 terminal

### ISSUE THREAD

**Issue by HonzaVinCZ** [blackd/Inventory-Profiles#151]
I'd like to ask you to add your sorting types into Applied Energetics 2 terminal like the Inventory Tweaks had. It would make AE2 terminal sorting much better. Today there is no useful sorting. Using your mod because it has the same sorting as Inventory Tweaks had and afaik there is no similar mod for 1.18.2 Forge yet.

**Comment by blackd** [comment]
can you provide me a world with terminal in question.. actually with as many  Applied Energetics 2 inventories as possible.

I need something to test with and  Applied Energetics 2 is structures/blocks are not easy to create unless you played the mod.

**Comment by HonzaVinCZ** [comment]
Here is AE2 sample world.
https://www.dropbox.com/s/c0k8p7z4mjz83ko/AE2_Sample.zip?dl=0

Minecraft version: 
- 1.18.2

Mods used:
- appliedenergistics2-11.1.4
- InventoryProfilesNext-forge-1.18.2-1.5.3

**Comment by blackd** [comment]
fix for the swipe move problem is now available in v1.6.1
