### ISSUE TITLE
Locked Slots over/underlays shoud honor Ignore hints. 

### ISSUE THREAD

**Issue by DrSigma4164** [blackd/Inventory-Profiles#152]
When I open the interface of any computer, and the slots are blocked, the following visual bug appears:
![image](https://user-images.githubusercontent.com/93322905/178412145-fc72373c-793e-4155-89cd-44a409844b7a.png)

**Comment by blackd** [comment]
by default R+G opens the GUI editor. 
set ignore to true for the Screen

**Comment by DrSigma4164** [comment]
This has already been done. It didn't help

**Comment by blackd** [comment]
have you tried any other combination like ignore true for the container?
Please provide as much information as possible in the issues. So I don't have to ask about the basics.

**Comment by blackd** [comment]
is it forge? or fabric... or quilt

**Comment by DrSigma4164** [comment]
This is Forge, version 36.2.34.
Mod version: 1.5.3
CC:Tweaked mod version: 1.100.8
Here's the block where it doesn't work: computercraft:computer_advanced
Tried in all possible combinations, both in the container and on the screen.
This error disappears when there are no blocked slots on the hotbar.

**Comment by blackd** [comment]
fixed in 564fdfe
