### ISSUE TITLE
Loading Profile Settings Failed: msg=mismatched input "protection".

### ISSUE THREAD

**Issue by jmmd2000** [blackd/Inventory-Profiles#153]
Hi there,
Followed the quick guide on the wiki. Set the profile to just be my normal armour, tools, food and rockets. I open the profiles.txt file, I change the name to "Gear", save and close the file. When I hit R + Y, I get this error: 
![image](https://user-images.githubusercontent.com/63932603/178957835-e2e86601-4bed-43c9-948e-13f6a735bccb.png)

**Comment by blackd** [comment]
attaching the config would help

**Comment by jmmd2000** [comment]
Oh yeah true, my bad!
[profiles.txt](https://github.com/blackd/Inventory-Profiles/files/9111096/profiles.txt)

**Comment by blackd** [comment]
looks like the HEAD slot was added by hand and all the enchantments are missing the "minecraft:" namespace

**Comment by jmmd2000** [comment]
That's bizarre. The only thing I changed was the "Saved" keyword to the name of the profile. I added in "minecraft:" before each enchantment and it works now! Odd one, but thanks for your help! Fantastic mod!
