### ISSUE TITLE
my alt click doesn't work since the 1.16 version of the mod

### ISSUE THREAD

**Issue by butterbrine22** [blackd/Inventory-Profiles#157]
I have used this mod for a little wile but I never ran into a problem before but now I cant "hotkey move" all of one item type like if i have 7 stacks of cobblestone in my inventory and I wanted to put all that into a chest with only one click it would before just move all the stacks from my inventory to the chest but now it just locks the slot and wont do anything I have tried to change some stuff after encountering this but I cannot figure out what to do and I don't know anything about the config/settings for this mod

**Comment by blackd** [comment]
if it's fabric remove mouse wheelie

**Comment by blackd** [comment]
there was no answer to a very simple question for 17 days
