### ISSUE TITLE
slots from other mods

### ISSUE THREAD

**Issue by Jaaaaas** [blackd/Inventory-Profiles#158]
Is it possible to make profiles work with slots from other mods like trinkets?

**Comment by blackd** [comment]
I doubt it's possible without any changes in the other mods.

The reason profiles work for vanilla hotbar is that the inventory is available for manipulation at all time even if not shown. Most mods don't do allow that.

**Comment by Jaaaaas** [comment]
you can equip items into trinkets slots by rightclicking them from hotbar with closed inventory so I think they are available for manipulation

**Comment by blackd** [comment]
this may look like exactly what I'm talking about but it's not. Using an item from the hotbar, I.e. right clicking while it's in the main hand, is handled server side.
