### ISSUE TITLE
With the pick-up-items-directly-to-inventory feature enabled, you can’t pick up items if your main inventory is full

### ISSUE THREAD

**Issue by Nevrai** [blackd/Inventory-Profiles#164]
With the new “Pick items directly into the Inventory” feature introduced in Inventory Profiles Next version 1.6.3, you aren’t able to pick up items if your main inventory is full, even if your hotbar has space. I’m not sure if this is a bug or if it’s intended. If it is intended, an option to allow items to go into your hotbar only if your main inventory is full would be fantastic.

[Mod list.](https://pastebin.com/raw/NJMhiDrJ)

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.69 (latest)
* **Inventory Profiles Next:** 1.6.3 (latest)

**Comment by blackd** [comment]
single player or server?

**Comment by Nevrai** [comment]
I’m playing on a single-player world.

**Comment by blackd** [comment]
as a workaround 
set `Mod Settings` `debug` to true
close the config and open it again
I the Debug page set locked slots force server method to true

I'll release a fix soon

**Comment by blackd** [comment]
fixed in 4accac6

**Comment by Nevrai** [comment]
Awesome! Thank you so much!
