### ISSUE TITLE
IPN crashes on startup

### ISSUE THREAD

**Issue by loleriz** [blackd/Inventory-Profiles#166]
![image](https://user-images.githubusercontent.com/2032606/183492689-5c7e7d8e-9701-472d-a5d2-cf7c5301263d.png)

Here is the dump: https://pastebin.com/raw/vMRC727P

Running:
Forge 43.0.2
kotlinforforge-3.6.0-obf
InventoryProfilesNext-forge-1.19-1.6.3

**Comment by blackd** [comment]
https://github.com/thedarkcolour/KotlinForForge/issues/46

**Comment by loleriz** [comment]
saw it was closed already. read the other discussion. dangit, kotlin!

**Comment by thedarkcolour** [comment]
Fixed in Kotlin for Forge 3.7.1 :)
