### ISSUE TITLE
Incompatibility with MoreOverlays concerning Visual Glitches

### ISSUE THREAD

**Issue by Jayryn** [blackd/Inventory-Profiles#167]
I've noticed that there is an issue with Item Amount Visual Glitches when using both InventoryProfilesNext and [MoreOverlays-Updated](https://github.com/r8420/MoreOverlays-updated) when using the search item container function for JEI Search by MoreOverlays. 

As MoreOverlays [[CURSEFORGE]](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated) is a widely known and used distribution for many use cases as well as modpacks together with InventoryProfilesNext, this incompatibility may be determined and eliminated, if you would agree.

**As I believe many users to want to use both mods simultaneously, I hope that this issue will not be marked as "will not fix".**
[Please let me know if you agree too.]

I've already informed the Author of MoreOverlays-Updated in the issue.
[Link to Issue](https://github.com/r8420/MoreOverlays-updated/issues/40)

**Issue Explanation Video**
[Preview of Visual Glitch](https://user-images.githubusercontent.com/77808206/183471617-b1e19dd6-8045-4552-a4a9-edc37da76071.mp4) [Video]

**How it should look**
[This is without comparability issue](https://user-images.githubusercontent.com/77808206/183471644-48782c40-b8a9-4786-8e59-c0ddf235598e.mp4) [Video]

**Comment by blackd** [comment]
have you tried disabling the matching items highlight of IPN

**Comment by Jayryn** [comment]
> have you tried disabling the matching items highlight of IPN 

Not yet but I'll try this in a moment, thank you for the suggestion.

**Comment by Jayryn** [comment]
@blackd If you mean these settings, I have disabled them and the issue still persists. 
![image](https://user-images.githubusercontent.com/77808206/183519290-a2f7bb45-cef2-40da-9e83-e6077b93987e.png)

**Comment by Jayryn** [comment]
This solution worked for me.

![image](https://user-images.githubusercontent.com/26418513/183523142-2d2e687d-865d-4c2e-b3fb-34d05070f571.png)

https://github.com/r8420/MoreOverlays-updated/issues/40#issuecomment-1208667043

**Comment by blackd** [comment]
technicaly this setting has effect only if you have setup click delay and only while sort/move... is being executed

**Comment by Jayryn** [comment]
As I believe many other people to experience this issue sometime, could you move such highlight settings to another submenu as I seem to find it difficult to locate it.

**I imagine something like:**

![image](https://user-images.githubusercontent.com/77808206/183525739-0d85b0c6-4166-4d12-9ce4-c4d7adb62e1c.png)


Highlights (eg. like Tweaks)

> Disable All Highlights
(Toggle all of the settings below without toggling them)

> Enable Items Highlight

> Highlight Clicking Slot

> Enable Highlight Blinking

**Comment by Jayryn** [comment]
> technicaly this setting has effect only if you have setup click delay and only while sort/move... is being executed 

It was somehow activated for me although I have "Add Interval Between Clicks" disabled and didn't sort while hovering over the items

-> The visual glitch happend when I hovered over some item.

Somehow this setting still fixed it

**Comment by blackd** [comment]
I tried to reproduce this but with no success

**Comment by r8420** [comment]
> I tried to reproduce this but with no success

I am able to reproduce this issue with the latest versions of these mods (Forge 43.1.2):
- InventoryProfilesNext-forge-1.19-1.6.5.jar
- kotlinforforge-3.7.1-obf.jar
- moreoverlays-1.21.3-mc1.19.jar
- jei-1.19.2-forge-11.2.0.256.jar

Steps to reproduce:
- Fill a chest with multiple stacks of different resources.
- Double-click the JEI search bar to enable the JEI item filter from moreoverlays.
- Put some random text in the search bar.
- Hover over the stacks that have a gray filter above them.

The item amount will be white when hovered and gray when not hovered.

The issue does not occur when highlight_clicking_slot is set to false.

**Comment by blackd** [comment]
fixed in mod version 1.7.0
