### ISSUE TITLE
CurseForge mark on Inventory Profiles Next compitable with 1.19.2

### ISSUE THREAD

**Issue by Disguys** [blackd/Inventory-Profiles#168]
Hello, please put a note on CurseForge that it is compatible with 1.19.2, I need it for the Modpack.

**Comment by blackd** [comment]
i was hoping to avoid that.. 
updating it manually messes up the youtube embed :)

anyway done

**Comment by Disguys** [comment]
> i was hoping to avoid that.. updating it manually messes up the youtube embed :)
> 
> anyway done

It's strange why it hasn't changed
![image](https://user-images.githubusercontent.com/60795989/183709281-f21e048d-3533-4eb2-bf72-e3ef5a77b7d0.png)

**Comment by blackd** [comment]
![изображение](https://user-images.githubusercontent.com/333840/183709702-0e4c7fbb-6077-4f60-a20b-cd15b3432509.png)

**Comment by blackd** [comment]
oh it's fabric you need
