### ISSUE TITLE
InventoryProfiles adds the buttons to anything that is a ContainerScreen.

### ISSUE THREAD

**Issue by githubbingitup** [blackd/Inventory-Profiles#17]
Not a bug, but more of a design issue likely from the original creator.
Mods that add overlays over the inventory often end up having InventoryProfiles buttons on them, which can kind of get in the way.

CleverNucleus pointed out to me that this code here: https://github.com/jsnimda/Inventory-Profiles/blob/c47487b060f51411d9b105d9296781a9c38fa832/src/main/java/io/github/jsnimda/inventoryprofiles/gui/inject/ScreenEventHandler.kt#L13
is adding the sorting buttons to anything that's a container screen without checking if said container has an inventory or not.
The only downside to this is any mods that might expand the inventory end up having these buttons present.

Would require it being reworked to fix that, but figured I'd post it here since this can happen in modpacks.
I don't think it happens with the other inventory sorting mods, but can't remember.

**Comment by blackd** [comment]
Containers can be sorted too, so the buttons are added.
As for the UI getting in the way...  all parts of the mod UI can be disabled. This is the best I can suggest.


Also if you can provide example mods that have clashing UI or expand the inventory so I can see if anything can be done about it. But tbh I suspect that anything short of a rewrite will not be enough. And at this point I'm not willing to do that.

**Comment by githubbingitup** [comment]
The main one I've tested is PlayerEx as its menu sits on top of the inventory.
Fortunately it doesn't seem to cause any problems, even if you click them. So its really just a minor visual flaw.

 I'll post a screenshot later.

**Comment by blackd** [comment]
So... This is an interesting issue. For now I'm adding new configuration option to disable the buttons for no vanilla screens.

Real fix would be to add API for other mods to inform us which of their screens are indeed storage/inventory so we can only enable the buttons for them so I opened new issue #19.

I'll close this issue when the configuration option is ready

**Comment by blackd** [comment]
fixed in 054539c see #19 for more info
