### ISSUE TITLE
Temporary ban on hypixel

### ISSUE THREAD

**Issue by XandarNull** [blackd/Inventory-Profiles#170]
I was using the mod and playing on hypixel when one item added by the server in my inventory started appearing and disappearing, then I got banned for "Cheating through the use of unfair game advantages"
and according to their rules on [disallowed modifications](https://support.hypixel.net/hc/en-us/articles/6472550754962) they state that "we do also note that anything which automates any player gameplay action is strictly disallowed"
have you ever gotten anything like this? and if so, is there an option to disable the mod on multiplayer only.

**Comment by blackd** [comment]
I guess "pickup directly into inventory" was the problem.

> is there an option to disable the mod on multiplayer only.

No and I don't really plan to do something like that.

**Comment by blackd** [comment]
Hypixel "compatibility"/circumvention has never been planed.

a quick google search yielded this https://hypixel.net/threads/solved-mod-help-banned-but-no-idea-what-triggered-it.4657576/

**Comment by XandarNull** [comment]
well, the item was put automatically put in my inventory (slot number 5) it was a block for the dancing game or whatever it's called where it gives you a block and you have to stand on it based on the color of the block. so you think disabling the pickup directly into inventory would fix that? i really like the mod and i don't want to stop using it yet don't want to get banned again
