### ISSUE TITLE
[Probably All Vers] Compatibility problem for mods "Inventorio" ("Quark"?), "Carry On" and "Players Tab"

### ISSUE THREAD

**Issue by DanteTooMayCry** [blackd/Inventory-Profiles#172]
"Inventorio" adds a leg enchant that adds extra space. They are not supported by the IPN. Quark has something similar, only in the form of a backpack (with addon "oddities"). I don't use, so I don't know, but I suspect there will be a similar incompatibility.
And IPN inventory buttons overlap this additional space.

"Carry on" allows you to pick up mobs and boxes. Unfortunately, the IPN means that I cannot put it back, and I cannot see the raised thing in my hands. You also can pick up one by one and only slowness increases.

"Players Tabs" adds tabs at the bottom of the inventory screen. When switching between tabs, the same IPN slot locks always remain. Perhaps half the solution would be to set profiles, but here is an additional problem - the tabs are in the same place as changing profiles. To be able to change tabs, you need to turn off the visibility of this element in the interface settings

Probably it isnt important here, but Forge 1.18.2-40.1.68

![2022-08-15_14 14 13](https://user-images.githubusercontent.com/108282775/184856604-90ca337d-1143-46ba-9832-6e7169bc25a6.png)
.

**Comment by blackd** [comment]
by default the gui editor is available by pressing r+g 
form there on you can move the buttons where ever you like them.

Unfortunately when it comes to combination of mods there are no safe defaults I can include.

**Comment by sayore** [comment]
Can confirm the Carry On problem, you pick up a chest and it(the item carry on uses to show you carry it) get's auto moved into the inventory kinda at random.
You can still put it down, but you need to switch to the item, AND carry on wants this item to be in a specific slot.

**Comment by blackd** [comment]
I guess for Carry On you need to disable the third option here:

![image](https://user-images.githubusercontent.com/333840/184920205-af02f13a-c89a-40b3-85bc-debf6b129229.png)

**Comment by blackd** [comment]
@DanteTooMayCry In future please don't report unrelated problems in one issue. Open multiple.

I totally missed the Carry On part.

**Comment by sayore** [comment]
> I guess for Carry On you need to disable the third option here:
> 
> [image](https://user-images.githubusercontent.com/333840/184920205-af02f13a-c89a-40b3-85bc-debf6b129229.png)

i will try this and report back on how it behaves 👍

**Comment by sayore** [comment]
Works fine!

**Comment by DanteTooMayCry** [comment]
> I totally missed the Carry On part.

My bad. But I can confirm that it works.

Unfortunately, Gui editor wont open. I changed hot key but it not helped. So far, I cant find a reason.

**Comment by blackd** [comment]
there is a button that opens it its in the top left under the other stuff there

**Comment by DanteTooMayCry** [comment]
I found the reason. Gui editor only opens when inventory is open :D.

**Comment by blackd** [comment]
you can change the gui for every type of storage

**Comment by DanteTooMayCry** [comment]
Yes. Thx a lot. All works fine.

Is there any chance that will be added lock compatibility for extra space for different mods?

**Comment by blackd** [comment]
> Is there any chance that will be added lock compatibility for extra space for different mods?

Probably not.
Unfortunately most mods that offer extra space do it in incompatible ways
