### ISSUE TITLE
[Suggestion/Bug] 1.6.4, "Pickup to inventory"

### ISSUE THREAD

**Issue by Mitchell5200** [blackd/Inventory-Profiles#173]
Hello, is there a way to turn off the "pickup to inventory" function without losing the locked slots functions, as i like having locked slots but the "pickup to inventory" function is not "for me", 
If there is a way, can i request a new button for it.

**Comment by blackd** [comment]
yes, the third option in the locked slots page of the config.

**Comment by Mitchell5200** [comment]
*facepalm* i looked at the main mod settings page, oops, thankyou for the rapid response
