### ISSUE TITLE
How do I turn off item highlighting? 

### ISSUE THREAD

**Issue by xotrikspl** [blackd/Inventory-Profiles#175]
How to off this - ![image](https://user-images.githubusercontent.com/46033214/185808530-5c4c57db-37a7-4bb6-b7e6-294ee897e2ac.png)
and this - 
Picked up items will now go directly into the inventory instead of taking hotbar space. This can be changed in the Locked Slots tab of the config.
https://youtu.be/zj1DzMvXO9Q

**Comment by blackd** [comment]
for support use the discord server

it's in Mod Settings - highlighting

**Comment by xotrikspl** [comment]
Discord server?

**Comment by blackd** [comment]
it's in the description of the mod on curseforge and Modrinth and also 8n the readme of this repository

**Comment by xotrikspl** [comment]
nice help..
