### ISSUE TITLE
[Single Player] Enable swiping and moving same items for locked slots

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#176]
I am currently using locked slots to prevent part of my inventory from picking up items, and I have the option to Disable Shift Click and Ctlr Q and Q to disabled. However, when I try to either 'move items of the same type' or swipe them into another inventory this isn't possible and I have to shift click each stack. Can we please have an option to turn this back on so I can use the locked slots as strictly 'non-pickup' slots with all other functionality as normal?

I play on Minecraft 1.19, with forge 41.1.0 and the mod version 1.6.5. Thank you very much!

**Comment by blackd** [comment]
You can set the `Quick Disable` key and use that while shift swiping. `Space` works best for me

![изображение](https://user-images.githubusercontent.com/333840/185899252-db8c9a41-37dc-4638-b5af-6f70a75b77cb.png)

**Comment by ghost** [comment]
I tried that, but it immediately starts filling up my locked slots with items that I was preventing it from picking up. I need a way to completely block those slots from picking up items as I am using those slots to craft into, and if they are already full crafting a lot is a real PITA. If a future version would have an option to enable these options without quick disable I would really appreciate that!

**Comment by blackd** [comment]
**picking up items in locked slots is possible while the inventory is open anyway**

Hi can you please join our discord server so I can ask you some questions.
https://discord.gg/23YCxmveUM
