### ISSUE TITLE
[1.16.5+] Incompatibility with Project E - Need to exclude transmutation interface

### ISSUE THREAD

**Issue by AerosAtar** [blackd/Inventory-Profiles#177]
For compatibility reasons, screen `moze_intel.projecte.gameObjs.gui.GUITransmutation` needs to be excluded from the inventory button and hotkey functionality of this mod.

* The buttons don't quite fit properly (see first screenshot) and have no relevant function for this interface.
* The hotkeys interfere with the search functionality and have no relevant function for this interface.
  * Example: Attempting to search for "di**r**t" causes the hotkey to trigger, which creates a bunch of random items from the pool and throws them into random slots in the interface (see second screenshot).

In a more general sense: Allowing the 'blacklisting' of interface screens (screens that the mod should ignore when adding buttons/hotkey functions) using the configuration, similar to how Quark handles their inventory buttons, would be a good QoL enhancement, as would the ability to remap the hotkeys using the "controls" menu.

![image](https://user-images.githubusercontent.com/13503100/186055880-b3f996bc-07c7-47ed-bd07-faa0c4da5fa2.png)
![image](https://user-images.githubusercontent.com/13503100/186057145-39f7c985-8f54-46e5-93a8-c54431e21672.png)

**Comment by blackd** [comment]
by defaut the gui editor screen is opened by pressing r+g while the gui in question is opened
if the key combination doesn't work there is a button in the left top corner.

**Comment by blackd** [comment]
setting ignore to true for the screen should be enough

**Comment by blackd** [comment]
changing the key binding is possible form the menu config by default accessible by pressing r+c in game
or through the mods button.
