### ISSUE TITLE
inventory profiles next перемещение поднятых предметов в инвентарь

### ISSUE THREAD

**Issue by SHOT-MASTER** [blackd/Inventory-Profiles#178]
помогите настроить мод inventory profiles next для игры Minecraft .
Когда я поднимаю предмет он сразу же перемещается в инвентарь минуя горячие слоты (которые отображаются без открытия инвентаря).пожалуйста помогите с настройками, заранее спасибо!
help set up the inventory profiles next mod for Minecraft. When I pick up an item, it immediately moves to the inventory bypassing the hot slots (which are displayed without opening the inventory). Please help with the settings, thanks in advance!

**Comment by blackd** [comment]
please don't polute github with support questions.

ask on discord

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/191315747-6e49f2c4-250b-465f-95f1-85af0d738aae.png)
Используй это. Разраб зачем то включил это по умолчанию
Вкладка "Запертые слоты" или как то так слева
