### ISSUE TITLE
1.19.2 versions on Modrinth are not marked 1.19.2-compatible

### ISSUE THREAD

**Issue by triphora** [blackd/Inventory-Profiles#179]
Namely the following four versions:
https://modrinth.com/mod/inventory-profiles-next/version/fabric-1.19.2-1.6.5
https://modrinth.com/mod/inventory-profiles-next/version/forge-1.19.2-1.6.5
https://modrinth.com/mod/inventory-profiles-next/version/fabric-1.19.2-1.6.4
https://modrinth.com/mod/inventory-profiles-next/version/forge-1.19.2-1.6.4

I've gone in and updated them as an admin, but you may want to update your buildscripts to add the version automatically.

**Comment by blackd** [comment]
I the build system underwent some clean up and I have probably broken something.
