### ISSUE TITLE
Auto-Drop

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#18]
Hello dear developer! Can you please add the Auto-drop function. For example, if I have a stone in my inventory, this function would automatically throw it away. It would be helpful. This function is available in the Meteor Client mod(open-source). Thanks for attention!

**Comment by blackd** [comment]
Auto dropping stuff sounds like a very good feature.... for a hacked client used for auto-mining.... OH LOOK you posted exactly the same request to  BleachDrinker420/BleachHack#263 

Although such feature may have totally legitimate use the potential for miss use is too big.
