### ISSUE TITLE
Make it possible to lock slots to certain types of items

### ISSUE THREAD

**Issue by TheAyes** [blackd/Inventory-Profiles#180]
I initially thought the slot locking would be able to do this. But either I'm not able to find it or it simply doesn't support it.
Cut short:
Sort of like you have for normal profiles I would like to be able to "assign" a block, tool or item to a locked slot so if that slot happens to be empty it automatically get's put into that slot if I pick up or shift + click from a chest.

**Comment by blackd** [comment]
probably won't happen
and this is not the idea of the locked slots

**Comment by TheAyes** [comment]
I see :o No worries.
However I also noticed while you can disable Shift+Click from locked slots themselves.
Crafting an item (or smelting in furnace) and shift+clicking this item does still put them into locked slots.

**Comment by blackd** [comment]
unfortunately shift click is handled by the server and I can't prevent the server from putting stuff in the locked slots while the inventory is opened.

Short of reimplementing the whole shift click support there is nothing I can do about it

**Comment by TheAyes** [comment]
Alright! Just wanted to let you know :D But it seems you already do!
Greetings~
