### ISSUE TITLE
Profile slot tags with "Any"?

### ISSUE THREAD

**Issue by TheAyes** [blackd/Inventory-Profiles#181]
Kinda hard to explain for me but I would like to assign a slot for "any" block. kind of like
```
profile MyProfile activate HOT1
     HOT1
          "minecraft:block"
```

**Comment by blackd** [comment]
I'll do some research about this.
But minecraft:block even if it exists as an ID will exclude any modded block. 
Might not be soon but I'll probably do something about this.

**Comment by blackd** [comment]
not really possible to be done in non brute force way
