### ISSUE TITLE
Hotbar  Bug on server join

### ISSUE THREAD

**Issue by BaxAndrei** [blackd/Inventory-Profiles#182]
I use the latest version of fabric, minecraft and mod. There are times when I connect to the server and my inventory gets messed up. The most annoying thing is that it moves my sword and pickaxe from the first 2 slots in the hotbar to the first 2 slots in the upper inventory.

**Comment by blackd** [comment]
it's a server caused problem

in the locked slots page of the settings there is a slider about timeout on world/dimensions change increase it until you stop having issues

**Comment by BaxAndrei** [comment]
Thank you, I think the problem was with a plugin (disabled it, problem seems to be solved for the moment) that hide your inventory until the map loads and then shows your inventory and that's probably why the items were messed up.

**Comment by blackd** [comment]
yeap sounds about right
