### ISSUE TITLE
Carry On mod incompatibility

### ISSUE THREAD

**Issue by AlexCastel14** [blackd/Inventory-Profiles#183]
When you try to pick up an entity (villager, zombie, etc) using carry on mod, Inventory profiles tries to put this on the hot bar, causing this entity to disapear and keeping slowness effect.

It is also informed on Carry On github.
[https://github.com/Tschipp/CarryOn/issues/409](https://github.com/Tschipp/CarryOn/issues/409)

Possible solution: Verify if carry on is installed. If it is, deactivate "Pick items directly into the inventory" on Locked Slots options by default.

**Comment by blackd** [comment]
Yeah same problem also exists if the hot bar slots are locked.

and only in multiplayer games.

I'll probably add filter for `carryon:` items
