### ISSUE TITLE
Option "Pick Items Directly Into Inventory" does not respect the global Locked Slots Toggle

### ISSUE THREAD

**Issue by JustAHuman-xD** [blackd/Inventory-Profiles#184]
The Option in Question: "Pick Items Directly Into Inventory" Is under the Locked Slots Section, however when you have locked slots disabled it does not disable that feature. Also (this is just my opinion) but as this is a decently big change it might be worth having the default be disabled and not enabled.

**Comment by blackd** [comment]
Relying on the users to, even find, and then enable new features proved to be very optimistic view about the world.

So a decision was made all new features to be enabled by default.

As for the placement of the option may be it's not very intuitive but it comes from the fact that the the same part of the code that handles it. May be I'll move it out in future releases.
