### ISSUE TITLE
Crash with GUI Scale mod

### ISSUE THREAD

**Issue by SplendidAlakey** [blackd/Inventory-Profiles#185]
**MC** 1.19.2
**IPN** 1.7.0
**[GUI Scale](https://www.curseforge.com/minecraft/mc-mods/tip-the-gui)** 2.1

To reproduce:

1. Open any inventory and click on the "IPN General configuration" button at the top left:

![2022-08-30_12 16 16](https://user-images.githubusercontent.com/86702831/187412839-55f8de32-2b5f-40c3-ab34-bd6f506f901d.png)

2. Crash

GUI Scale is not open source so if the issue can't be resolved, I understand.

Logs: https://gist.github.com/Footage2-Amply-Pounce/b6ca889b40f23f58435236b80ee4482c

**Comment by blackd** [comment]
fabric or forge

**Comment by SplendidAlakey** [comment]
Oh, sorry, Fabric.

**Comment by blackd** [comment]
I would say there are multiple problems with that mod.  Even if I mitigate the reasons for the crash my mod UI is still not displayer property and is not working properly.

**Comment by SplendidAlakey** [comment]
I see. If it's not worth it/possible to resolve these issues, then close this as not planned. I just won't use GUI Scale with IPN for the time being.

Maybe add a warning note on the mod's page to let people know that the global config screen will crash if GUI Scale is installed, but otherwise everything will work fine.

**Comment by blackd** [comment]
The crash it self is already "fixed" however it's the wrong "solution" to a bigger problem. For some reason the UI handling becomes multithreaded when this mod is present which is not really expected.

And there are visual problems depending on what combinations of gui/menu scale I choose.

![изображение](https://user-images.githubusercontent.com/333840/187422522-8bcd95db-9d37-4188-806a-2c017d0c14d9.png)

or this 

![изображение](https://user-images.githubusercontent.com/333840/187422768-d07463fa-d7e7-4ed0-8eea-03a9292bf38d.png)

**Comment by blackd** [comment]
I it's at all possible report the problem to them.
