### ISSUE TITLE
[bug, feedback, suggestion-fabric] locked slots prevent item scrolling from a different mod

### ISSUE THREAD

**Issue by Grumpey102** [blackd/Inventory-Profiles#186]
Hey, I'm using Mouse Wheelie for my item scrolling. For one I have used that for ages, secondly it provides the function to bind mod functions to key + modifier key even in the standard minecraft key config (ctrl+1 for example).

Anyway, since I'm not using your scrolling feature I "turned it off" by deleting all keybinds of that feature. Problem is, that I can't use mouse wheelie to scroll items into a chest from a locked inventory slot. I'm not 100% sure but I think that was possible before the latest inventory profiles update.

If you want to look into this, this is mouse wheelie:
https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie/files/all?filter-game-version=1738749986%3a73407

I'm on quilt, I don't know if this makes a difference.

By the way - I found your way of handling the scrolling a bit unintuitive. When you use the spread function to spread items from the chest into your inventory and then use "leave one" to scroll every item but one back into the inventory, then there will be one _in every slot_ instead of one _in the inventory_ which is what I thought it did. For example to put all the mass crafted pickaxes into a chest but the one you use (which has the cursor on), or to clean your exploration inventory from all arrows but one.

The "scroll the whole stack" is also strange because it seems like the "stack" is always the chest one. Meaning when I have 64 planks in my inventory and in the chest is 1, it will scroll 63 planks to fill the chest stack to 64 instead of "scrolling away" the whole stack your mouse cursor is on.

If you want to know, I find these settings of mouse wheelie to be most intuitive for item scrolling:
![22-08-31 - javaw - 19-34-50](https://user-images.githubusercontent.com/110056966/187743061-a75c2da7-4dba-4e7f-a726-caf10d3a71cb.png)

Oh also: your item scrolling doesn't include the hotbar when you're scrolling into the chest if I remember correctly, I'd personally include the hotbar because it's the place first filled with rubbish (except when you turn on the "put items directly in inventory" option, which is bad when you have a trident that you throw and it comes back into the inventory instead of the hotbar for successive use)

Anyway, great mod nonetheless!
Cheers, Grumpey

**Comment by blackd** [comment]
Hi,

Can you join our discord sever https://discord.gg/23YCxmveUM
I have some questions

also holding alt includes the hotbar this is how all features of IPN work the user has to explicitly request that the hotbar is included.

**Comment by Grumpey102** [comment]
Yup, I just joined, my discord is Grumpey102#1002

> holding alt includes the hotbar this is how all features of IPN work

Ah yes, I remember. For some reason I did not connect the dots that this also counts for scrolling items :)
