### ISSUE TITLE
Please do it easyli more like InventoryTweaks

### ISSUE THREAD

**Issue by FritzHugo3** [blackd/Inventory-Profiles#188]
I have testet this mod but it dont work good. Its so much complicated, some function dont work, please show InventoryTweak at Minecraft 1.12.10, IT FEELS EASY GOOD. 

In this mod i tryed to make "alt" key for Drop items, not working, i have tryed that i can drop all Itemslot from this specifik material (e.g. all cobblestone stacks), dont work.

please copy the usability and keys from InventoryTweaks in youre mod and the people will be so thankfull to you. And forget this with lock mith alt, make a txt list with the rools with numbers for the slots like in InventoryTweaks its so easy and selfexplaining. In youre mod i undersant nothing and tzhe people dont now there are a config, why there are not a button for it in the inventory?

I see the potential for youre mod but its much to complicated, its much to not good to handle and it haves not the functionality what it could have. 

Thank you. And good luck. Have a very nice day.

**Comment by blackd** [comment]
First of all no I'm not going to copy Inventory Tweaks.
Second there is a button to access the settings in the inventory see the screen shot bellow.

**alt**, **ctrl** and **shift** by default have special meaning and modify how other functions behave. 

If you need help using the mod you can always hop in our discord server so we can help. However we don't want to hear complains how this mod is not carbon copy of Inventory Tweaks.

![2022-09-04_20 57 53](https://user-images.githubusercontent.com/333840/188327143-79e067d7-ff79-4472-a29b-0e8cbcd6e14d.png)

**Comment by FritzHugo3** [comment]
Cant find a Discord Link for youre Server, where stand it in github ?

In youre picture this is a different config for what you get when you press R+C - but how people guess this? (And what you get with this button lefutup is overlaped with other stuff like NEI and oder mods. maybe there should be an underground color for beter reading 
![grafik](https://user-images.githubusercontent.com/55752226/188328180-cce62e04-a07f-4957-8d25-983a5f9cd322.png)
(im sure its different for each modpack and versions but for atm7 its so).

But this are the only importen (the right) config or? 
![grafik](https://user-images.githubusercontent.com/55752226/188328278-851e9535-16ec-48ae-9971-8bd2c2914904.png)
And for this i dont find a button. How people knows that they must press R+C (Maybe it could stand as an Text if you load the map or what ever but any that people find it)

**Comment by blackd** [comment]
you have old version of the mod please update to the latest one

the discord link is in the description of this repository 
and on the curseforge page
and on modrinth page 

https://discord.gg/23YCxmveUM
