### ISSUE TITLE
Picked up items do not appear in hotbar

### ISSUE THREAD

**Issue by Frunobulax53** [blackd/Inventory-Profiles#189]
With InventoryProfilesNext-fabric-1.19-1.7.1, items that are picked up will be moved into the inventory instead of the hotbar.
I couldn't find a configuration option corresponding to this, if there is, it needs to be more transparent. In any case that behaviour is very unfortunate.

It still worked fine in the last version I used, which was InventoryProfilesNext-fabric-1.19-1.5.3.

Environment is fabric/carpet 19.2, loads of client side mods, server only runs optimization mods (lithium, starlight).

**Comment by blackd** [comment]
it's in the locked slots page

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/191315117-5a52c6e4-f713-41d7-9522-73ae1b4f94cf.png)
Use this in "Locked slots tab"

**Comment by lynrayy** [comment]
I hate this update with forced new functions

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/191315398-4e0874c4-77cb-4503-b1d0-3f0eb29d857d.png)

**Comment by lynrayy** [comment]
Do not delete this
It might help to others

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/191315586-0c8dce1a-3a09-4e3d-8a20-090cd1128dea.png)
Do not delete this
It might help to others
