### ISSUE TITLE
Expose API for other mods to inform us which of their screens are invontory/sotrage

### ISSUE THREAD

**Issue by blackd** [blackd/Inventory-Profiles#19]
The idea is to allow other mods to provide information if their screens are storage/inventory or not.

Should be something that doesn't introduce hard dependency.

**Comment by blackd** [comment]
See #17

**Comment by elhertz** [comment]
PlayerEx 
![playerex](https://cdn.discordapp.com/attachments/380553391694413825/897609745186308186/unknown.png)

**Comment by blackd** [comment]
released with 1.1.0
