### ISSUE TITLE
Corpse inventory error

### ISSUE THREAD

**Issue by KyrDerz** [blackd/Inventory-Profiles#190]
![image](https://user-images.githubusercontent.com/110685473/189502354-8f254e72-acdc-4fbf-a33c-02ed333d5c44.png)
I do not know which mod it enters in conflict with tbh.

But when I do not have enough inventory on me to receive every item from my corpse, this is the menu it turns into.

**Comment by blackd** [comment]
unfortunately I can't see what is the problem.

can you try to describe it?

**Comment by KyrDerz** [comment]
Oh, sorry.
The original menu is this:
![image](https://user-images.githubusercontent.com/110685473/189503183-cd5bff8d-0673-4a37-914c-d5946e8e5351.png)
Then somehow it transforms into the one I have in the other screen.

Tho it is most likely nothing to do with Inventory Profiles, sorry

**Comment by blackd** [comment]
Well I can assure you Inventory Profiles Next doesn't in any way influence what UI is shown
we just add the sort buttons on top of what is shown
