### ISSUE TITLE
Throw all Crafting Outputs to the world

### ISSUE THREAD

**Issue by Laifsyn** [blackd/Inventory-Profiles#191]
So Let's say you have 6400 charcoal scattered in both your feets and inside your inventory. What would be the most common thing an InventoryProfiles user do with so much charcoal? Convert it into a Charcoal Block(Modded item) of course!

But issue comes when you try to craft it. Because you can't place it inside your inventory because it gets filled with the charcoal dropped at your feet, I thought, how about throwing it all at one simple "Ctrl + Shift + Q"?

**Comment by blackd** [comment]
https://youtu.be/BHEnDOWltsQ
this is the best way to handle such crafting

ctrl+shift+q on the crafting slot is not possible in vanilla minecraft

simulating it by pressing ctrl+q 64 times is as slow as you holding ctrl+q over the slot so IPN doesn't do it

**Comment by blackd** [comment]
Not planned in this form.
But may be there will be a development that will allow for crafting of all resources in pickup distance.
