### ISSUE TITLE
Pick items directly into inventory not working in 1.19.2

### ISSUE THREAD

**Issue by Nevrai** [blackd/Inventory-Profiles#192]
This feature was working as expected in 1.18.2, but in 1.19.2, it is not working. Any items picked up still go into the hotbar rather than directly into the inventory. “Enable picking items into locked slots” is disabled.

### Versions
* **Minecraft:** 1.19.2 (latest)
* **Forge:** 43.1.25 (latest)
* **Inventory Profiles Next:** 1.7.1 (latest)

**Comment by blackd** [comment]
single player or server and are the locked slot enabled?

make sure locked slots are enabled.

**Comment by blackd** [comment]
closing due to lack of information
