### ISSUE TITLE
[Suggestion] Idea to add a new native rule for "empty space"

### ISSUE THREAD

**Issue by zjhendryx** [blackd/Inventory-Profiles#193]
When I'm sorting my inventory manually to add new locked slots, I like to set it up so that my locked slots are at the the end; so that if you were to look at my inventory you would see the sorted items, then any empty slots, and then finally my locked slots in the bottom right of my inventory.

As I play the game, I keep having to change these locked slots however as I stop wishing them filled with certain items and upgrade to using better stuff (normally changes in weapons, food, etc).

It occurred to me today that, if we had a native rule for "empty space" then I could mostly automate this, as then I could then just add a rule "::empty_space" to be before "@name_weapons" and "@food" to sort the way I like.

My idea of how the ::empty_space rule would work, is that if after stacking items there were no empty spaces left, then this rule could just be ignore. However in the event where after stacking items there where say 4 empty slots, then Inventory-Profiles would place those 4 empty slots before the final items to be sorted.

**Comment by blackd** [comment]
From your description I thing you are defining ::empty_space as a empty slot not all empty slots.
but all other rules march all items of type. 
So per your suggestion if there is a ::empty_space rule you will end up with an inventory where the items are split in to groups with  all empty slots in between.


My guess from your description is that you want to end with inventory sorted like this:
![изображение](https://user-images.githubusercontent.com/333840/190677554-19caa843-f1b4-47f7-b8c0-f09db795e73b.png)

However with the way sort works now you will most likely end up with something like this:

![изображение](https://user-images.githubusercontent.com/333840/190677919-88970979-19ab-4b3a-989f-44e17e55e0d6.png)

**Comment by blackd** [comment]
With the above said the current sort implementation doesn't even know empty slots exists. And is so complex that if I ever decide to change something I will probably start from scratch.
