### ISSUE TITLE
Using anvil will sort your inventory

### ISSUE THREAD

**Issue by Aefinn** [blackd/Inventory-Profiles#194]
For some reason when I use the anvil it will always sort items in my inventory. Hot bar stays fine, just the actual inventory gets sorted.

Using this: InventoryProfilesNext-fabric-1.19-1.7.2

But this has happened before this version too. So far have not noticed it happening with any other work benches.

**Comment by blackd** [comment]
the default keybind for sorting is r I guess you type a name with r.

**Comment by Aefinn** [comment]
Doesn't that seem like an oversight? Regardles what keybind is used since the main feature of anvil is to write, not to arrange your inventory.

But good to know :) I'll definitely change the keybind!

**Comment by blackd** [comment]
you are welcome to submit a patch that detects if the player is typing into the name field so ipn can ignore it.
