### ISSUE TITLE
I don't know how to disable auto move function

### ISSUE THREAD

**Issue by lynrayy** [blackd/Inventory-Profiles#195]
I don't know how to disable auto move picked up items inside inventory instead of hotbar slots. Why did you even turn it on by default?

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/191291797-b8ccce64-dce6-4dfa-9928-f0427a0b4182.png)

**Comment by blackd** [comment]
Read the comments on the mod page
ask on our subreddit
ask on discord

don't use the issue tracker for support

**Comment by lynrayy** [comment]
Then please add obvious settings in mod
