### ISSUE TITLE
Настрой свой мод

### ISSUE THREAD

**Issue by lynrayy** [blackd/Inventory-Profiles#196]
Ёбаное чмо, лучше настрой свой мод, а не удаляй ответы с помощью людям, которые не могут найти твою ебаную настройку, которую ты поместил не в тот раздел, да ещё и включил по умолчанию. Ты хуже чем разработчики VK.com, они хотя бы настройки пихают куда надо.

Никто не просил добавлять автоматическое перекладывание предметов из хотбара в инвентарь. Так оставь хотя бы подсказку как это выключить, а не удаляй комментарии. Чмошник ебаный

**Comment by blackd** [comment]
thank you for this message now I can report it

**Comment by lynrayy** [comment]
Don't care. Didn't ask. Now fix your mod
