### ISSUE TITLE
Caused by carpet enabled "stackableShulkerBoxes" would result in a java.lang.IllegalStateException: Infinity loop detected. 100001 > 10000

### ISSUE THREAD

**Issue by tianxiu2b2t** [blackd/Inventory-Profiles#199]
Because I stackable shulker boxes, it will lead to unable to organize inventory.

**Comment by tianxiu2b2t** [comment]
![image](https://user-images.githubusercontent.com/95091178/192290301-5b232356-5044-4188-854f-af65a3eb76c7.png)

**Comment by tianxiu2b2t** [comment]
"作者": Auther or by mean

**Comment by tianxiu2b2t** [comment]
![image](https://user-images.githubusercontent.com/95091178/192290507-db38ed90-48da-434d-adec-2a5b49be874b.png)

**Comment by tianxiu2b2t** [comment]
![image](https://user-images.githubusercontent.com/95091178/192290575-e0199565-5750-4f82-b964-92fb736a6a22.png)
![image](https://user-images.githubusercontent.com/95091178/192290591-647e8db9-58b8-4468-8580-5093c7dccd60.png)

**Comment by tianxiu2b2t** [comment]
![image](https://user-images.githubusercontent.com/95091178/192293292-23c43226-3c48-44dc-81ad-795ead5cd2a6.png)

**Comment by tianxiu2b2t** [comment]
emmm

**Comment by tianxiu2b2t** [comment]
Only two shulker boxes and item or more items

**Comment by tianxiu2b2t** [comment]
For raw electricity players, sometimes open the latent shadow box stacking to ensure that the item bar space will not take up a lot of.

**Comment by blackd** [comment]
by default shulkers don't stack. so this is not supported.

also please stop spamming comments! I would appreciate it!

**Comment by tianxiu2b2t** [comment]
For raw electricity players, sometimes open the latent shadow box stacking to ensure that the item bar space will not take up a lot of.

**Comment by tianxiu2b2t** [comment]
For raw electricity players, sometimes open the latent shadow box stacking to ensure that the item bar space will not take up a lot of.

**Comment by blackd** [comment]
No it's not a bug!

**Comment by blackd** [comment]
the best thing I can do is just leave the oversized stacks where they were
