### ISSUE TITLE
Improve the page on curseforge.com

### ISSUE THREAD

**Issue by blackd** [blackd/Inventory-Profiles#20]
The page on curseforge needs some love and tbh, but I personally can't be bothered/think of anything better to put there.

So... HELP WANTED.

**Comment by Tygoar** [comment]
What is it you want doing to the curseforge page exactly?

**Comment by blackd** [comment]
Add 
- description
- screenshots
- better contacts issue reporting section 
- thanks to the original author

stuff like that

**Comment by marie-bnl** [comment]
How can we do it? Where to edit it? What format is it? HTML? MarkDown?

**Comment by blackd** [comment]
It's html here is the source https://gist.github.com/blackd/60c5cc3d5790554b164201c9bce11001

**Comment by marie-bnl** [comment]
Is it allowed on Curseforge to put the style apart in a `<style>`?

**Comment by blackd** [comment]
Nope, it gets removed.

**Comment by marie-bnl** [comment]
Okay thanks, maybe I'll try to do something

**Comment by marie-bnl** [comment]
What do you think of that?

https://gist.github.com/victorbnl/2215168582439b7a31b4b6697fd45623

I'll convert it to HTML and add some style later

Of course, the image is a placeholder one, I'll also make a cool picture representing the before/after of the sorting

EDIT : In the gist there are now both the source markdown and the html, if you want to view the HTML file, click on "Raw", do CTRL+S and open the downloaded file in your browser

**Comment by victorbnl** [comment]
I wanted to create a test project on CurseForge to preview my work but I can't, it doesn't take my HTML and just displays the code. The only two options of the description editor are WYSIWYG and Markdown and both don't work

**Comment by victorbnl** [comment]
In the gist I gave above there are now both the source markdown and the html, if you want to view the HTML file, click on "Raw", do CTRL+S and open the downloaded file in your browser

**Comment by marie-bnl** [comment]
And to explain a bit how this all works, I made a little bit of code, I have these files :

- source.md
- style.css
- build.py

As you may have guessed, you build the document using build.py

The source.md is converted to HTML by _pandoc_ (actually _pypandoc_, which is a python wrapper for pandoc)

And the style.css is put in the HTML as inline attributes by _premailer_

Also source.md uses no special syntax or anything, only Markdown and HTML, so you can use it wherever you want, for example Github. Of course you could loose the centered things and the colors but it won't break anything

**Comment by marie-bnl** [comment]
When you'll think it will be finished I'll send you a .zip with all these files, so that you can make a new repo or branch if you want, or just in case you want to edit some things

**Comment by blackd** [comment]
You know what why don't you clone this repository add /description folder and put the sources and the build script there and make a pull request

**Comment by marie-bnl** [comment]
No problem I'll do that, good idea!

**Comment by marie-bnl** [comment]
So as you may have seen I made the PR!

**Comment by blackd** [comment]
I guess bb36707 is the best we can do :) given curseforge limitations

**Comment by marie-bnl** [comment]
Yep, it's already much better!
