### ISSUE TITLE
Compatibility with stackableShulkerBoxes from Carpet

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#200]
The [Carpet mod](https://github.com/gnembon/fabric-carpet) has a feature to stack empty shulker boxes (up to 64) named [stackableShulkerBoxes](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings#stackableshulkerboxes) which causes an error on InventoryProfilesNext when attempting to sort an inventory that contains stackable shulkers.

With Minecraft 1.19.2 and InventoryProfilesNext-fabric-1.19-1.7.2, it gives the error `java.lang.IllegalArgumentException: Illegal Capacity: -49` in any condition, where -49 is an example for 60 shulkers, this value varies according to the stack size.

With Minecraft 1.19 (1.19.0) and InventoryProfilesNext-fabric-1.19-1.6.0 and Minecraft 1.18.2 and InventoryProfilesNext-fabric-1.18.2-1.6.0, it doesn't give any error if the inventory sorting operation doesn't need to move the shulker stack. If it needs/try to move the shulker stack, it gives the error `java.lang.IllegalArgumentException: Area is not retangular!`.

I am aware of the difficulty or impossibility to sort the illegal stacks, but the behavior of InventoryProfileNext 1.6.0 worked fine enough. Could you implement it for 1.7.0 and future versions?
The most optimal solution (disregarding the ability to sort the illegal stacks) would be to complete ignore or skip the slots that contains these type of stacks automatically in any operation of inventory sorting.

**Comment by blackd** [comment]
the workaround works ance again works in 1.8.0 now oversized stacks of size  <=64 are moved at the back of the inventory and oversized stacks with more than 64 are left in place 
however due to the nature of these oversized stacks braking again in future is possible

**Comment by tianxiu2b2t** [comment]
Game: Minecraft 1.16.5
