### ISSUE TITLE
1.18.2 Adding Mixin Bootstrap as dependency has broken everything.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [blackd/Inventory-Profiles#201]
https://gist.github.com/P3rf3ctXZer0/0fb094b06f2868a19b255915b054a319

I blamed libIPN but it actually was mixin bootstrap

- MixinBootstrap has a history of issues going all the way back to 1.12.2 consider using something else.

**Comment by blackd** [comment]
MixinBootstrap should be added as dependency only for 1.14.

**Comment by P3rf3ctXZer0** [comment]
Strange it is adding in on 1.18.2 was that not intended? Seems curse missed the memo.

**Comment by P3rf3ctXZer0** [comment]
![RCuaKgg 1](https://user-images.githubusercontent.com/10351221/192428165-74aa12aa-0ac4-48e2-b8e5-5a30f51442d3.png)
![G4tQ9xM 1](https://user-images.githubusercontent.com/10351221/192428237-8da75e72-78e2-42c8-bf75-a2d4b3527393.png)
![86ltCIM 1](https://user-images.githubusercontent.com/10351221/192428272-664cf4a5-a9b8-4ba3-ae75-372568eb298c.png)
![gq4mgSy 1](https://user-images.githubusercontent.com/10351221/192428307-f67504f5-b679-46c0-b1f9-dd09f3133196.png)
![grjNmoZ 1](https://user-images.githubusercontent.com/10351221/192428356-e7e547a2-594b-491b-aa29-9697093935ee.png)

Events in order of pictures.

**Comment by blackd** [comment]
all forge builds had it as dependency for some reason 

i've removed it

**Comment by P3rf3ctXZer0** [comment]
Glad I could help only caused me a 3 hour headache XD

**Comment by P3rf3ctXZer0** [comment]
Unfortunately it is still happening. I updated my 1.19.2 pack and it grabbed mixinsbootstrap again. I will close this as soon as I am able to update mods without suddenly gettinga  sus mod ;)

**Comment by blackd** [comment]
major changes usually bring unforeseen consequences and annoyingly I can test the dependency resolving before I releasing it

**Comment by blackd** [comment]
> Unfortunately it is still happening. I updated my 1.19.2 pack and it grabbed mixinsbootstrap again. I will close this as soon as I am able to update mods without suddenly gettinga sus mod ;)

May be it has become part of the pack as far as I know mod packs are fully resolved and the curseforge won't try to resolve individual mods from a pack

**Comment by P3rf3ctXZer0** [comment]
> > Unfortunately it is still happening. I updated my 1.19.2 pack and it grabbed mixinsbootstrap again. I will close this as soon as I am able to update mods without suddenly gettinga sus mod ;)
> 
> May be it has become part of the pack as far as I know mod packs are fully resolved and the curseforge won't try to resolve individual mods from a pack

Its not a modpack.
Its a modpack I am creating IE it is not on curse technically its just a group of files.

Here for your clarity I made this 
![YG10p8i 1](https://user-images.githubusercontent.com/10351221/192430949-336d3a77-7685-4eb3-bdd5-eaec58a62f92.png)

**Comment by blackd** [comment]
then the curseforge app just have cached the dependencies.

**Comment by P3rf3ctXZer0** [comment]
> then the curseforge app just have cached the dependencies.

if they have you should make a note on the front page. Otherwise more people will have the same issue.

**Comment by blackd** [comment]
ATLauncher doesn't show it

![изображение](https://user-images.githubusercontent.com/333840/192431138-c0a49f2f-1072-4206-8cfa-f44a24710112.png)

**Comment by P3rf3ctXZer0** [comment]
I know - also I know curseforge is a nightmare to use (So glad they have a monopoly now) I am just helping you realize 
- users will have this issue when using curseforge
- it is not directly your fault
- simply noting it on your frontpage ``Warning to new users some users are getting mixin bootstrap when using version beyond 1.7.2 so if this happens to you simply delete it.`` will help mitigate some issues.

**Comment by blackd** [comment]
my guess is the cache is local and will expire at some point

noone reads the description or the release notes...... judging by the number of questions I get that that have been answered in the description/release notes

🤣
