### ISSUE TITLE
Feature request: Inventory profiles INV# inventory slot definition 

### ISSUE THREAD

**Issue by Thanos1716** [blackd/Inventory-Profiles#204]
I would like to request a feature that allows you to configure the inventory slots with the profile files as well as the hotbar slots, so for example:
```
profile Combat activate HOT1
	HOT1
		"minecraft:netherite_sword"
	HOT2 
		"minecraft:bow"
	INV1
		"minecraft:netherite_pickaxe"
	INV2
		"minecraft:elytra"
```
Where INV1 would describe the upper left most inventory slot and INV2 would be the one next to it and so on all the way up to INV27 at the bottom right.
This would really enhance the usefulness of this mod in my opinion.
Also great work :D

**Comment by blackd** [comment]
at the moment there is no plan of this being supported. there are some technical reasons that make it impractical to implement.

however a very close approximation of this can be achieved with locked slots and the current profiles

**Comment by Thanos1716** [comment]
that is a

**Comment by Thanos1716** [comment]
that makes sense, thought it was worth a try
