### ISSUE TITLE
[Suggestion] Config option for treating shulker boxes as stackables

### ISSUE THREAD

**Issue by kikugie** [blackd/Inventory-Profiles#205]
Carpet mod and essential client allow stacking shulker boxes inside inventories by a player. In order to not break default behavior I think stacking boxes should be a setting in the mod.

**Comment by blackd** [comment]
this can only be done server side
this mod is client side only

and oversized stacks are "supposed" to a degree and are either left untouched ore moved at the end if possible

**Comment by kikugie** [comment]
https://modrinth.com/mod/essentialclient
![2022-09-30_20 54 12](https://user-images.githubusercontent.com/50152507/193338017-edf5574e-9a1e-41f7-a8ee-6f76256abcee.png)
It allows stacking shulkers in player inventory if carpet rule is enabled on the server

**Comment by kikugie** [comment]
So with proposed option enabled when sorting inventory mod will attempt to stack shulker box items. On most servers it won't work so its supposed to be disabled by default
@blackd

**Comment by blackd** [comment]
unfortunately the whole point of this mod is to not require any server side component or non vanilla communication

so this will not be added
