### ISSUE TITLE
(bug?) Durability in fising (and sword)

### ISSUE THREAD

**Issue by futag** [blackd/Inventory-Profiles#207]
https://user-images.githubusercontent.com/21020026/193424259-be673e6a-bf7d-44ee-ad12-2516b6463797.mp4

Sometime fishing rod reduce 10 durability, sometime sword durability half left and unbreaking 3 not work. but after disable Inventory Profile next, durability system back to normal

**Comment by blackd** [comment]
the durability is controlled by the server. so whatever value you seen is sent by the server. 
IPN reads the durability value to replace the tool before it breaks.
