### ISSUE TITLE
strange IPN Warning message

### ISSUE THREAD

**Issue by Maia-Saku** [blackd/Inventory-Profiles#209]
Hello! After updating, some tools will at random produce a warning- like a hoe when harvesting or a shovel when making a path- with a little noise alert. 
"IPN Warning - Stone Hoe Replace Failed"

It will happen as tools get into the red of durability, as far as I have observed. 
![image](https://user-images.githubusercontent.com/114946621/193644036-78d1b408-7dc4-43f7-bf75-f9bac75a6daf.png)

**Comment by blackd** [comment]
this is the intended behaviour
you can cotroll it from the settings `auto refill` page

to open the settings use r+c in game or the mods button
