### ISSUE TITLE
Traveling through portals may cause locked slots to be cleared

### ISSUE THREAD

**Issue by 0xf0xx0** [blackd/Inventory-Profiles#210]
**Issue**
Sometimes when traveling through portals, locked slots are cleared and moved into unlocked slots. If you have no clear unlocked slots (returning from a mining expedition for example), the items will instead end up being thrown in a small radius around you, potentially resulting in item loss.  
I can't seem to consistently reproduce this. Sometimes it fixes itself, other times a quick toggle of the locked state fixes it. I almost exclusively play on servers, but a quick singleplayer test didn't cause the issue to crop up.

**Version**
IPN v1.8.1 (managed with [Minecraft Mod Updater](https://github.com/jonafanho/Minecraft-Mod-Updater))
Minecraft v1.19.2

**Full Modlist**
<details>

[Advanced XRay (Fabric Edition)](https://curseforge.com/minecraft/mc-mods/Advanced-XRay-Fabric-Edition)  
[Alternate Current](https://modrinth.com/mod/r0v8vy1s)  
[Animatica](https://modrinth.com/mod/PRN43VSY)  
[AppleSkin](https://modrinth.com/mod/EsAfCjCV)  
[Better Biome Blend](https://modrinth.com/mod/Rs6c7WyL)  
[Better End Sky](https://modrinth.com/mod/SgJ1iW80)  
[BetterF3](https://modrinth.com/mod/8shC1gFX)  
[CIT Resewn](https://modrinth.com/mod/otVJckYQ)  
[Chime](https://modrinth.com/mod/ubxU84eR)  
[Clear Skies](https://modrinth.com/mod/xNK6XfRv)  
[ClickThrough](https://modrinth.com/mod/Z5b0cAlD)  
[Cloth Config API](https://modrinth.com/mod/9s6osm5g)  
[Concurrent Chunk Management Engine (Fabric)](https://modrinth.com/mod/VSNURh3q)  
[Continuity](https://modrinth.com/mod/1IjD5062)  
[Cull Leaves](https://modrinth.com/mod/GNxdLCoP)  
[Custom Entity Models](https://modrinth.com/mod/YOQCucah)  
[DashLoader](https://modrinth.com/mod/ZfQ3kTvR)  
[Don't Drop It!](https://modrinth.com/mod/HcVOCzMh)  
[Dynamic FPS](https://modrinth.com/mod/LQ3K71Q1)  
[EntityCulling](https://modrinth.com/mod/NNAgCjsB)  
[Extended Clouds](https://modrinth.com/mod/SRvY3a39)  
[FPS - Display](https://modrinth.com/mod/DIlqwRFH)  
[Fabric API](https://modrinth.com/mod/P7dR8mSH)  
[Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL)  
[Fastload](https://modrinth.com/mod/kCpssoSb)  
[FerriteCore](https://modrinth.com/mod/uXXizFIs)  
[ForgetMeChunk](https://modrinth.com/mod/vRXn3MrA)  
[Fullbright 1.19](https://modrinth.com/mod/VyxkIxCd)  
[Idwtialsimmoedm](https://modrinth.com/mod/ad89WlWh)  
[Indium](https://modrinth.com/mod/Orvt0mRa)  
[Inventory Profiles Next](https://modrinth.com/mod/O7RBXm3n)  
[Iris Shaders](https://modrinth.com/mod/YL57xq9U)  
[LazyDFU](https://modrinth.com/mod/hvFnDODi)  
[Lithium](https://modrinth.com/mod/gvQqBUqZ)  
[Logical Zoom](https://modrinth.com/mod/8bOImuGU)  
[Make Bubbles Pop](https://modrinth.com/mod/gPCdW0Wr)  
[Model Gap Fix](https://modrinth.com/mod/QdG47OkI)  
[Mouse Wheelie](https://modrinth.com/mod/u5Ic2U1u)  
[No Chat Reports](https://modrinth.com/mod/qQyHxfxd)  
[No More Purple](https://modrinth.com/mod/32J251wv)  
[Phosphor](https://modrinth.com/mod/hEOCdOgW)  
[Presence Footsteps](https://modrinth.com/mod/rcTfTZr3)  
[Raised](https://modrinth.com/mod/nCQRBEiR)  
[Reese's Sodium Options](https://modrinth.com/mod/Bh37bMuy)  
[Show Me Your Skin!](https://modrinth.com/mod/bD7YqcA3)  
[Skip Transitions](https://modrinth.com/mod/Zoz5HQjH)  
[Smooth Boot (Fabric)](https://modrinth.com/mod/FWumhS4T)  
[Sodium Extra](https://modrinth.com/mod/PtjYWJkn)  
[Sodium](https://modrinth.com/mod/AANobbMI)  
[Symbol Chat](https://modrinth.com/mod/NKvLVQMc)  
[Telepistons](https://modrinth.com/mod/23PBx0DP)  
[Xaero's Minimap](https://curseforge.com/minecraft/mc-mods/Xaeros-Minimap)  
[Xaero's World Map](https://curseforge.com/minecraft/mc-mods/Xaeros-World-Map)  
[microDurability](https://modrinth.com/mod/JW3bGnLO)  
[multiconnect](https://modrinth.com/mod/sfEDKnlo)  

</details>

**Comment by blackd** [comment]
![unknown-3.png](https://user-images.githubusercontent.com/333840/193905881-66a2e4f7-6881-43c1-9cf1-5832d29c8f5a.png)

increase this value until the problem disappears
don't just put it on max 😉

**Comment by 0xf0xx0** [comment]
That seems to have fixed it, and in hindsight feels very obvious xd  
Thanks!
