### ISSUE TITLE
Switching Dimension sorting Bug

### ISSUE THREAD

**Issue by Schamlumpen** [blackd/Inventory-Profiles#212]
Hey, I'm playing with a few friends on a server with this mod and we run into an issue where the sorted inventory gets completely thrown over when switching dimensions. (Judging after the sound it feels like he drops the whole inventory and just instantly picks everything up again making the items completely random sorted in your inventory)
It happens inconsistently but more often than not. When you have a full Inventory and a bunch of locked slots he will throw the items on the floor and isn't able to pick them up again which is also pretty annoying. 
Any change in fixing this bug?

https://user-images.githubusercontent.com/115220193/194528004-98b2e355-0796-4100-80ac-8712ed7d9fb7.mp4

**Comment by blackd** [comment]
duplicate #210

**Comment by blackd** [comment]
https://github.com/blackd/Inventory-Profiles/issues/210#issuecomment-1267468553
