### ISSUE TITLE
AutoCraft BUG

### ISSUE THREAD

**Issue by Alt0x022** [blackd/Inventory-Profiles#214]
On the version of Minecraft 1.16.5 fabric, if you turn off autocraft, minecraft instantly crashes and you can only restart Minecraft if you delete the settings file or the mod itself.

**Comment by blackd** [comment]
which mod version and which libipn version

**Comment by Alt0x022** [comment]
InventoryProfilesNext-fabric-1.16-1.8.1 
libIPN-fabric-1.16-1.0.0

**Comment by Alt0x022** [comment]
now it stopped working even if you delete the settings file, it will work again only when you delete the mod or change the mod settings in another version of minecraft.

**Comment by blackd** [comment]
I really doubt that even with deleted mod the crash is somehow related to it

**Comment by blackd** [comment]
if you can send the logs it will be very helpful

**Comment by Alt0x022** [comment]
[latest.log](https://github.com/blackd/Inventory-Profiles/files/9739217/latest.log)

**Comment by blackd** [comment]
install the latest version of Fabtic Language Kotlin

**Comment by Alt0x022** [comment]
I use google translate because i don't speak english.  I meant that Minecraft only starts if you remove the mod or change the mod settings.  It started after turning off autocraft.

**Comment by Alt0x022** [comment]
ок

**Comment by Alt0x022** [comment]
Thanks

**Comment by blackd** [comment]
I assume [this](https://github.com/blackd/Inventory-Profiles/issues/214#issuecomment-1272310449) fixed your problem?

Reopen if not
