### ISSUE TITLE
"inventory must not be null" when trying to sort any inventory with Scout installed

### ISSUE THREAD

**Issue by SplendidAlakey** [blackd/Inventory-Profiles#215]
**MC** 1.19.2
**FAPI** 0.62.0
**IPN** 1.8.1
**[Scout](https://modrinth.com/mod/scout)** 1.1.1

To reproduce just open any inventory and try to sort it by either clicking R or the sorting buttons. It won't sort anything and produce an error in chat and in the logs. Sometimes the game will also crash, but I don't know how to reproduce the crash. I believe the issue started happening after updating from a non libIPN version to a libIPN one.

Logs: https://gist.github.com/SplendidAlakey/d6e23c551306aae09d18c7fb3fe56846 (latest.log was produced with just Scout and IPN; crash log was produced in a large modpack, because I don't know how else to reproduce it).

**Comment by blackd** [comment]
I can't do anything about this report it to Scout.
The problem is that the vanilla way to get the inventory returns null which is not expected.
