### ISSUE TITLE
Fishing rod not getting replaced

### ISSUE THREAD

**Issue by danielwerg** [blackd/Inventory-Profiles#216]
https://user-images.githubusercontent.com/35052399/194937778-addaac6b-ca3b-4296-8283-2c2be55597fb.mp4

`inventoryprofilesnext.json`:
```json
{
    "ModSettings": {
        "first_run": false
    },
    "GuiSettings": {
        "continuous_crafting_checkbox_value": "UNCHECKED",
        "continuous_crafting_saved_value": false
    },
    "AutoRefillSettings": {
        "allow_break_for_non_enchanted": {
            "value": true
        }
    }
}
```

**Comment by blackd** [comment]
looks like your fishing rod is not enchanted
and you have set `allow break of non enchanted` to true

**Comment by danielwerg** [comment]
> looks like your fishing rod is not enchanted and you have set `allow break of non enchanted` to true

Yeah I want them to break but it doesn't replace hotbar slot with new fishing rod but it does for wooden axes.

**Comment by blackd** [comment]
looks like fishing rods are not supported at all
