### ISSUE TITLE
Failure message: Mod File libIPN-forge-1.19-1.0.1.jar needs language provider kotlinforforge:3 or above to load

### ISSUE THREAD

**Issue by DevSnx** [blackd/Inventory-Profiles#217]
I have a problem now

I have installed Forge 1.19

-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Mod File libIPN-forge-1.19-1.0.1.jar needs language provider kotlinforforge:3 or above to load
		We have found none
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by blackd** [comment]
you need to install [Kotlin For Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/3925887)

**Comment by DevSnx** [comment]
i have installed but, minecraft dont start then, wich version must installed?

**Comment by blackd** [comment]
the one from the link

**Comment by DevSnx** [comment]
its dont work, my Minecraft dont start with this mod Kotlin For Forge

This is my Modlist:
InventoryProfilesNext-forge-1.19-1.8.0
jei-1.19.2-forge-11.3.0.262
journeymap-1.19-5.8.5-forge
libIPN-forge-1.19-1.0.1
OptiFine_1.19_HD_U_H9
StorageDrawers-1.19-11.1.2
Terra-forge-6.2.0-BETA+7d056bd88

**Comment by blackd** [comment]
can you post the whole log file

**Comment by DevSnx** [comment]
[crash-2022-10-14_13.21.31-fml.txt](https://github.com/blackd/Inventory-Profiles/files/9786204/crash-2022-10-14_13.21.31-fml.txt)

**Comment by blackd** [comment]
where did you install kotlin for forge

also do you really  need to use 1.19 and if not can you update to 1.19.2

**Comment by DevSnx** [comment]
Yes

![image](https://user-images.githubusercontent.com/59105899/195885885-877195d7-358a-46ca-9c41-7e18eae2f016.png)

**Comment by blackd** [comment]
OK can you remove both IPN and libIPN

and check if it will start

**Comment by DevSnx** [comment]
Okay its works, but i dont can use other mods without this
![image](https://user-images.githubusercontent.com/59105899/195888587-c6d0220c-81f1-40b5-a026-d426eeb650dd.png)

shit...

**Comment by blackd** [comment]
May be the other mods caused the problem

**Comment by DevSnx** [comment]
hm i dont know that

[latest.log](https://github.com/blackd/Inventory-Profiles/files/9787991/latest.log)

**Comment by blackd** [comment]
can you pleas always send the whole log file

**Comment by DevSnx** [comment]
thats all logs..

[latest.log](https://github.com/blackd/Inventory-Profiles/files/9788034/latest.log)
[debug.log](https://github.com/blackd/Inventory-Profiles/files/9788035/debug.log)

**Comment by blackd** [comment]
look when I said send me a screenshot of your mods folder I meant ALL mods not just what you feel is appropriate.

**Comment by DevSnx** [comment]
thats all mods ^^

I have found the problem but thanks for any helps :)

The Mod: Terra-forge-6.2.0-BETA+7d056bd88 is the problem

**Comment by blackd** [comment]
you also have:
OptiFine
JEI
StorageDrawers

none of the screenshots show them

**Comment by DevSnx** [comment]
I have this mods now and its work fine
![image](https://user-images.githubusercontent.com/59105899/195892319-ec283790-fe82-4f3f-a6a6-3d585d765cb7.png)
