### ISSUE TITLE
Items in QuickAccess up in inventory

### ISSUE THREAD

**Issue by SnrSterling** [blackd/Inventory-Profiles#221]
Why, after entering the server, all things from quick access end up in the inventory? How can this be turned off?

**Comment by blackd** [comment]
![unknown-14.png](https://user-images.githubusercontent.com/333840/196283655-d61ff88a-2fb8-4cc5-be43-f6d1e8d37771.png)


gradually increase this setting until it stops happening

**Comment by SnrSterling** [comment]
Can't it be completely turned off? there is no such function?

**Comment by blackd** [comment]
you can always uninstall the mod

**Comment by SnrSterling** [comment]
No, the mod is great, I just don't understand the meaning of this function. Why is she needed

**Comment by blackd** [comment]
as you can imagine I've put that setting in because it's needed

The problem is the server is not behaving as expected and breaking the mod. So the setting is there in case of bad server behaviour to make the mod compatible.

**Comment by SnrSterling** [comment]
I understand. Thanks a lot for your help. Prosperity modification.
