### ISSUE TITLE
[1.16.5 FABRIC] Empty Travelers Backpacks behave differently during sort. 

### ISSUE THREAD

**Issue by quentin452** [blackd/Inventory-Profiles#222]
Problem : 

When click on inventory sorting key with travelers backpack withtout nbt i have bug

Instruction : 

1 : Give traveler backpack with roughly enough items
2 : Open chest
3 : Click on inventory sorting key(for me ²)
4 : see the problem

Mods list : 

architectury-1.32.66
cloth-api-1.6.59
cloth-config-4.16.91-fabric
fabric-api-0.42.0+1.16
fabric-language-kotlin-1.8.5+kotlin.1.7.20
InventoryProfilesNext-fabric-1.16-1.8.2
libIPN-fabric-1.16-1.0.3
Library-Of-Exile-1.16.5-1.0.15
RoughlyEnoughItems-5.12.385
travelers-backpack-1.16.5-5.4.12

logs : 

https://paste.ee/p/0OTbn

Videos : 

Backpack with NBT(no bug).mkv

https://mega.nz/file/y4dBzTzb#VvsolEELcN-o-9-LFSbmMHC0ZXFrasRLbPw65X5NG6U

Backpack without NBT(bug).mkv

https://mega.nz/file/f5UEyIBK#VWw5g5-wTWiQAeL_kCtMtUxWKvqY4UqaPhG2b6pZSrM

**Comment by blackd** [comment]
I can't understand what the problem is. From what I see in the video may be sorting doesn't work in the second case? Can you be more specific 

What are "Backpack without NBT" and "Backpack with NBT"

**Comment by quentin452** [comment]
with nbt : with items in the backpack
without nbt : without items in the backpack

**Comment by quentin452** [comment]
I don't know why, but when the backpack has no NBT, it doesn't want to be sorted

**Comment by blackd** [comment]
So I tested it and for some reason mouse clicks for that item are not processed the same way as for other items.

Since its just this item and a special version of it I would report this to Travellers Backpack authors.

**Comment by quentin452** [comment]
ok
