### ISSUE TITLE
Game crashes on start-up

### ISSUE THREAD

**Issue by kireinatori** [blackd/Inventory-Profiles#224]
My game crashes immediately on start-up. I narrowed it down to Kotlin for Forge. Disabling Kotlin for Forge lets the game boot normally, aside from not booting because of the mods that require Kotlin for Forge. But InventoryProfilesNext needs this mod. Then you cannot use InventoryProfilesNext.

No crash report is generated, and I couldn’t find anything relevant in the log.

**Versions**
- Minecraft: 1.19.2
- Forge: 43.1.33
- Kotlin for Forge: 3.7.1

**Comment by blackd** [comment]
have you installed all the dependencies
kotlin for forge and libIPN
