### ISSUE TITLE
[1.18.2] [Forge][MacOS] Inventory cannot lock, move item to chest got random problem

### ISSUE THREAD

**Issue by hinls1007** [blackd/Inventory-Profiles#227]
Hi,

I found that if Minecraft run in windows mod with Forge mod-loader will cause the issue of inventory slot are not correct.
This will causing the inventory slot cannot lock.

Also, when moving items to chest with shift+ click or move all feature of this mod, there will random problem that the items inside the chest will move to user inventory. Most appear in the item in column 1 , row 3 or row 4.

These issue appear when the game run in windows mode, full screen mod seems didn't have problem

**Comment by blackd** [comment]
probably the same as #150

**Comment by blackd** [comment]
FIXED in v1.9.2
