### ISSUE TITLE
Newest update crashing inventory 

### ISSUE THREAD

**Issue by Zelioth** [blackd/Inventory-Profiles#229]
MC 1.19.2
Forge 43.1.52
IPN - 1.8.4

in creative mode on my public server. middle mouse wheel clicked to get block to inventory and crashed to this 
https://crashy.net/e5TxdsRQ1JtrsikKVmJN
https://crashy.net/e5TxdsRQ1JtrsikKVmJN?raw

**Comment by BrekiTomasson** [comment]
Same issue here, running on the Fabric v1.18.2 version of the mod. "Parameter specified as non-null is null" on `LockedSlotKeeper.isIgnored`

**Comment by blackd** [comment]
So far I can't reproduce this.

can you provide exact steps

**Comment by Zelioth** [comment]
> So far I can't reproduce this.
> 
> can you provide exact steps

The only way that I had it happen to me was I logged into my public server, Had a gold Iron furnace and middle mouse clicked it in creative. This happened right at login like there was little time between logging in and pressing middle mouse wheel in creative to receive the block in my inventory 

does that make sense?

**Comment by blackd** [comment]
being on a server is even stranger.. because this part of the code  is only relevant in single player

**Comment by Zelioth** [comment]
Ha, welllllllllllllllllllllllllllllllll that crashy report should say server as well but yeah it was one of my public servers for my custom mod pack "Friends United" published on forge. It hasn't happened since so I'm unsure how I even caused it.

**Comment by blackd** [comment]
IPN is client side only just remove it from the server

**Comment by Zelioth** [comment]
So it is disabled on the server. I use a group of mods on 1.19.2 called Adaptive Performance and for servers it goes through and turns off mods that are client side and IPN is set to disabled so it's only on the client.

**Comment by blackd** [comment]
@BrekiTomasson  Are you getting this on a server as well?

**Comment by BrekiTomasson** [comment]
> @BrekiTomasson  Are you getting this on a server as well?

Yeah. Works fine when client-only.

**Comment by P3rf3ctXZer0** [comment]
Mine is on forge but it is the same crash. I broke an item and then this crash happened. Some basic differences is this was in a SP world but the actually crash says server thread. Crash log says it has to do with profile lock manager lock

crash-2022-11-11_11.18.33-server
Crash Report https://gist.github.com/P3rf3ctXZer0/af1ebf17df30c6206ca39b4cc53e882e

Forge 43.1.52
Inventory Profiles Next InventoryProfilesNext-forge-1.19-1.8.4
LibIPN libIPN-forge-1.19-1.0.5

**Comment by blackd** [comment]
I'll probably release an update latter today
