### ISSUE TITLE
New feature: Autosort

### ISSUE THREAD

**Issue by OoLunar** [blackd/Inventory-Profiles#23]
Autosorts on item pickup, inventory open or inventory close. Same goes to chests :smile:

**Comment by blackd** [comment]
If you use the default (right mouse button) settings for use/place adding this breaks:
- stack splitting - right click on a stack to take half
- putting down single item of a currently picked stack 

And on top of that I'm sure even if you want to have everything sorted in 99.99% if the cases. The 0,01% when something gets sorted but you don't really want it to, will infuriate you enough to just disable it.

**Comment by blackd** [comment]
With that said if you join discord and ask I'll give you a version that does auto sort but breaks the above if you want to play with it

**Comment by OoLunar** [comment]
Just realized that I wrote out a response, but never posted it. Good job me.

I'm a bit confused here, and I think we have different ideas of "autosort." I'm proposing to sort inventory when it opens/closes, definitely not during.

**Comment by blackd** [comment]
Yes I do understand what you mean. As I said if you join discord I'll give you a version that does auto sorting on open so you can see how it breaks stack management.
