### ISSUE TITLE
Cant see Inventory profiles next settings

### ISSUE THREAD

**Issue by TRTUI** [blackd/Inventory-Profiles#234]
I accidentally made the settings hidden and i cant open them again is there i way to open them again using shortcut or something?

**Comment by blackd** [comment]
what do you mean made it hidden?

**Comment by TRTUI** [comment]
I cant see it

**Comment by blackd** [comment]
i mean how did you do that?

**Comment by TRTUI** [comment]
I turned something to false and i cant open settings

**Comment by TRTUI** [comment]
Any Idea to fix it?

**Comment by blackd** [comment]
come in our discord server https://discord.gg/23YCxmveUM
