### ISSUE TITLE
Add option to disable scrolling item

### ISSUE THREAD

**Issue by Sawaumi** [blackd/Inventory-Profiles#237]
Or even better, add options to modify scrolling items and scrolling item modifiers' hotkeys, e.g, rather than using customizable modifier hotkeys, use hotkeys that default as "Shift+MouseWheelUp"/"Shift+MouseWheelDown". (Thus unbind them = disable feature)

This issue was made because the scrolling feature will conflict with item scroller (with useSlotPositionAware Scroll direction setting to false as in the inventory GUI item scroller will try moving in the opposite direction as inventory profiles)

Also, can we have a ItemScroller-like useSlotPositionAware potion (to disable that position awareness)? My muscle memory just simply cannot react to a different scroll logic, also having the same hotkey for "pushing the item" makes more sense for my smooth brain.

**Comment by blackd** [comment]
to disable it you can always unset the hotkeys for it.

**Comment by Sawaumi** [comment]
I don't think in the current 1.8.5 version there is a hotkey setting for scrolling item itself (only the 4 modifiers have key bind settings) or did I miss something?

**Comment by blackd** [comment]
it the hotkeys page

**Comment by Sawaumi** [comment]
I'm being stupid on the internet again I found it now thank you for your reply!

Still, I suggest a "useSlotPositionAware/disableSlotPositionAware" potion there (to have one wheel action for "send an item to the other container" and the other direction will be "retrieve an item of this from the other container")

maybe I should start a new issue on this.

**Comment by blackd** [comment]
I don't like the idea of scroll up always sending the item to the other container. So I probay won't add it.

And tbh i added scrolling due to hight demand, not to just rip off other mods

**Comment by hhxc-0** [comment]
I'm facing an issue where unsetting the hotkeys doesn't solve the problem for me since the scrolling feature remains enabled. When attempting to scroll a stack of items in the item scroller by holding down shift, the inventory profile next interrupts the entire stack operation, moving only a single item instead.
