### ISSUE TITLE
Locked items wont get saved using the quick config key

### ISSUE THREAD

**Issue by Remodor** [blackd/Inventory-Profiles#238]
When using the quick lock hotkey, the locked slots wont get saved. Using the combination method (default: alt + click) everything works fine, even when changing the hotkeys.

Background: I was using this mod with alt + left klick to lock slots. Everything worked fine. However, I wanted to remap this to only the middle mouse button. Locking worked, but it is not saved. I tried to delete the save files and noticed that they are only created using the default method.

I think this is related to this issue: #45 

Thank you!

**Comment by blackd** [comment]
This was the behaviour of the original mod.
My guess is the intension was for it to be temporary.
TBH I haven't checked the code path that habdles it. May be it's a bug may be it's a feature 😂

**Comment by blackd** [comment]
#45 was about the naming scheme used. The server name weren't sanitised for characters not allowed in file names.

**Comment by Remodor** [comment]
Ahh, ok... Thanks for the quick reply! 

It is not reflected in the tooltip, so I would guess its a bug 🐛 
Up to you. Close this, if it is a feature 😉
