### ISSUE TITLE
Inventory Profiles Next-fabric-1.19[.1-2]-1.8.5 Keeps Causing Minecraft to Crash

### ISSUE THREAD

**Issue by kofsmg** [blackd/Inventory-Profiles#241]
Hello,

I am running Fabric on MC 1.19 and as a result I downloaded this version of Inventory Profiles Next. After installing this mod and its requisites (fabric-language-kotlin-1.6.0+kotlin.1.5.0 and libIPN-fabric-1.19-1.0.6) I am able to launch my MC client and get to the Mojang loading screen where the client then crashes. Removing the Inventory Profiles Next-fabric-1.19[.1-2]-1.8.5 mod from the mods folder stops the client from crashing.

**Comment by blackd** [comment]
just guessing because of lack of logs.

update kotlin to the latest version

**Comment by kofsmg** [comment]
> 

Oh, you may definitely be right. I am not sure why when I went to download from Curseforge the top version was outdated. I had that happen to another mod too. So sorry for the useless issue here. Thanks!
