### ISSUE TITLE
(Mod Compatibility Request) Inventorio

### ISSUE THREAD

**Issue by GrantedSuper** [blackd/Inventory-Profiles#244]
I would love the ability to auto-replace near-broken tools within the tool belt of Inventorio using Inventory Profiles Next.

Running 1.19.2 Fabric on a Mac laptop.

Link: https://www.curseforge.com/minecraft/mc-mods/inventorio

**Comment by blackd** [comment]
I've spoken with the author of Inventorio about that and it won't be possible. The information about its slots is only available client side while the inventorio screen is shown.
