### ISSUE TITLE
Crashing when using the buttons in the inventory UI

### ISSUE THREAD

**Issue by Prototyx5** [blackd/Inventory-Profiles#246]
When i press any of the buttons in the inventory UI the game crash
Here is the crash log from "Not Enough Crash"
https://crashy.net/j2HdFyUbe1FJdt0JqgHe?raw

**Comment by blackd** [comment]
the provided information is not sufficient

please add list of the mod files you have installed

also quilt support is **as is** and no special efforts will be made if the fabric version  is not enough

**Comment by blackd** [comment]
all of my attempts to recreated this failed.

I will need the mod file list to continue

**Comment by Wallano-pand** [comment]
same problem here 

https://pastebin.com/XxQNujjE

**Comment by blackd** [comment]
Hi can one or both of you try with clean installation 
only IPN, lbIPN, kotlin and fabric api

**Comment by Wallano-pand** [comment]
made it, with a new .minecraft folder to ensure the other files are not corrupted
guess its a conflict with the quilt itself in 1.19.2 fabric version
sad

the crash report:
https://crashy.net/DeoGj3kt3c39Mgt62l11?raw

**Comment by blackd** [comment]
@Wallano-pand you have the wrong version for libIPN  `libIPN-fabric-1.19.3-1.0.7.jar` install `libIPN-fabric-1.19-1.0.7.jar`

**Comment by blackd** [comment]
I guess @Prototyx55  has the same problem

**Comment by Wallano-pand** [comment]
oh god i didnt see it, thanks, that was the problem

**Comment by blackd** [comment]
this problem actually exists in 1.19.3
