### ISSUE TITLE
crash when I open bag UI

### ISSUE THREAD

**Issue by DarkCrystalll** [blackd/Inventory-Profiles#247]
1.19.2Fabric
[minecraft-exported-crash-info-2022-12-02T14-18-24.zip](https://github.com/blackd/Inventory-Profiles/files/10138653/minecraft-exported-crash-info-2022-12-02T14-18-24.zip)

**Comment by blackd** [comment]
what modpack is this?

Also my guess is that i happens while you are opening a UI provided by a mod or vanilla UI with slots added by a mod. 

Can you provide this information?

**Comment by DarkCrystalll** [comment]
https://www.curseforge.com/minecraft/mc-mods/scout
maybe,I guess

**Comment by DarkCrystalll** [comment]
This crash was caused by opening the original inventory

**Comment by blackd** [comment]
this was reported to scout long time ago 

https://github.com/Cynosphere-mc/Scout/issues/24

**Comment by DarkCrystalll** [comment]
ok,will it fix?

**Comment by blackd** [comment]
so far it doesn't look like the author will continue development
