### ISSUE TITLE
cant use in 1.19.2 what should i do ?

### ISSUE THREAD

**Issue by osebok** [blackd/Inventory-Profiles#249]
Hello , i am using ur mod in 1.19.2 Forge , and both versions of 1.19 i had tried , and it dosen't work at all. it shows up and said  "needs language provider kotlinforforge:3 or above to load " what dose it mean ,should i try to install the 1.18 versions ? ,please help thx

**Comment by blackd** [comment]
`needs language provider kotlinforforge:3` is the key..... https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge

and before you come back you also need to install libIPN https://www.curseforge.com/minecraft/mc-mods/libipn
