### ISSUE TITLE
Unable to sort Mekanism's chests.

### ISSUE THREAD

**Issue by Fiocher** [blackd/Inventory-Profiles#250]
e.g. Personal Chest and Personal Barrel.
Hotkey not working, no sort button.
It's like IPN doesn't recognize it as a sortable chest.
[Version]
Minecraft 1.19.2
Forge 43.2.0
Kotlin for Forge 3.7.1
libIPN 1.0.8
IPN 1.8.6
Mekanism 10.3.5.473

**Comment by blackd** [comment]
are those the only mods installed

**Comment by Fiocher** [comment]
> are those the only mods installed

![Snipaste_2022-12-14_11-38-55](https://user-images.githubusercontent.com/82749343/207499678-c26f6d33-67f7-4a03-b668-0933ed1526bc.png)
Yes, and JEI

**Comment by blackd** [comment]
As a workaround you can extract this file [ModIntegrationOverride.zip](https://github.com/blackd/Inventory-Profiles/files/10224463/ModIntegrationOverride.zip) in `config/inventoryprofilesnext`.

And the general fix will be available in the next release.

**Comment by Fiocher** [comment]
> As a workaround you can extract this file [ModIntegrationOverride.zip](https://github.com/blackd/Inventory-Profiles/files/10224463/ModIntegrationOverride.zip) in `config/inventoryprofilesnext`.
> 
> And the general fix will be available in the next release.

Thanks！

**Comment by blackd** [comment]
this will be released in 1.9.2
