### ISSUE TITLE
Item scrolling

### ISSUE THREAD

**Issue by Domen-1** [blackd/Inventory-Profiles#252]
Scrolling items to the inventory, but it does not scrolling it to the hotbar, this is not very convenient, is it possible to disable this function somehow, or enable scrolling in the hotbar

**Comment by blackd** [comment]
as with all other functions of this mod hotbar is excluded by default

holding alt includes it

**Comment by Domen-1** [comment]
> holding alt

Where is this function, I can't find it

**Comment by blackd** [comment]
the ALT key

**Comment by Domen-1** [comment]
can it be done without pressing a key?

**Comment by blackd** [comment]
as I've said already everything in this mod doesn't touch the hotbar except with explicit player input

So no it can be done without holding alt

**Comment by Domen-1** [comment]
okay, is it possible to disable this feature? item scrolling

**Comment by blackd** [comment]
remove the keybinds for scroll up/down

**Comment by Domen-1** [comment]
thenks
