### ISSUE TITLE
Traveler's backpack mod sorting compatibility issues

### ISSUE THREAD

**Issue by Renektoff** [blackd/Inventory-Profiles#253]
While using the Traveler's Backpack mod (https://www.curseforge.com/minecraft/mc-mods/travelers-backpack), pressing R in the open backpack is kinda broken. It first sorts items inside the crafting bench section of the backpack and subsequently pressing R picks up an item from the backpack's inventory even if not hovering it.

Not sure how difficult it will be to resolve that compatibility issue, but at the very least if you let me know of some workaround with which I could disable R sorting while in the open backpack UI I'd appreciate it :)

**Comment by blackd** [comment]
press r+g
and set player side only to. true

**Comment by Renektoff** [comment]
Thanks! Not sure if there's a way to configure some specific blocks to be overriden so it excludes the sorting. I think this works almost perfectly. Its just that it sorts items inside the backpack crafting table first, so if those blocks could be excluded in general this would work almost perfectly. I appreciate the help :)

**Comment by blackd** [comment]
Unfortunately the way travelers backpack are too different from vanilla to be handled properly.
The setting above is build in the mod but it appears they have changed something and IPN no longer detects it.
In the next version travelers backpacks will once again be blacklisted.

**Comment by Renektoff** [comment]
Gotcha! Well thanks anyway and I appreciate your work :)
