### ISSUE TITLE
Inventory Profile and ItemSwapper

### ISSUE THREAD

**Issue by futag** [blackd/Inventory-Profiles#254]
when pick item using **ItemSwapper** and `locked_slots_empty_hotbar_as_semi_locked` is **true**, item move back to inventory instead pick to Hotbar

**Comment by futag** [comment]
Using minecraft 1.9 with fabric 0.14.11 and Fabric API 0.58.0

**Comment by blackd** [comment]
this is a know issue and will also affect locked slots in the hotbar

unfortunately the itemwapper author did not show interest in integration with IPN API that will allow this to be solved

I suggest you post a request to their issue tracker for implementing interoperability with IPN

**Comment by blackd** [comment]
Looks like the latest version of ItemSwapper set MinecraftClient.currentScreen when showing GUI. This is enough for IPN not to interfere  with items put in the hotbar.
So I'll close this as done
