### ISSUE TITLE
[1.19.2-Forge 43.2.0] Incompatibility with mod "Raised"

### ISSUE THREAD

**Issue by thimblebird** [blackd/Inventory-Profiles#256]
[Raised](https://www.curseforge.com/minecraft/mc-mods/raised) raises the hotbar:

![2022-12-23_16 41 13](https://user-images.githubusercontent.com/93487547/209361928-1e1aaed7-a52e-44be-9036-e9466e807e2a.png)

**Comment by blackd** [comment]
it's up to raised to ensure compatibility since they change the vanilla hotbar
