### ISSUE TITLE
Elytra Setup

### ISSUE THREAD

**Issue by Mshangao** [blackd/Inventory-Profiles#258]
I tried, a lot of times, but it never worked. When I switch profile from elytra to chestplate, my fireworks stays in offhand. I turned off autorefill option in this mod and in Tweakeroo and still no changes. I'm frustrated as hell. So simply, but doesn't work.

**Comment by blackd** [comment]
Hi can you join our discord for support questions 
https://discord.gg/23YCxmveUM
