### ISSUE TITLE
Crash when trying to join a server 1.19.2 Quilt

### ISSUE THREAD

**Issue by NantaArthur123** [blackd/Inventory-Profiles#259]
When I'm trying to connect to server, my client crashes. I'm trying to read the crash log, but I'm not sure where to start. Would you be willing to review the crash log and see if you can offer any suggestions for how to fix the issue? I'd be very grateful for your help.

Game Version: 1.19.2

Modloader: Quilt

Crashlog:
[crash-2022-12-29_16.47.15-client.txt](https://github.com/blackd/Inventory-Profiles/files/10318729/crash-2022-12-29_16.47.15-client.txt)

Full Log:
[latest.log](https://github.com/blackd/Inventory-Profiles/files/10318731/latest.log)

**Comment by blackd** [comment]
can you test it with fabric. quilt is supported as long as it behaves like fabric.

**Comment by blackd** [comment]
also try removing the mod and see what happens
logs suggest that it might fail anyway

**Comment by NantaArthur123** [comment]
Hi, thank you for your reply, I tried to remove Inventory profile next, and libIPN, and I was able to connect to the server.

**Comment by blackd** [comment]
are any of the other mods quilt specific

**Comment by NantaArthur123** [comment]
The bumble zone
OK Zoomer
geckolib
Midnight Lib
QFAPI

Maybe that's all? I'm not so sure.

**Comment by blackd** [comment]
only OK zoomer is quilt only
and Zoomify is way better alternative

qfapi is the equivalent of fabric api

the rest have fabric versions

it will be much easier for you to test with fabric them for me to recreate your setup

**Comment by NantaArthur123** [comment]
got it!, I will try to test it using fabric loader and re add all the mods

**Comment by NantaArthur123** [comment]
Just confirmed that this problem only happening when using quilt modloader

**Comment by blackd** [comment]
thank you very much for the help
