### ISSUE TITLE
Locked slots will auto move out items in it when change the dimension

### ISSUE THREAD

**Issue by KigeYark** [blackd/Inventory-Profiles#26]

**Comment by blackd** [comment]
this one will be hard to solve... it looks like when switching dimensions sometimes the player spawns with empty inventory and then the server sends the client the content...

**Comment by srnyx** [comment]
Has this been fixed in the latest release? Cause it's still happening to me.

**Comment by blackd** [comment]
what are the  versions of the mod, minecraft and server if known
and which modloader

**Comment by srnyx** [comment]
> what are the versions of the mod, minecraft and server if known
> and which modloader

Mod: 0.8.5
Minecraft: 1.16.5
Server: Purpur 1.16.5
Modloader: Fabric

**Comment by KigeYark** [comment]
> what are the versions of the mod, minecraft and server if known
> and which modloader

Minecraft ver is 1.17.1, and mod ver is 0.8.3, that's the latest version when I post this issue. Loader is Fabric

**Comment by blackd** [comment]
@srnyx sometimes purpur is slow to update the client on dimension change. You need to increase "Ticks to wait on dimension change" in Mod Settings until it stops happening. 

@KigeYark It should be fixed in the later versions.. If you still have problems adjust the above setting.

**Comment by srnyx** [comment]
> @srnyx sometimes purpur is slow to update the client on dimension change

It was happening before I switched from Paper to Purpur I'm pretty sure
