### ISSUE TITLE
Incompatibility with `Scout`

### ISSUE THREAD

**Issue by EthanZeigler** [blackd/Inventory-Profiles#262]
IPN causes the render thread to hang when an item is picked up when the mod [scout](https://modrinth.com/mod/scout) is also installed.

https://gist.github.com/EthanZeigler/fbadbe1dc6c48d7a3821b1cf4c884905

Can compatibility be added between these mods? I have a suspicion the "pick up into inventory" setting being set to true is what's causing this since the player inventory itself has been modified.

**Comment by blackd** [comment]
versions? and modloader?

**Comment by blackd** [comment]
they declined to fix this 

https://github.com/Cynosphere-mc/Scout/issues/24

latest mod version may be has a workaround for it but I can't guarantee it since thir slots doesn't behave like vanilla

**Comment by EthanZeigler** [comment]
I appreciate the effort nonetheless. All the loader/version stuff is in the pastebin, but it's fabric 1.14.12, scout 1.1.1, ipn 1.9.1, mc 1.19.2

**Comment by blackd** [comment]
sorry but 1.14.x is no longer supported and the workaround probably didn't make it in the last release for 1.14.x

**Comment by EthanZeigler** [comment]
I'll probably fork and make a pr for if that's okay

**Comment by blackd** [comment]
join our discord if you have questions

**Comment by Seikm** [comment]
> sorry but 1.14.x is no longer supported and the workaround probably didn't make it in the last release for 1.14.x

Minecraft version is 1.19.2, 1.14 is the fabric loader version.

I'm instantly crashing when I open the inventory.
Not Enough Crashes is saying that the problem is the IPN.
I'm using Minecraft 1.19.2, IPN 1.9.1, Scout 1.1.1 and Quilt Loader 0.17.8.
The crash report is pretty much the same as the issue.

**Comment by blackd** [comment]
quilt is no longer supported due to behaviour differences with fabric

this is causes by scout because they add slots and make them behave differently then vanilla
