### ISSUE TITLE
Pick Block replaces locked slots

### ISSUE THREAD

**Issue by Dojando1** [blackd/Inventory-Profiles#263]
I have 5 Tools in the first 5 slots of my hotbar. I installed this mod ONLY to be able to lock those 5 slots to prevent my tools being replaced by the pick block feature. However, if I have my pickaxe in my hand, press the "pick block" key, it will still replace the tool instead of any other slot that has a block in it.

**Comment by blackd** [comment]
for multiplayer it's not possible to prevent this since it is handled by the server

in single player it should work as expected

**Comment by blackd** [comment]
you can try and disable all user input for locled slots but this will disable block picking for locked slots in general and you will have to select non locked slot to be able to pickup a block

**Comment by Dojando1** [comment]
aah okay, no I play multiplayer unfortunately :)
Could we install the mod on the server and it would work then or is this only clientside? 
And I have already disabled all user input but its not working. Probably since its multiplayer again.

**Comment by blackd** [comment]
the mod is client side only
it does nothing on the server

**Comment by Dojando1** [comment]
alright, then I guess I have to deal with it. Thanks anyway :)
