### ISSUE TITLE
How to reset the configuration

### ISSUE THREAD

**Issue by ElGomez23** [blackd/Inventory-Profiles#264]
I was testing the different configurations of the mod, when I hid the configuration option on the top left. I would like to know how to reset the configuration or open it if possible

**Comment by blackd** [comment]
You can still show the settings by pressing `r+c` in game
Or by using the `Mods` button. If you are on fabric and you don't have `Mods` button you need to install "Mod Menu"

If you really want to just reset the configuration you can delete this file `config/inventoryprofilesnext/inventoryprofiles.json`

**Comment by ElGomez23** [comment]
R+C worked thaks!!!
