### ISSUE TITLE
Disable Features by Default

### ISSUE THREAD

**Issue by TheAyes** [blackd/Inventory-Profiles#265]
So I've used your mod many times now and every single time I felt like the default configuration is way to intrusive.
It's on you to decide but I'd prefer the approach of giving the user a very very very minimalistic default version of your mod, with giving them the opportunity to enable additional features.
I literally been so annoyed by this workbench refill that I just went through your config to disable literally everything, so I can slowly roll things in I actually want to have.
I'm sorry if it sounds harsh, but please acknowledge this.

**Comment by blackd** [comment]
![unknown-20.png](https://user-images.githubusercontent.com/333840/212579919-6b618409-8306-453e-8f01-3fb3a9a0542f.png)

Have you noticed this little checkbox?

**Comment by blackd** [comment]
But on the main complain.

Most players don't even know there is a configuration and generally don't care to seek it. The overlay buttons are the thing that points them that something is different.

And it begins with "Ohhh what does this button do?"

So being "in your fase" and enabled by default makes the players interested and helps them discover the features. If everything is disabled and hidden noone will ever progress after the basic sorting. 

I know this is annoying for some of the players, but talking numbers it's a small fraction and usually those are the players that will find and figure how to use the config anyway. 

The most controversial of the enabled by default stuff is the direct to inventory picking up. The goal of enabling it was to make people look for the settings. I has done perfectly in that regard. People that come for help and not knowing there was a configuration has dropped from 80% to 25% and people that seek help for advanced stuff has tripled. 

So I will probably continue to enable new features by defaut so people will at least know that they exist.

**Comment by TheAyes** [comment]
Yea, as I said that's on you to decide I just wanted to let you know how some might feel. :)
