### ISSUE TITLE
Forge Dependencies 

### ISSUE THREAD

**Issue by TimeStop12** [blackd/Inventory-Profiles#266]
It would be nice if the the dependencies were shown for both versions of the mod either on the relations page or on the main page.

**Comment by blackd** [comment]
like this?

![Screenshot_20230116-070250.jpg](https://user-images.githubusercontent.com/333840/212602495-a2f840ac-6525-431c-818e-b14de755c817.jpg)

and this?

![Screenshot_20230116-070326.jpg](https://user-images.githubusercontent.com/333840/212602524-7391de1d-5c01-42ab-b5d7-bba726eb92bd.jpg)

**Comment by TimeStop12** [comment]
Yeah, currently there is no way to see what is needed for either version. Both on the main curseforge site and the beta site. Is that what you see when your editing the page?

**Comment by blackd** [comment]
don't blame me for curseforge stupidity 
these pages open when you click on the file name


https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4263991

https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4263995

**Comment by TimeStop12** [comment]
I know this is closed now but, would it be possible to show the dependencies on the main page as the beta site actually does not show dependencies on the file page. and funny enough clicking relations goes back to the non beta site. I think even the app wont show the dependencies... (as it just auto installs them without showing it until you go back to what mod you have in the profile)
