### ISSUE TITLE
Game crash "inventory must not be null"

### ISSUE THREAD

**Issue by amidnightblue** [blackd/Inventory-Profiles#267]
Fabric 1.19.2, creative mode (not tested in survival)

Crashes when picking up an item. I can see that ipnext is involved but don't understand anything else.
[crash-2023-01-16_17.23.22-server.txt](https://github.com/blackd/Inventory-Profiles/files/10423416/crash-2023-01-16_17.23.22-server.txt)

Had the same crash message previously when I accidentally opened EMI's recipe viewer, but that looks like it might have something to do with the continuous crafting feature? Maybe mod incompatibility?
[crash-2023-01-16_16.39.28-client.txt](https://github.com/blackd/Inventory-Profiles/files/10423471/crash-2023-01-16_16.39.28-client.txt)

Please tell me if there's more info I need to give, I'm relatively new to modding Minecraft (and it seems unnecessarily complicated compared to other games).

**Comment by blackd** [comment]
Hi,

You don't need the mod on the server it only works client side.

The problem is caused by scount but they refuse to fix it.  And not being very  nice about it https://github.com/Cynosphere-mc/Scout/issues/32 

to quote it here 

> And considering the fact the dev wants to shift the blame on me instead of just null checking things because "weh its not something vanilla does!" and wants to drop Quilt support for IPN anyways, I genuinely cannot care anymore, nor recommend anyone use IPN anymore.

>But what do I expect from a mod dev that basically stole a mod from another person to maintain it and slapped a license incompatible for Minecraft modding. Sorry everyone using IPN is caught in the crossfire of the entitlement plague of the modding scene.

anyway I'll probably do something about it.

**Comment by amidnightblue** [comment]
Oh darn looks like I'll have to choose then until a fix is released. Hope you can work out something that works for both of you.

I don't know anything about installing server-side. I just put it in the mods folder. Is that something I need to fix?

**Comment by blackd** [comment]
> I don't know anything about installing server-side. I just put it in the mods folder. Is that something I need to fix?

just remove IPN from the mods folder of the server.

**Comment by amidnightblue** [comment]
I only have one mods folder that I'm aware of. I don't use the default .minecraft folder, have made separate folders for each profile in the launcher. I play singleplayer so I don't do anything with servers. Where would I find the server specific folders? Sorry to bother you with this, it seems to be working fine as is if you're busy.

**Comment by blackd** [comment]
well why is this file [crash-2023-01-16_17.23.22-server.txt](https://github.com/blackd/Inventory-Profiles/files/10423416/crash-2023-01-16_17.23.22-server.txt) called ....-server.txt
Anyway if you don't run your own server  you don't have to do anything.

**Comment by Niko2700** [comment]
My game crashes everytime I try to create a world

**Comment by blackd** [comment]
@Niko2700 Remove the mod. scout

**Comment by blackd** [comment]
@Niko2700  actually since it crashes whenever you try to create new world
can you open a new issue and post logs from failed start

and at least explain why do you think it's IPN fault

**Comment by blackd** [comment]
handled in v1.9.2
