### ISSUE TITLE
Lost the menu

### ISSUE THREAD

**Issue by Zipaine** [blackd/Inventory-Profiles#268]
so uh I was unbinding unnecessary hotkeys and I accidentally unbinded the menu and hid the menu buttons any fixes ;-;?

**Comment by blackd** [comment]
the Mods button in the main menu

there are also 2 a small buttons top left of the screen when the inventory is opened.. if you haven't disabled those too 🤣


if you don't have Mods button then install the mod "Mod Menu".

**Comment by Zipaine** [comment]
yea thank you I am going to install the mod menu thank you ;-;
