### ISSUE TITLE
make when pressing shift ignore auto tool switch

### ISSUE THREAD

**Issue by Yumileashen** [blackd/Inventory-Profiles#270]
would be great :) if pressing shift with the tool didn't auto switch

**Comment by blackd** [comment]
you mean don't replace it when it's about to break if the player is holding shift?

**Comment by Yumileashen** [comment]
yes thats right

**Comment by blackd** [comment]
It makes sense to have easy way to temporarily switch it off, but I'm not sure sneaking is the best way to do it.
I'll think about it.
