### ISSUE TITLE
Adding gaps into sorting items.

### ISSUE THREAD

**Issue by teoWei** [blackd/Inventory-Profiles#272]
Is there a way to sort items like this? (gaps are where any items are sorted)
![image](https://user-images.githubusercontent.com/54856793/214932558-cc0cc045-a9ea-4196-8c9b-b67916400504.png)
If not, please add one.

Suggestion:
You can add SLOT1-27 for inventory profiles to solve this problem.
Or
You can add a way to leave gap for universal item sorting in custom rules.

**Comment by blackd** [comment]
Nope it is not possible to have such configuration.

Nope I will not be adding the inventory to the profiles any time soon. This has been discussed multiple times with different people but it comes with some technical problems that makes it... very annoying to implement. 

Current sort implementation has no concept for empty slot. And even if I introduce one I doubt you will be able to get this inventory configuration as a result.

If you think you have an idea how to do it I will be very happy to heat it.

**Comment by teoWei** [comment]
I'll try to think of an idea.
