### ISSUE TITLE
Hotbar items moved to inventory after respawn when using 'pick items directly into the inventory'

### ISSUE THREAD

**Issue by H3XDaemon** [blackd/Inventory-Profiles#273]
Hello,

I am experiencing an issue when using the "pick items directly into the inventory" feature on a server where the gamerule keepInventory is set to true. After respawning, all items in my hotbar are moved to my inventory.

Before:
![before](https://user-images.githubusercontent.com/42803553/215014518-3a6e1b2f-a02e-4615-b092-8a71c60a80c0.gif)

After:
![after](https://user-images.githubusercontent.com/42803553/215014948-4522a808-b974-441c-91a1-13f7f2928638.gif)

I would appreciate any help in resolving this issue.
Thank you.

**Comment by blackd** [comment]
this is actually caused by the server
you can try increasing the timeout on world/server change in the locked slots page of the settings


if it doesn't work disabling pickup into inventory is the only way

**Comment by H3XDaemon** [comment]
Thank you for the quick response, I will try increasing the timeout. If it doesn't work, I understand that disabling pickup into inventory is the only other option. Thank you for your help.
