### ISSUE TITLE
game crash with unknown reason

### ISSUE THREAD

**Issue by amaneyunomi** [blackd/Inventory-Profiles#274]
when i use [shift+mouse left click] to a item in inventory,the game crash. here is the crp(crash report)
URL:https://bytebin.lucko.me/aLeqTpGd39
if you cant open that URl, you can see below
============================================
`---- Minecraft Crash Report ----
// There are four lights!

Time: 1/27/23, 1:14 PM
Description: Unexpected error

java.lang.NullPointerException:  must not be null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
	at org.anti_ad.mc.ipnext.event.MiscHandler.slotAction(Unknown Source)
	at org.anti_ad.mc.ipnext.event.MiscHandler.swipeMoving(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ClientEventHandler.onTickInGame(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ClientEventHandler.onTick(Unknown Source)
	at net.minecraft.client.MinecraftClient.handler$efm000$tick2(MinecraftClient)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1817)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.anti_ad.mc.ipnext.event.MiscHandler.slotAction(Unknown Source)
	at org.anti_ad.mc.ipnext.event.MiscHandler.swipeMoving(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ClientEventHandler.onTickInGame(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ClientEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$efm000$tick2(class_310.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['xmy_yunomi'/140, l='ClientLevel', x=-40.87, y=68.00, z=95.71]]
	Chunk stats: 1024, 621
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,64,64), Section: (at 0,0,0 in -2,4,4; chunk contains blocks -32,-64,64 to -17,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 196139 game time, 294630 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Compressor, Fabric Mods, loadmyresources.hiddenpack, Resource Pack Credits (open me!), Create Legacy Copper, computercraft/classic, continuity/default, continuity/glass_pane_culling_fix, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.2.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 900305768 bytes (858 MiB) / 3275751424 bytes (3124 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 4.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2802
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26050.01
	Virtual memory used (MB): 19507.93
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 341.17
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m
	Fabric Mods: 
		ad_astra: Ad Astra! 1.0.2
			team_reborn_energy: Energy 2.2.0
		aileron: Aileron 1.0.0
		alternate-current: Alternate Current 1.4.0
		ambientenvironment: Ambient Environment 7.0+19
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.9.84
		autoconfig1u: Auto Config v1 Updated 3.4.0
		automobility: Automobility 0.2.1+1.18.2
			jsonem: JsonEM 0.1.2
			myron: Myron 1.6.3+1.18.1
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.2.0+0
		betteradvancements: Better Advancements 0.2.1.132
		bettercombat: Better Combat 1.4.4+1.18.2
		betterf3: BetterF3 3.0.0
		blanket-client-tweaks: Blanket Client-tweaks 1.0.4
		borderless_window: Borderless Window 1.3.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.8-1.18.2
			maelstrom_library: Maelstrom Library 1.2.4-1.18.2
			multipart_entities: MultipartEntities 1.1.5-1.18.2
		bsvsb: Better Sodium Video Settings Button 2.0.5
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.7.0
			com_ishland_c2me_libs_: libs 0.2.0+alpha.7.0
		campanion: Campanion 3.0.3
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.2.0
		capybara: Capybara 1.0.6
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		carpet: Carpet Mod 1.4.69
		catwalksinc: Catwalks Inc. 1.3.0
		cccbridge: CC:C Bridge 1.3.0
		cem: Custom Entity Models 0.7.1
		chassis: Chassis 1.1.0
		chat_heads: Chat Heads 0.6.0
		chunky: Chunky 1.2.164
		citresewn: CIT Resewn 1.1.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.18.2
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+15
		cobblegen: CobbleGen v1.11b36+mc1.18.x
			omega-config: OmegaConfig 1.2.3-1.18.1
		collective-fabric: Collective (Fabric) 4.36
			fiber: fiber 0.23.0-2
		combatroll: Combat Roll 1.0.8+1.18.2
		completeconfig: CompleteConfig 1.4.1
		compressor: Compressor 0.2.0
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		computercraft: CC: Restitched 1.100.8
		continuity: Continuity 2.0.0+1.18.2
		controlling: Controlling For Fabric 9.0+22
		create: Create 0.5.0e-733
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 0.6.4-30
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.4
		create_crystal_clear: Create: Crystal Clear 1.0-fabric-patch1
		createaddition: Create Crafts & Additions ${version}
		createdeco: Create Deco 1.2.9-1.18.2
		creativecore: CreativeCore (Fabric) 2.6.12
		cull-less-leaves: Cull Less Leaves 1.0.1
		customloadingscreen: Custom Loading Screen 1.0.1
		debugify: Debugify 1.11.0
		diggusmaximus: Diggus Maximus 1.5.6-1.18
			kyrptconfig: Kyrpt Config 1.4.6-1.18
				blue_endless_jankson: jankson 1.2.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		doodads: Doodads 0.1.2-1.18.2
		drinkbeer: Drink Beer 3.0.2
		dustrial_decor: Dustrial Decor 0.5
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ears: Ears 1.4.5_01
		elytra_physics: ElytraPhysics 1.0.2
		entity_texture_features: Entity Texture Features 4.0.2
		entityculling: EntityCulling-Fabric 1.5.1
		environmentalcreepers: Environmental Creepers 1.6.0
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.3
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fancymenu: FancyMenu 2.12.6
		farmersdelight: Farmer's Delight 1.18.2-1.2.2
		fastload: Fast Load 1.2.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 3.2.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		ftblibrary: FTB Library 1802.3.6-build.140
		ftbquests: FTB Quests 1802.3.8-build.106
		ftbteams: FTB Teams 1802.2.6-build.51
		geckolib3: Geckolib 3.0.62
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 19
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.12.3_fabric
		harvestwithease: Harvest with ease 4.0.0.0
		hotbarswap: Hotbar Swap 1.0.2
		iceberg: Iceberg 1.0.38
		idwtialsimmoedm: idwtialsimmoedm 0.1.1+1.18
		incendium: Incendium + Seed Fix 5.0.4
			seedfix: Seed Fix 1.0.2
		indium: Indium 1.0.7+mc1.18.2
		indrev: Industrial Revolution 1.14.0-BETA
			libblockattributes_core: LibBlockAttributes (Core) 0.10.0
			libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
			libblockattributes_items: LibBlockAttributes (Items) 0.10.0
			libgui: LibGui 5.3.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
			magna: Magna 1.7.0-1.18-pre1
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		ingameime: IngameIME 1.6.5
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.9.1
		invmove: InvMove 0.7.0
		iris: Iris 1.3.1
			org_anarres_jcpp: jcpp 1.4.14
		irisflw: Iris Flywheel Compat 1.18.2-0.1.5-ALPHA
		itemfilters: Item Filters 1802.2.7-build.33
		itemphysiclite: ItemPhysic Lite (Fabric) 1.5.0
		java: OpenJDK 64-Bit Server VM 18
		konkrete: Konkrete 1.5.3
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		kubejs: KubeJS 1802.5.4-build.533
		kubejs_create: KubeJS Create 1802.2.2-build.26
		lambdabettergrass: LambdaBetterGrass 1.2.4+1.18
			spruceui: SpruceUI 3.3.3+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.5
		letmedespawn: Let Me Despawn fabric-1.0.0
		libipn: libIPN 2.0.1
		libraryferret: Library Ferret 2.0.0
		limitedchunks: Limited Chunkloading Mod 1.18.2-2.5
		lithium: Lithium 0.7.10
		loadmyresources: Load My Resources 1.0.1
		mcdw: MC Dungeons Weapons 5.0.2-1.18
			enchant_giver: Enchant Giver 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		memoryleakfix: Memory Leak Fix 1.18.2-0.7.0
		midnightlib: MidnightLib 0.4.4
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.3
		naturalist: Naturalist 1.1.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		packages: Packages 3
		packed-inventory: Packed Inventory 0.2.2+1.18.2
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		phonos: Phonos 0.3+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		player-animator: Player Animator 0.3.5
		polaroidcamera: PolaroidCamera 1.2.9
		probablychests: Probably Chests 0.5.4-1.18.2
		projectiledamage: Projectile Damage Attribute 1.0.7
		puzzle: Puzzle 1.4.0-1.18
			puzzle-base: Puzzle Base 1.4.0-1.18
			puzzle-gui: Puzzle GUI 1.4.0-1.18
			puzzle-models: Puzzle Models 1.4.0-1.18
			puzzle-splashscreen: Puzzle Splash Screen 1.4.0-1.18
		puzzleslib: Puzzles Lib 3.3.5
		questsadditions: Quests Additions 1.4.0
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.18.2-build.58
		rhino: Rhino 1802.1.14-build.225
		roughlyenoughitems: Roughly Enough Items 8.3.529
			error_notifier: Error Notifier 1.0.9
		scout: Scout 1.1.1
		servercore: ServerCore 1.2.9-1.18.2
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 1.1.3+1.17.1
		servertick: Server Tick 1.6
		smoothboot: Smooth Boot 1.18.2-1.7.0
		smwyg: Show Me What You Got 1.0.1
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.10+mc1.18.2-build.63
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.9.1
		spyglass-improvements: Spyglass Improvements 1.2+mc1.18.2+fabric
		starlight: Starlight 1.0.2+fabric.89b8d9f
		starterkit-fabric: Starter Kit (Fabric) 3.5
		structures_compass: Structures Compass 1.18.2-1.4.2
		suggestion_tweaker: Suggestion Tweaker 1.18.2-1.3.0
		t_and_t: Towns and Towers - Structure Add-on 1.6
		tconstruct: Hephaestus 1.18.2-3.5.2.150
			mantle: Mantle 1.18.2-1.9.156
				satin: Satin 1.7.2
				star: Star 1.3+1.18.2
			porting_lib: Porting Lib 1.2.550-beta+1.18.2-stable
				com_github_llamalad7_mixinextras: MixinExtras 0.0.11
				mm: Manningham Mills 2.3
			serialization_hooks: Serialization Hooks 0.3.23
		toms_storage: Tom's Simple Storage Mod 1.4.3
		tooltipfix: ToolTip Fix 1.0.4-1.18
		trinkets: Trinkets 3.3.1
		vdm: Villainous Difficulty Multipliers 1.1.2-1.18
		voxelmap: Voxelmap 1.18.2-1.11.2
		walllanterns: Lanterns Belong on Walls 1.3.0-1.18.x
		wthit: wthit 4.13.1
		yigd: You're in Grave Danger 1.3.10
		yippee: Yippee 1.0.0
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
	Loaded Shaderpack: Sildur's+Vibrant+Shaders+v1.32+Extreme-VL.zip
		Profile: Custom (+0 options changed by user)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: Create Astral
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.02, NVIDIA Corporation
	Window size: 2560x1411
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, compressor, Fabric Mods, loadmyresources.hiddenpack, file/Resource Pack Credits (open me!), Create Legacy Copper, computercraft/classic, continuity/default, continuity/glass_pane_culling_fix
	Current Language: 简体中文 (中国大陆)
	CPU: 12x Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['xmy_yunomi'/140, l='ServerLevel[Create:Astral]', x=-40.87, y=68.00, z=95.71]]
	Data Packs: vanilla, compressor (incompatible), loadmyresources.hiddenpack (incompatible), Fabric Mods, global:BlazeandCaves Advancements Pack 1.13.8, global:New-End-Cities, global:daycountertitlemessage (incompatible), global:nullscape-v1-1-1, global:zLaky Core (incompatible), global:zTConstructAstra (incompatible)
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Inventory Profiles Next (inventoryprofilesnext), Fabric Loader (fabricloader)`

**Comment by blackd** [comment]
this is a know scout incompatibility
it will be addressed in the next release

scout slots won't be part of any operations ipn does

**Comment by amaneyunomi** [comment]
thanks for your help, i deleted scout, now it work expectly

**Comment by blackd** [comment]
fixed in v1.9.2
