### ISSUE TITLE
Error loading Inventory Profiles Next Mod

### ISSUE THREAD

**Issue by yvolii** [blackd/Inventory-Profiles#277]
I am currently having this weird loading error whenever I wanna start Minecraft Forge with the mod installed. Any ideas? I am playing on 1.19.3 Forge. No other mods installes. 

![image](https://user-images.githubusercontent.com/124112662/215929402-7317f10c-b191-44ba-bd7b-618584b6a376.png)

**Comment by blackd** [comment]
install kotlin for forge as the message says
