### ISSUE TITLE
inventorio compat

### ISSUE THREAD

**Issue by DanMeadWasTaken** [blackd/Inventory-Profiles#278]
The buttons in inventory profiles get pushed around weirdly when you enable the inventorio menu

![image](https://user-images.githubusercontent.com/75497984/216311510-f28c534c-5238-4e15-8420-7936a0786901.png)

**Comment by blackd** [comment]
press r+g or the bottom button of the 2 buttons top left
and you will be able to move the buttons

this is not the defaut position for inventorio so my guess is the modpack moved them
