### ISSUE TITLE
Cannot scroll items with memorized slots from sophisticated storage/backpacks

### ISSUE THREAD

**Issue by JJSax** [blackd/Inventory-Profiles#279]
Using the scrolling function is broken when using sophisticated storage's memory slot feature.  Scrolling an item out of the slot doesn't work at all, and trying to scroll items into a barrel with any slot memorized causes very strange behavior.

MC 1.18.2
mod version curseforge release date 1/29/2023 (no build version available in filename)
forge: 40.1.86

**Comment by blackd** [comment]
unfortunately IPN can't really offer compatability with every mod under the sun.
Modded storages is supported as long as it behaves close to vanilla. Anything else is impossible to support without very close integration with the mod in quiestion. Such integration requires too much effort and is outside of the current IPN goals.
