### ISSUE TITLE
For some reason i cant create a profile its just keep saying "NONE" i did everything as the youtube and the wiki says...

### ISSUE THREAD

**Issue by BambangLife** [blackd/Inventory-Profiles#280]

**Comment by BambangLife** [comment]
So i created a profile when i edit the profile to the name that i changed on the edit profiles thingy then when i tryed to go to the inventory still saying None

**Comment by blackd** [comment]
since it will be easier can you join our discord

**Comment by BambangLife** [comment]
ok

**Comment by blackd** [comment]
does this mean that you solved your problem?

**Comment by BambangLife** [comment]
not really

**Comment by blackd** [comment]
if you want me to help you https://discord.gg/23YCxmveUM and say something

**Comment by BambangLife** [comment]
ok
