### ISSUE TITLE
Hotbar is not working normally

### ISSUE THREAD

**Issue by Miku13666** [blackd/Inventory-Profiles#281]
Hello, and please tell me how to make it so that my things can be picked up in hotbar i. Because it really pisses me off that the things thrown out do not fall into the hand but into the inventory.
The inability to quickly add items to the hotbar is so annoying that I want to remove this mod.
Tell me where to poke there in the settings so that it works because I don't understand at all. I don't need profiles and they are inconvenient, I turned them off, but there is zero sense. It would also be great to remove the profiles button.

**Comment by blackd** [comment]
if the mod pisses you off that much just don't use it. 

it's all in the settings Locked Slots page for the items pickup and GUI Settings to enable disable buttons. 

Also this issue tracker is for problems reporting not for support questions. If you have further questions please use discord. Link is in the description here or on curseforge.

**Comment by Miku13666** [comment]
Thank you so much for your answer, the mod is very cool, but maybe because of the translation I didn't understand that the hotbar is just locked slots. I'm sorry that it turned out so rudely and not where it should be, I just poked at the settings for an hour, but I didn't get to the right one.
Another basin thanks a lot and sorry for the trouble. ♥
