### ISSUE TITLE
Add keybind to copy item ID

### ISSUE THREAD

**Issue by ModProg** [blackd/Inventory-Profiles#284]
Add a feature to copy the item id of a hoverd item.

Similar to "Dump Item Nbt To Chat" but copy to clipboard and just the id. (This should probably be configurable (maybe add 4 keybinds: copy nbt, copy id, dump nbt, dump id.))

**Comment by blackd** [comment]
what will you use this for?

**Comment by ModProg** [comment]
My use is creating tags for datapacks and wanting a way to easily access the ids I need to do so.

I can do it with the current implementation, but I always need to open the chat and copy the id from there making it not much faster than just typing it by hand.

**Comment by blackd** [comment]
Oh OK I can do that. I'm not sure about clipboard operations because it has to be implemented for the 3 supported operating systems.

Are you aware that you can use the mod to dump a file with all item ids currently supported by the game.

It's at the top of the Mod Settings page of the settings.

**Comment by ModProg** [comment]
> I'm not sure about clipboard operations because it has to be implemented for the 3 supported operating systems.

I think there is something builtin in the Minecraft APIs: https://maven.fabricmc.net/docs/yarn-1.19+build.1/net/minecraft/client/util/Clipboard.html

> Are you aware that you can use the mod to dump a file with all item ids currently supported by the game.

I didn't know that, that already helps.

**Comment by ModProg** [comment]
> It's at the top of the Mod Settings page of the settings.

I didn't find it

![grafik](https://user-images.githubusercontent.com/11978847/218262528-e67a46f4-8bb9-4cd7-b186-abe65814c417.png)

**Comment by blackd** [comment]
oops yes I remember now.... I remived it

but you can enable the Debug at the bottom of the page close and show the settings and there will be new debug page
at the bottom there is a button generate tags.*.txt this might help

**Comment by ModProg** [comment]
Seems like the list can be incomplete, I have at least one item, that is only in the tag `minecraft:impermeable` and was therefore apparently excluded from the list. (create:spruce_window)

**Comment by blackd** [comment]
it's generated from what is available in the registries when you generate it
may be it will be more accurate if you are in single player game compared to a server for example

**Comment by ModProg** [comment]
> it's generated from what is available in the registries when you generate it may be it will be more accurate if you are in single player game compared to a server for example

I did it on a single player world, but the problem probably is that it just exports the tags and not the actual items, and if an item is not in any of the exported tags it will be excluded.

**Comment by blackd** [comment]
May be.
Anyway I'll add copy and probably full item dump in next release.

**Comment by blackd** [comment]
done in 1.9.3-4
