### ISSUE TITLE
Pick up new items moved from Hotbar to Inventory

### ISSUE THREAD

**Issue by christiankarsch** [blackd/Inventory-Profiles#285]
If I pick up an item that not yet exist in my inventory and hotbar and a have a free slot in my hotbar and inventory.
The item are moved instandly after i pick it up from my hotbar to a free slot in my inventory.

I don't like this behavior and I couldn't find a way to turn it off in the options.

Game: 1.19.3
Loader: Forge 44.1.0
Mod: 1.9.2

**Comment by blackd** [comment]
it's in the locked slots page

![image-3.png](https://user-images.githubusercontent.com/333840/218319718-e144f34a-55ab-408e-ac18-ee7d741e5d8b.png)

**Comment by christiankarsch** [comment]
Thanks, a small improvement:

Pick Items directly into the inventory only if a stack of the type already in the inventor

**Comment by blackd** [comment]
this is how vanilla behaves

**Comment by christiankarsch** [comment]
I mean if a full stack (64) exist. Then the Item can create a new stack in the Inventory instead on the Hotbar.

**Comment by blackd** [comment]
I will check how easy is to achieve this and if it's not too complex I'll add it as an option
