### ISSUE TITLE
Crafted item is ripped out of hand when picked up from result solt.

### ISSUE THREAD

**Issue by christiankarsch** [blackd/Inventory-Profiles#286]
If an item is being crafted and it tries to be dragged from the result slot into the inventory/hotbar, it will be snatched from the 'hand' and placed in the first free slot in the inventory by the following reason:

One of the Ingeserens has emptied completely. Then the mod tries to replenish the Ingeserens.
I know it's not technically possible otherwise, doing the interact with the server its need a free 'hand'.

Therefore, the replenishment should only happen when the item has been dropt, not when it is grabbed.

**Comment by blackd** [comment]
As I understand your request you want the crafting grid to be refilled only if you drop the item you picked up from the result slot?

Although it might be possible to do that it will increase the complexity of already very very complex implementation and probably make it unstable.

Now IPN detects that a crafting has occurred and refills the grid. The detection will have to be moved outside this in an undetermined moment of time which will lead to errors in detection or at least undesired detections.

It barely works as it is and it needs tuning with every version of the game. So I'll have to decline this change.

**Comment by christiankarsch** [comment]
Is the a way to turn off auto refill for crafting, i don't find an option

**Comment by blackd** [comment]
![unknown-20.png](https://user-images.githubusercontent.com/333840/218454396-fb48bc96-99ce-45ec-9026-c33e9f10d8aa.png)
