### ISSUE TITLE
Focused Item Type Move Bug

### ISSUE THREAD

**Issue by NoxCloud** [blackd/Inventory-Profiles#288]
I can't move matching items at once. I don't know when it happened, but it seems to don't work anymore. Also tried it without other mods and only IPN installed

**Comment by blackd** [comment]
mod version? and modloader?

are you using the gui buttons or keyboard?

**Comment by NoxCloud** [comment]
Fabric
Version 1.9.2
I'm using keyboard

**Comment by blackd** [comment]
can you post your config
it's found at config/inventoryprofilesnext/*.json

**Comment by NoxCloud** [comment]
just the JSON?

**Comment by blackd** [comment]
yes

**Comment by NoxCloud** [comment]
{
    "ModSettings": {
        "sort_order": "ITEM_ID",
        "move_just_refill_modifier": {
            "main": {
                "keys": "SPACE"
            }
        },
        "restock_hotbar": {
            "value": true
        },
        "first_run": false
    },
    "AutoRefillSettings": {
        "disable_for_drop_item": {
            "value": true
        },
        "allow_break_for_non_enchanted": {
            "value": true
        },
        "visual_durability_notification": {
            "value": false
        }
    }
}

**Comment by blackd** [comment]
ok
have you updated any mods before the problem has started?

or do you have conflicting keyboard binds with other mods

**Comment by NoxCloud** [comment]
not that i know of
only mod ive updated was roughly enough items

**Comment by blackd** [comment]
REI user R may be you need to change it

**Comment by NoxCloud** [comment]
i also use iris, which uses R as well

**Comment by blackd** [comment]
iris shortcut is only active while there is no opened ui

**Comment by NoxCloud** [comment]
basically i want to move focused/same items using ctrl-click, but it wont let me

**Comment by blackd** [comment]
this wasn't in your config?
it's not possible because IPN tries not to override vanilla clicks

**Comment by NoxCloud** [comment]
because i would move all the same items by holding ctrl and clicking said item

**Comment by blackd** [comment]
this is not done by IPN
do by any chance hav InvTweaks Emu for IPN installed also

**Comment by NoxCloud** [comment]
i do not

**Comment by NoxCloud** [comment]
it would highlight the same items and i would be able to move them all by holding ctrl and left clicking it

**Comment by blackd** [comment]
IPN doesn't support left or right click to be part of move/throw shortcuts

however if you have back/forward buttons you can use them or the mid mouse buttons

**Comment by NoxCloud** [comment]
either im just imagining things or i cant explain it correctly

**Comment by blackd** [comment]
OK can you join our discord server so we can communicate more real-time

**Comment by NoxCloud** [comment]
whats the discord link?

**Comment by blackd** [comment]
https://discord.gg/23YCxmveUM

it's in the description of the project

**Comment by NoxCloud** [comment]
thank you
im gonna close this now
