### ISSUE TITLE
[1.19.2] Crashes when entering the world with cyrillic characters

### ISSUE THREAD

**Issue by SDA-31** [blackd/Inventory-Profiles#289]
Minecraft crashes when entering a world called "`Новый мир`".
The entrance to the world without cyrillic characters is successful.
Here is the logs:
[crash-2023-02-21_20.44.30-client.txt](https://github.com/blackd/Inventory-Profiles/files/10796228/crash-2023-02-21_20.44.30-client.txt)
[latest.log](https://github.com/blackd/Inventory-Profiles/files/10796231/latest.log)

**Comment by blackd** [comment]
you need to change your locale to at least en_US.utf8

also is this on a server?

**Comment by SDA-31** [comment]
> you need to change your locale to at least en_US.utf8

No, here's my locale list:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

> also is this on a server?

I haven't checked it yet. Wait 5 minutes please.

**Comment by blackd** [comment]
[20:44:04] [Render thread/INFO]: Default JVM text encoding is: US-ASCII

**Comment by SDA-31** [comment]
> [20:44:04] [Render thread/INFO]: Default JVM text encoding is: US-ASCII

[latest.log](https://github.com/blackd/Inventory-Profiles/files/10796391/latest.log)
[crash-2023-02-21_21.08.08-client.txt](https://github.com/blackd/Inventory-Profiles/files/10796393/crash-2023-02-21_21.08.08-client.txt)

**Comment by SDA-31** [comment]
I've added flag `-Dfile.encoding=UTF-8` in Java arguments. Still not working

**Comment by SDA-31** [comment]
Connection to the server with russian characters was successful

**Comment by blackd** [comment]
I can't reproduce it. I'm also running on Linux 


[cyrilic.webm](https://user-images.githubusercontent.com/333840/220430457-c342d607-1626-4623-b8dd-84d92bcf9cc9.webm)

**Comment by blackd** [comment]
have you tried if removing IPN fixes the problem?

**Comment by SDA-31** [comment]
> have you tried if removing IPN fixes the problem?

Without libIPN mod is not working.
Without Inventory Profiles Next, world launch.

**Comment by SDA-31** [comment]
> I can't reproduce it. I'm also running on Linux

I'll try to run without a mod, except for "Inventory Profiles Next"

**Comment by blackd** [comment]
hmm  what is the filesystem that contains the config folder?

**Comment by SDA-31** [comment]
NTFS

**Comment by blackd** [comment]
ok can you do `cat /proc/mounts` and check the encoding it's mounted with? my guess is you need to mount it with koi-8 or cp1251

**Comment by SDA-31** [comment]
> I'll try to run without a mod, except for "Inventory Profiles Next"

[crash-2023-02-21_21.47.18-client.txt](https://github.com/blackd/Inventory-Profiles/files/10796642/crash-2023-02-21_21.47.18-client.txt)
[latest.log](https://github.com/blackd/Inventory-Profiles/files/10796644/latest.log)




> ok can you do `cat /proc/mounts` and check the encoding it's mounted with? my guess is you need to mount it with koi-8 or cp1251
```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,noexec,relatime,size=10240k,nr_inodes=1961866,mode=755,inode64 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755,inode64 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/nvme0n1p5 / ext4 rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,inode64 0 0
cgroup_root /sys/fs/cgroup tmpfs rw,nosuid,nodev,noexec,relatime,size=10240k,mode=755,inode64 0 0
openrc /sys/fs/cgroup/openrc cgroup rw,nosuid,nodev,noexec,relatime,release_agent=/usr/lib/openrc/sh/cgroup-release-agent.sh,name=openrc 0 0
none /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cpuset /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cpu /sys/fs/cgroup/cpu cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
cpuacct /sys/fs/cgroup/cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
blkio /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
memory /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
devices /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
freezer /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
net_cls /sys/fs/cgroup/net_cls cgroup rw,nosuid,nodev,noexec,relatime,net_cls 0 0
perf_event /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
net_prio /sys/fs/cgroup/net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_prio 0 0
hugetlb /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
pids /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
rdma /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
misc /sys/fs/cgroup/misc cgroup rw,nosuid,nodev,noexec,relatime,misc 0 0
/dev/nvme0n1p4 /boot vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/nvme0n1p6 /home ext4 rw,relatime 0 0
/dev/nvme0n1p7 /opt ext4 rw,relatime 0 0
/dev/nvme0n1p3 /mnt/SDA\040Drive fuseblk rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1573168k,nr_inodes=393292,mode=700,uid=1000,gid=1000,inode64 0 0
portal /run/user/1000/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
PrismLauncher-Linux-6.3-x86_64.AppImage /tmp/.mount_PrismLGRMLuA fuse.PrismLauncher-Linux-6.3-x86_64.AppImage ro,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
```

**Comment by blackd** [comment]
what distro are you using

**Comment by blackd** [comment]
also may be we should continue the conversation on discord it will be much easier

**Comment by SDA-31** [comment]
> what distro are you using

Artix Linux

**Comment by SDA-31** [comment]
> also may be we should continue the conversation on discord it will be much easier

Ok

**Comment by blackd** [comment]
the flatpack sets the locale to US-ASCII and forces java do refuse non ascii file names
