### ISSUE TITLE
Incompatibility issue

### ISSUE THREAD

**Issue by PenguinTech-official** [blackd/Inventory-Profiles#290]
Inventory profiles next have an incompatible issue in my mod pack. Which mods are incompatible with inventory profiles next

**Comment by blackd** [comment]
most other inventory management mods will interfere with IPN

But may be you should start with describing what problems are you facing.

**Comment by blackd** [comment]
this issue will soon be closed due to lack of engagement from OP

**Comment by PenguinTech-official** [comment]
Sorry I'm a little bit busy.
The issue is when i start my custom modpack with inventory profiles installed I got an error like some mods are incompatible.when I remove IPN and start the modpack it will start with no error.
Ihave installed tetra is it incompatible with inventory profiles next

**Comment by blackd** [comment]
so you have a custom mod pack that I have no access to

and some how expect me to be able to guess what the problem is?

please provide more information like the errors you see and logs.

how do you expect me to help you with no information whatsoever?

**Comment by PenguinTech-official** [comment]
I've managed to fix it.
It's because of incompatiblity with some mods in my modpack

**Comment by blackd** [comment]
I'm glad you were able to fix the problem.

Still providing information what was it and list with incompatible mod will probably help if someone else has similar problems.

**Comment by PenguinTech-official** [comment]
I copied all mods from my modpack to a new one it fixed the issue.
I think the issue was made by some old configs in directory.
