### ISSUE TITLE
[Suggestion] Add the ability for profiles to manage inventory too.

### ISSUE THREAD

**Issue by SzczurekYT** [blackd/Inventory-Profiles#291]
Hello
In the current state profiles control only the hotbar and the armor. But it would be cool if they could also control the inventory. So that you can keep your inventory organised with profiles. It would be cool if there's was an option to don't sort the slots controlled by a profile.
For exmaple I have this inventory:
![image](https://user-images.githubusercontent.com/67533827/221420169-8e628886-dfa3-47ae-bd42-2c25c5b70414.png)
and I would like to have an ability to quickly put my potions and arrows in place, and keep them there when sorting the inventory without locking all these slots.
Thanks

**Comment by blackd** [comment]
this has been coming up from time to time.
there are some technical reason that makes the support of the inventory quite complicated.
So for now there are plans to implement something like this.
