### ISSUE TITLE
[1.16.5] shift + drag moving unwanted items

### ISSUE THREAD

**Issue by joinmod** [blackd/Inventory-Profiles#295]
modpack: age of fate 1.6.7
how i can fix that?

https://user-images.githubusercontent.com/23500905/222960479-62553ef2-001b-4c51-909f-472160da4bde.mp4

**Comment by blackd** [comment]
which version of the mod minecraft and what operating system?

**Comment by joinmod** [comment]
os: windows 11 22h2
inventory profile next: forge 1.9.2

**Comment by blackd** [comment]
I will need the list of mods

but if you have other inventory management mods like mouse tweaks try disabling them

**Comment by joinmod** [comment]
https://www.curseforge.com/minecraft/modpacks/age-of-fate/relations/dependencies

mods which can change inventory system: mouse tweaks 2.14
crafting tweaks 12.2.1
inventoryEssentials 2.3.2
i'll try without them

**Comment by blackd** [comment]
both mouse tweaks and inventory essentials can interfere with IPN
try disabling them to test if the issue persist

**Comment by joinmod** [comment]
and its keep happening

**Comment by joinmod** [comment]
i cant do continous move with focused items but items 2 row below keep continues move
something still breaks inventory system

**Comment by blackd** [comment]
can you try disabling IPN and enable the rest and test again

**Comment by joinmod** [comment]
i am aready did that and this is reason why i openned an issue here

**Comment by joinmod** [comment]
ok i found problem it occurs at tinkers contruct with own crafting station and mayby own inventory? (smeltery has dynamic inventory) about storge not sure
mod list:
forge 36.2.39
mantle 1.6.157
tconstruct 3.3.4.335
ipn 1.9.2
libipn forge 2.0.2
kotlinforforge 1.17.0-obf

**Comment by blackd** [comment]
at the moment I can't investigate further
I'll have time probably tomorrow

**Comment by blackd** [comment]
what are the tabs on the top as in are they provided by separate mod or by tconstruct

**Comment by blackd** [comment]
ok so it seems the problem is caused by TinkersConstructs having the tabs count as part of the crafting gui. Which they solved in 1.18.2 were the problem doesn't happen.

**Comment by blackd** [comment]
unfortunately what ever I try to mitigate the effect of the strange TC behaviour just breaks the rest of the UIs.
So I'll have to leave this as is.
