### ISSUE TITLE
Add "Always Include Hotbar" option for mouse wheel scrolling

### ISSUE THREAD

**Issue by DanClypse** [blackd/Inventory-Profiles#296]
Currently, to perform any operations on the hotbar, the player needs to either hold the ALT button or enable the **Always Include Hotbar** option under Mod settings.

This option simulates holding the ALT button correctly when shift clicking to send a whole stack and swipe moving items. However, mouse wheel behavior does not change.

Video showcasing the issue:
https://user-images.githubusercontent.com/106415755/222999161-325c66c9-cd7b-4ce0-acc4-3369d89fea0f.mp4

**Comment by blackd** [comment]
released in 1.9.6
