### ISSUE TITLE
Crash on 1.19.2 Fabric

### ISSUE THREAD

**Issue by pokesmells** [blackd/Inventory-Profiles#297]
Mod Version: InventoryProfilesNext-fabric-1.19-1.9.2
Mod Loader: Fabric 0.14.17
Launcher: Curseforge

Hi I experienced a crash when going through any type of GUI, this happens randomly when opening GUI's at all!
https://mclo.gs/XxrrIbh - Crash Logs

This will automatically close my game and make it do "Saving World" and close it out.

**Comment by blackd** [comment]
I will need list of all mods

**Comment by pokesmells** [comment]
ad_astra: Ad Astra 1.12.4
		additionalstructures: Additional Structures 4.1.1
		adorn: Adorn 3.8.1+1.19.2
		advancementplaques: Advancement Plaques 1.4.6
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.17
		ae2: Applied Energistics 2 12.9.2
		ae2additions: AEAdditions 4.0.0-fabric
		ae2wtlib: AE2WTLib 12.8.5
		airhop: Air Hop 4.2.1
		alloy_forgery: Alloy Forgery 2.0.19+1.19
		alternate-current: Alternate Current 1.5.0
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		another_furniture: Another Furniture 2.1.2-1.19.2
		appbot: Applied Botanics 1.4.2
		appleskin: AppleSkin 2.4.1+mc1.19
		arcanus: Arcanus 1.30
		architectury: Architectury 6.5.69
		artifacts: Artifacts 7.1.1+fabric
		attributefix: AttributeFix 17.1.3
		authme: Auth Me 4.2.0
	        autotag: AutoTag 2.0.0+1.19
		auudio: Auudio 1.0.3
		backslot: BackSlot 1.2.11
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.6
		basicshields: Basic Shields [Fabric] 1.4.0-1.19.2
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.6
		besmirchment: Besmirchment 1.19-8
		betteradvancements: Better Advancements **.**.**.**
		betteranimalsplus: Better Animals Plus 1.19.2-11.0.10
		betteranimationscollection: Better Animations Collection 4.0.5
		bettercombat: Better Combat 1.6.1+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.4
		betterfpsdist: Better FPS distance Mod 1.19-2.4
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		bettermounthud: Better Mount HUD 1.2.0
		betternether: Better Nether 7.1.3
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 2.3+1.19.2
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthirdperson: Better Third Person 1.9.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bewitchment: Bewitchment 1.19-6
		biomemakeover: Biome Makeover 1.19.2-1.6.2
		blur: Blur (Fabric) 2.6.0
		boatbreakfix: Boat Break Fix 1.0.11
		boatiview: Boat Item View Fabric 0.0.4
		bookshelf: Bookshelf 16.2.17
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
		botania: Botania 1.19.2-438-FABRIC
		botanypots: BotanyPots 9.0.27
		botanytrees: BotanyTrees 5.0.4
		botarium: Botarium 1.8.2
		bwncr: Bad Wither No Cookie Reloaded 3.14.1
		bwplus: Bewitchment Plus 1.19-9
		byg: Oh The Biomes You'll Go **.**.**.**
		cardinal-components: Cardinal Components API 5.0.2
		carryon: Carry On **.**.**.**
		catwalksinc: Catwalks Inc. 1.3.1
		charm: Charm 4.4.4
		charmonium: Charmonium 4.2.1
		chat_heads: Chat Heads 0.10.5
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		chiselsandbits: chisels-and-bits 1.3.129
		citresewn: CIT Resewn 1.1.2+1.19.2
		cloth-api: Cloth API 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		clumps: Clumps 9.0.0+14
		collective: Collective 6.49
		combatroll: Combat Roll 1.1.4+1.19
		computercraft: CC: Restitched 1.101.2
		conjuring: Conjuring 1.0.26+1.19
		connectivity: Connectivity Mod 1.19.2-3.8
		controlling: Controlling For Fabric 10.0+7
		cookingforblockheads: Cooking for Blockheads 13.3.1
		coralreef: Coral Reef 1.19-1.0.2
		crawl: Crawl 0.11.1
		create: Create 0.5.0.i-961+1.19.2
		createaddition: Create Crafts & Additions 20230211a
		creativecore: CreativeCore (Fabric) 2.9.3
		creaturesfromthesnow: Creatures from The Snow 4.1.0+1.19.2
		creeperoverhaul: Creeper Overhaul 2.0.8
		croptopia: Croptopia 2.2.2
		ctov: ChoiceTheorem's Overhauled Villages 3.1.7
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
		darkness: True Darkness 2.0.101
		dataattributes: Data Attributes 1.4.2
		debugify: Debugify 2.8.0
		decorative_blocks: Decorative Blocks 3.0.0
		deeperdarker: Deeper and Darker 1.1.6
		dehydration: Dehydration 1.3.3
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		doom: Doom Fabric 4.2.28
		dragonfight: Dragonfight Mod 1.19.2-2.7
		dragonloot: DragonLoot 1.1.2
		drippyloadingscreen: Drippy Loading Screen 2.1.1
		duckling: Duckling 2.0.8
		dummmmmmy: MmmMmmMmmMmm 1.19.2-1.7.1
		dungeon_difficulty: Dungeon Difficulty 2.0.1+1.19
		dungeons_arise: When Dungeons Arise 2.1.54
		easyanvils: Easy Anvils 4.0.6
		easymagic: Easy Magic 4.3.3
		eatinganimationid: Eating Animation 1.9.1
		ecologics: Ecologics 2.1.11
		effective: Effective 1.4
		eldritch_mobs: EldritchMobs 1.12.104.18+1.19.2
		elytraslot: Elytra Slot 6.1.0+1.19.2
		emojiful: Emojiful 4.0.4
		emotecraft: Emotecraft 2.2.5
		enchantinginfuser: Enchanting Infuser 4.2.2
		enchdesc: EnchantmentDescriptions 13.0.14
		endgoblintraders: End Goblin Traders 1.5.1
		endrem: End Remastered 5.2.0
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.9
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		enviromats: Environmental Materials 1.19-2.1.1.0
		environmentz: EnvironmentZ 1.3.5
		equipmentcompare: Equipment Compare 1.3.1
		essential_commands: Essential Commands 0.30.0-mc1.19.2
		expandeddelight: Expanded Delight **.**.**.**
		experiencebugfix: Experience Bug Fix 19
		explorify-fabric: Explorify 1.19-1.3.0
		extraalchemy: Extra Alchemy 1.9.0
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
		fabric-api: Fabric API 0.75.1+1.19.2
		fabric-furnaces: Fabric Furnaces 2.2.0-1.19.2
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
		fabricloader: Fabric Loader 0.14.17
		fabricshieldlib: Fabric Shield Lib 1.6.1-lite-1.19
		fancymenu: FancyMenu 2.13.3
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersknives: Farmer's Knives 2.4
		farmingforblockheads: Farming for Blockheads 11.2.0
		farsight: Farsight Mod 1.19-2.4
		fastfurnace: FastFurnace 1.19.2-5
		fastload: Fast Load 2.6.11
		faux-custom-entity-data: Faux-Custom-Entity-Data 2.0.2
		ferritecore: FerriteCore 5.0.3
		fmextension_audio: FancyMenu Audio Extension 1.1.1
		forgeconfigapiport: Forge Config API Port 4.2.11
		fpsreducer: FPS Reducer 1.19.2-2.1
		frame: Frame 0.26.1+1.19-fabric
		ftbchunks: FTB Chunks 1902.3.15-build.233
		ftblibrary: FTB Library 1902.3.14-build.184
		ftbquests: FTB Quests 1902.4.9-build.195
		ftbteams: FTB Teams 1902.2.12-build.95
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		galosphere: Galosphere 1.19.2-1.2.2
		geckolib3: Geckolib 3.1.40
		geophilic-fabric: Geophilic 1.19-1.2.1
		go-fish: Go Fish 1.6.0-1.19.1
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 2.3
		graveyard_biomes: The Graveyard Biomes 1.6
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		handcrafted: Handcrafted 2.0.2
		harvestwithease: Harvest with ease **.**.**.**
		healingcampfire: Healing Campfire 5.1
		highlighter: Highlighter 1.1.4
		icarus: Icarus 1.13
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.11
		immediatelyfast: ImmediatelyFast 1.1.9
		immersive_armors: Immersive Armors 1.5.4+1.19.2
		immersive_weathering: Immersive Weathering 1.19.2-1.2.8
		imst: Immersive structures 2.0.7
		incantationem: Incantationem 1.1.6+1.19
		indium: Indium 1.0.9+mc1.19.2
		indrev: Industrial Revolution 1.15.1-BETA
		ingredient-extension-api: Ingredient Extension API 3.0.6
		interactic: Interactic 0.1.11+1.19
		inventoryhud: Inventory HUD + 3.4.7
		inventoryprofilesnext: Inventory Profiles Next 1.9.2
		iris: Iris 1.5.2
		ironchests: Iron Chests: Restocked 3.1.1
		itemfilters: Item Filters 1902.2.9-build.46
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 17
		jecalculation: Just Enough Calculation 4.0.2
		jmi: JourneyMapIntegration 0.13-30
		journeymap: Journeymap 5.9.3
		kambrik: Kambrik 4.0-1.19.2
		kleeslabs: KleeSlabs 12.1.0
		konkrete: Konkrete 1.6.0
		krypton: Krypton 0.2.1
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
		languagereload: Language Reload 1.5.4+1.19.2
		lazydfu: LazyDFU 0.1.3
		leavesbegone: Leaves Be Gone 4.0.1
		legendarytooltips: Legendary Tooltips 1.3.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		libipn: libIPN 2.0.2
		lithium: Lithium 0.10.4
		logbegone: Log Begone 1.0.4
		lootr: Lootr **.**.**.**
		luggage: Luggage 1.19-1.5.2
		mapfrontiers: MapFrontiers 2.4.0-fabric
		mca: Minecraft Comes Alive 7.4.7+1.19.2
		mcda: MC Dungeons Armors 2.4.4
		mcdar: MC Dungeons Artifacts 1.5.3-1.19
		mcdw: MC Dungeons Weapons 5.0.5-1.19
		mcwbridges: Macaw's Bridges 1.0.6
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.8
		mcwwindows: Macaw's Windows 2.1.2
		megacells: MEGA Cells 1.5.3-1.19.2
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		merchantmarkers: Merchant Markers 1.2.3
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
		mixintrace: MixinTrace 1.1.1+1.17
		mo_glass: Mo Glass 1.6.1-MC1.19.2
		mobhealthbar: MobHealthBar 2.1.0
		modern_industrialization: Modern Industrialization 1.6.3
		moderndynamics: Modern Dynamics 0.3.4-beta
		modmenu: Mod Menu 4.1.2
		moonlight: Moonlight 1.19.2-2.2.13
		more_babies: More Babies 1.0.0
		moreculling: More Culling 1.19.1-0.16.0
		mousetweaks: Mouse Tweaks 2.22
		musicplayer: Music Player **.**.**.**
		mvs: Vanilla Structure Mod 2.5.10-1.19.2
		mythicmetals: Mythic Metals 0.17.2+1.19.2
		mythicmounts: Mythic Mounts 1.19.2-7.1
		nameplate: Nameplate 1.0.10
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		nears: Nears 1.2.3
		netherportalfix: NetherPortalFix 10.0.1
		nethersdelight: Nether's Delight 1.0.1
		nnvf: No Night Vision Flickering 0.1.1
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		notreepunching: No Tree Punching 6.0.0
		origins: Origins 1.7.1
		origins-classes: Origins: Classes 1.4.0
		origins-plus-plus: Origins++ 2.0
		owo: oωo 0.9.3+1.19
		paradise_lost: Paradise Lost 2.1.0-beta+1.19.2
		patchouli: Patchouli 1.19.2-77-FABRIC
		paxi: Paxi 1.19.2-Fabric-3.0.1
		pehkui: Pehkui 3.7.0+1.14.4-1.19.3
		pfm: Paladin's Furniture 1.1.1
		philipsruins: Philip`s ruins 1.19.2
		pickupnotifier: Pick Up Notifier 4.2.4
		ping-wheel: Ping Wheel 1.2.0
		player-animator: Player Animator 1.0.2
		playerex: PlayerEx 3.5.2
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.46.1+1.19.2
		powah: Powah! 4.0.6
		presencefootsteps: Presence Footsteps 1.6.4
		prism: Prism 1.0.3
		probablychests: Probably Chests 0.5.5-1.19.2
		projectile_damage: Projectile Damage Attribute 3.0.0+1.19
		puzzle: Puzzle 1.4.2-1.19
		puzzleslib: Puzzles Lib 4.3.12
		quartzelv: Quartz Elevator 2.1.5+1.19
		reborncore: Reborn Core 5.4.0
		redmorestructure: Reds More Structures 1.0.6-fabric-1.19.2
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		relicex: RelicEx 3.3.0+1.19.2
		repurposed_structures: Repurposed Structures 6.3.16+1.19.2
		resourcefulconfig: Resourcefulconfig 1.0.19
		resourcefullib: Resourceful Lib 1.1.22
		rocks: This Rocks! 1.6.1
		rottencreatures: Rotten Creatures 1.0.1
		roughly_enough_trades: Roughly Enough Trades 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.591
		roughlyenoughprofessions: Roughly Enough Professions 1.1.3
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		rpgdifficulty: Rpg Difficulty 1.3.5
		runes: Runes 0.9.4+1.19
		scout: Scout 1.1.2
		sdrp: Simple Discord Rich Presence 3.0.4-build.27+mc1.19.2
		simplehats: SimpleHats 1.19.2-0.1.6
		simply_houses: Simply Houses 1.1.3-1.19
		simplyswords: Simply Swords 1.43.1-1.19.2
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		skyvillages: Sky Villages **.**.**.**
		smarterfarmers: Smarter Farmers 1.19.2-1.7.1
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
		soulsweapons: Marium's Soulslike Weaponry 0.9.8
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spell_engine: Spell Engine 0.9.14+1.19
		spell_power: Spell Power Attribute 0.9.7+1.19
		spellbladenext: Spellblade Next **.**.**.**.hotfix1
		spirit: Spirit 2.2.3
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit: Starter Kit 5.2
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		structory_towers: Structory: Towers 1.0.0
		supplementaries: Supplementaries 1.19.2-2.2.54
		t_and_t: Towns and Towers 1.9
		takesapillage: Takes a Pillage 1.0.4
		talkbubbles: Talk Bubbles 1.0.4
		techreborn: Tech Reborn 5.4.0
		tenshilib: TenshiLib 1.19.2-1.6.15
		terrablender: TerraBlender **.**.**.**
		terracart: Terracart Reloaded 1.4.0
		terrarianslimes: Terrarian Slimes 1.3.1-BETA+1.19
		terrestria: Terrestria 5.0.8
		the_bumblezone: The Bumblezone - Fabric 6.6.17+1.19.2
		things: Things 0.3.0+1.19
		thonkutil: ThonkUtil 2.15.4+1.19
		tiered: Tiered 1.2.2
		tipsmod: Tips 8.0.27
		tlc: The Lost Castle 1.0.0
		toolstats: ToolStats 12.0.2
		totw_additions: Towers of the Wild: Additions 1.2.4
		transparent: Transparent 5.1.2
		trashslot: TrashSlot 12.0.2
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.13
		treechop: HT's TreeChop 0.17.6
		trinkets: Trinkets 3.4.2
		tumbleweed: Tumbleweed 0.5.1
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		twilightforest: The Twilight Forest 4.2.335
		unsafe-world-random-access-detector: Unsafe World Random Access Detector 1.1.0
		uteamcore: U Team Core **.**.**.**
		valkyrielib: ValkyrieLib 1.19-4.0.1.1
		veinmining: Vein Mining 1.0.2+1.19.2
		villagernames: Villager Names 5.2
		visuality: Visuality 0.5.6
		visualworkbench: Visual Workbench 4.2.3
		voicechat: Simple Voice Chat 1.19.2-2.3.28
		voidtotem: Void Totem 2.1.0
		wabi_sabi_structures: Wabi-Sabi Structures 1.1.2
		waveycapes: WaveyCapes 1.3.2
		whisperwoods: Whisperwoods 1.19-2.1.1
		windchimes: Windchimes 1.2.1
		wizardex: WizardEx 1.0.1
		wizards: Wizards 0.9.11+1.19
		wmitaf: WMITAF 3.1.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
		woof: Woof 3.0.0-1.19
		xlpackets: XLPackets 1.19.2-4
		xps: Xp Obelisk 0.4.7-r+1.19.2-Fabric
		xps_additions: XP Obelisk Additions 0.1.8-r+1.19.2-Fabric
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.8
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.8
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
		zoomify: Zoomify 2.9.0

**Comment by pokesmells** [comment]
I am so sorry I have a lot of mods :(

**Comment by blackd** [comment]
I think there is a way to export a modpack from curseforge launcher. This will make it so much easier 😂

**Comment by pokesmells** [comment]
[ALBOE-d.zip](https://github.com/blackd/Inventory-Profiles/files/10895327/ALBOE-d.zip)

**Comment by blackd** [comment]
well the jvm crashes with your modpack :) 
anyway can you try with the attached versions of my mods

[zzzz.zip](https://github.com/blackd/Inventory-Profiles/files/10898305/zzzz.zip)

**Comment by pokesmells** [comment]
BRUH LMAO Alrighty tested it and legit smashed all the combos I could think of and opened multiple GUI's, and nothing happened

**Comment by pokesmells** [comment]
> well the jvm crashes with your modpack :) anyway can you try with the attached versions of my mods
> 
> [zzzz.zip](https://github.com/blackd/Inventory-Profiles/files/10898305/zzzz.zip)

I hope you mean with the crash 😭 and not my pack in general...

**Comment by blackd** [comment]
your modpack in general

**Comment by blackd** [comment]
so I'll consider this fixed 
it will be officially  out in few days

**Comment by pokesmells** [comment]
> your modpack in general

dang any tips before this gets closed later on? and thank you for the help I greatly appreciate it

**Comment by blackd** [comment]
about the modpack? 
I have no idea I don't do modpacks. But it looks they are harder then just putting a bunch of mods in the mod folder... well at least my knowledge limited to that
