### ISSUE TITLE
1.19.2 Pickup to inventory behavior conflicts with Create Toolboxes

### ISSUE THREAD

**Issue by Ari-Elle-0237** [blackd/Inventory-Profiles#298]
Whenever you select an item from the toolbox, this mod moves it out of your hotbar anyways, dumping the entire contents out into it as a result, and there appears to be no config setting to disable this.

**Comment by blackd** [comment]
locked slots page of the settings
![image-3.png](https://user-images.githubusercontent.com/333840/223593025-6a50d68e-c07a-4365-9928-efd90a56244d.png)

**Comment by Ari-Elle-0237** [comment]
My apologies, I must be blind lol, I read over it like 5 times to try to make sure I wasn't doing what I just did. 

Regardless though, it'd still be convenient if there was a way to make that behavior work with the toolbox

**Comment by blackd** [comment]
being client side comes with some limitations. like it's almost impossible to reliably detect why something popped up in the hotbar or in the inventory.

My guess is that Create handles stuff server side so integration between the mods would be impossible.

**Comment by Ari-Elle-0237** [comment]
Ah shame, I can live with it though. Thanks for the quick reply though!
