### ISSUE TITLE
Profiles seem to be unable to support any NBT data except for enchantments and potion id

### ISSUE THREAD

**Issue by Ari-Elle-0237** [blackd/Inventory-Profiles#299]
Based on the error message I assume this is known, but I couldn't find an issue here that brought it up, and I'd be curious to know why that is seeing as the enchantments and potions already appear to be in NBT format

Example Line
`
"minecraft:wooden_shovel" -> "Damage" : 1421
`
Error Message upon reload:
`
Loading Profile settings failed: SyntaxErrorException(line=21,pos=31, msg=mismatched input '"Damage"' expecting {'"Enchantments" :', '"Potion" :'})
`

**Comment by blackd** [comment]
yes this is the intended behaviour
