### ISSUE TITLE
Items rendering error

### ISSUE THREAD

**Issue by IceeAlin** [blackd/Inventory-Profiles#3]
Something weird just happened when I was using this mod.
Items looks really ugly. See the picture.
![java exe Screenshot 2021 06 21 - 14 44 16 11](https://user-images.githubusercontent.com/86223973/122721449-41c71380-d2a3-11eb-8dcc-08ffe39a202f.png)

These're all the mod I was using.
![image](https://user-images.githubusercontent.com/86223973/122721976-cdd93b00-d2a3-11eb-8178-6490a55d3a61.png)

**Comment by blackd** [comment]
well i hate automatic stuff :)

**Comment by blackd** [comment]
Can you pleas try to download this build https://tmpfiles.org/58047/dev-build.zip and test it

note: the url will only exist for 120 minutes because of how tmpfiles.org works

**Comment by IceeAlin** [comment]
I've tried. Problem seems to be solved now. Thanks.
![java exe Screenshot 2021 06 21 - 17 46 30 02](https://user-images.githubusercontent.com/86223973/122742563-a6409d80-d2b8-11eb-8640-e71e3f352dfa.png)

**Comment by blackd** [comment]
Fixed in 19c4bfa
