### ISSUE TITLE
java.lang.IllegalStateException: Infinity loop detected. 100001 > 100000

### ISSUE THREAD

**Issue by marie-bnl** [blackd/Inventory-Profiles#30]
It does that when sorting a chest or inventory of enchant books. It always does that to me when the chest is full of books, but also sometimes when it's not

**Game version:** 1.16.5
**Mod version:** 0.8.4
**Mod loader:** Forge

**Comment by blackd** [comment]
This is a protection against situations where sorting takes too long and #27 is the reason if it takes too long
So I'll mark this as duplicate of #27 because

**Comment by marie-bnl** [comment]
_[ImgBot] Optimize images #27_? Didn't you mean another issue? I don't see the link between this issue and #27

**Comment by blackd** [comment]
#29 ....

**Comment by marie-bnl** [comment]
Oh okay no problem 😄
