### ISSUE TITLE
Shift + CapsLock +  Clicking

### ISSUE THREAD

**Issue by keylperez** [blackd/Inventory-Profiles#300]
When  performing Shift + CapsLock + Clicking, after closing the chest gui, keyboard gets locked and you cant perform keyboard actions. Running on 1.19.2 btw. Somestimes when im lucky i redo the action and get unlocked but  im not totally sure  how  it works

**Comment by blackd** [comment]
what other mods do you have?
is it forge of fabric

**Comment by keylperez** [comment]
I use fabric, here is my modpack :D
https://mega.nz/file/azIHRLZb#RVHt9DAxt_XRZCNt_fSyCH1Sg7QVco2SC0psZukEqXM

**Comment by blackd** [comment]
if you don't use the latest mod version please test with it

**Comment by blackd** [comment]
@keylperez have you tested with the latest version of the mod?

**Comment by blackd** [comment]
closing due to lack of interest of OP
