### ISSUE TITLE
Suggestion about sorting buttons.

### ISSUE THREAD

**Issue by KostromDan** [blackd/Inventory-Profiles#301]
At the moment, the mod adds sorting buttons exclusively to the inventory we are working with. This creates a problem, if I opened the chest, then the sort button will be exclusively for the chest inventory, but not for the player's inventory, and if I want to sort the player's inventory during the work with the chest, I will have to exit the chest, enter the inventory, sort the inventory, exit the inventory and return to the chest, I think it is not necessary to say that it is very inconvenient.
How it looks now:
![image](https://user-images.githubusercontent.com/90044015/224553063-cb6089c9-2c04-4df4-9df0-787b0a08dbaf.png)
How it should:
![image](https://user-images.githubusercontent.com/90044015/224553146-f1023605-07b7-4028-bdd7-d7fc7c21b485.png)
Also, if you add this feature, make sure it works with Sophisticated Backpacks and Sophisticated Storage, because other mods, that have this feature don't display sorting buttons in players inventory while working working with Sophisticated mods. But show in vanilla storages. Same thing with Mekanism.

**Comment by blackd** [comment]
To be honest I don't really want to introduce additional GUI elements.
If you can switch to hotkey sorting you can make the mod sort the inventory that is under the mouse cursor.

**Comment by KostromDan** [comment]
"you can make the mod sort the inventory that is under the mouse cursor" - sounds interesting, I've tried it. I have locked the mouse wheel and it sorts only the barrel inventory, even if the mouse cursor is in the player's inventory area. I have disabled all other binds from other sorting mods. What am I doing wrong?
![image](https://user-images.githubusercontent.com/90044015/224559656-b124857b-39e0-40bd-a78f-417f8bced7aa.png)

**Comment by blackd** [comment]
there is an option in the Mod Settings that enable this.

I was set to false in the original mod before it was abandoned and I never got around to set it to true by default. I will do that in the next release.

**Comment by KostromDan** [comment]
Now it works, thanks, but I would suggest that you think about the buttons, since not everyone knows how to use keyboard shortcuts and just use the mod as it is without additional settings.

**Comment by ejm554** [comment]
> To be honest I don't really want to introduce additional GUI elements.

I started using this mod about a month ago, and the main UX frustration I have is that I cannot sort my inventory with the standard button unless I go to the inventory view. The requires me to leave my current view, open my inventory, click the sort button, and then return to my previous view. 

I decided to post this issue today, and I found that @KostromDan raised this same issue about a year ago. However, @blackd wasn't persuaded. 

In case they (or one of the other contributors) are open to re-considering their stance, I'd like to advocate for the elegance of a button. As a user, having the same inventory-sort button on different screens seems _intuitive_. Also, I'm not a power user of this mod, so I'd also prefer not to tinker with hotkey settings. 

<img width="1098" alt="Three screenshots, arranged horizontally, of an inventory view, a chest view, and a crafting table view, respectively." src="https://github.com/user-attachments/assets/c42b7818-546e-40bb-a1e1-bad540550d09">

**Comment by blackd** [comment]
the default shortcut for sort is "R" and it works for the inventory under the mouse cursor.
I prefer not to add new buttons because of the numerous  problems with modded GUIs

**Comment by blackd** [comment]
I've decided to add another set of buttons 

![image](https://github.com/user-attachments/assets/560edbf3-fea3-48ea-b534-5747235fa645)

but they will be disabled by default

![image](https://github.com/user-attachments/assets/da3523c6-d31a-4d3a-be28-9e88bb897bf7)


This will be available in the next 1.21+ release

**Comment by ejm554** [comment]
- Thanks for adding this option.
- Thanks for the tip about the "R" default shortcut.
- Will this new feature work with 1.20.6 also?
- What are those purple arrows shown at the bottom of one of your recent screenshots? ↴
<img width="889" alt="Bottom row of a Minecraft inventory screen that includes some non-Vanilla purple arrows in the upper left of each cell" src="https://github.com/user-attachments/assets/e3bed6cb-60f5-4209-90e7-313705853cf3">

**Comment by blackd** [comment]
no 1.20.6

in the latest version it's possible to enable auto refill per slot the arrows show if it's enabled or not
