### ISSUE TITLE
Can’t change inventory gui buttons with resource pack

### ISSUE THREAD

**Issue by PoggChamp** [blackd/Inventory-Profiles#302]
I tried to change the inventory gui buttons (sort, move all, etc.) using a resource pack and nothing has changed. I edited the gui_buttons.png and gui_buttons_new files located in the mod files and put them under (PACK)/assets/inventoryprofilesnext/textures/gui and nothing has changed with the buttons. Is there something I’m doing wrong?

**Comment by blackd** [comment]
this resource pack has support for IPN textures may be check how they did it
https://www.curseforge.com/minecraft/texture-packs/dracula-theme/files/3956729

**Comment by blackd** [comment]
I also made a simple example that works  [ipn.zip](https://github.com/blackd/Inventory-Profiles/files/11056422/ipn.zip)
