### ISSUE TITLE
Where is option ?

### ISSUE THREAD

**Issue by gragonfire242002** [blackd/Inventory-Profiles#305]
I can't find the option to disable 1 or 2 click item transfers outside of inventory

**Comment by blackd** [comment]
can you elaborate? I can't quite understand what problem are you having.

is it scroll wheel related?

**Comment by gragonfire242002** [comment]
items in my inventory move to chests when I click outside of inventory

**Comment by blackd** [comment]
this is not done by this mod

check if you also have
mouse wheelie
item scroller
mouse tweaks

or other inventory management mods and remove all that  you don't want to use

**Comment by blackd** [comment]
if you don't have such mods

r+c opens the settings check the hotkey page if you have set something to mouse click only

**Comment by gragonfire242002** [comment]
oh sorry for the inconvenience the problem came from the server
