### ISSUE TITLE
java.lang.IllegalStateException: Infinity loop detected. 100001 > 100000

### ISSUE THREAD

**Issue by XxPaldo88xX** [blackd/Inventory-Profiles#309]
Error occurs when using Fabric Carpet "stackableShulkerBoxes" rule, which allows empty shulker boxes to stack to 64.
Is there any way to solve it?

Client: Fabric, 1.19.3

**Comment by blackd** [comment]
which version of the mod

**Comment by XxPaldo88xX** [comment]
InventoryProfilesNext-fabric-1.19.3-1.9.4

**Comment by blackd** [comment]
fixed in 5422359c9604d7d3550e0ad2e0d5e9b3459cb752
