### ISSUE TITLE
How to disable new item auto jump to inventory ?

### ISSUE THREAD

**Issue by ItsukaHiro** [blackd/Inventory-Profiles#313]
It's not a actual issue (or it's really, idk) but new item always jump directly to inventory (not to hand / hotbar). And it's make a huge problem for me. So is there anyway to disable this ?

**Comment by blackd** [comment]
join our discord https://discord.gg/23YCxmveUM

and click this link https://discord.com/channels/861171785897738240/861178646478585876/1080336838448910427

**Comment by ajaxnotmeta** [comment]
![image](https://github.com/blackd/Inventory-Profiles/assets/135541817/88446391-58c2-4246-96ea-dd8c15b44c7f)
For someone who had their discord already capped 100 servers and cant leave one of them

**Comment by blackd** [comment]
please stop spamming closed issues.
