### ISSUE TITLE
Mouse tweaks incompatibility.

### ISSUE THREAD

**Issue by KostromDan** [blackd/Inventory-Profiles#314]
If defalt layer will install theese mods together, inv scrolling will double.
Also this mod doest work with scrolling in crafting table.

**Comment by blackd** [comment]
And what do you expect me to do about mouse tweaks?

please report separate issue about the crafting table.

**Comment by KostromDan** [comment]
Mouse tweaks and your mod are very popular and can be installed by a wide range of people, including those who do not fumble in the configuration. Therefore, it would be nice to implement compatibility out of the box. OK, I'll write down more details about the crafting table.

**Comment by blackd** [comment]
did you suggest the same thing to mouse tweaks?

**Comment by KostromDan** [comment]
No, but i can write.
