### ISSUE TITLE
[Suggestion] Have a position preset for buttons when Minecraft window is maximized / not maximized

### ISSUE THREAD

**Issue by aisukuma** [blackd/Inventory-Profiles#315]
When moving the GUI buttons to different parts of the screen, the positions of the buttons also move when you switch the window from maximized to the original window size.

IPN GUI not maximized and no buttons moved:
![2023-04-05_14 30 46](https://user-images.githubusercontent.com/22802219/230173472-ff6ae261-15b8-4592-9acb-6539a598ee0e.png)

IPN GUI maximized with a button moved:
![2023-04-05_14 31 08](https://user-images.githubusercontent.com/22802219/230173495-ace85359-7db2-40c0-97f1-46ab48742c54.png)

IPN GUI not maximized with a button moved from the maximized window state:
![2023-04-05_14 31 14](https://user-images.githubusercontent.com/22802219/230173598-c0f62848-b2b6-4ff6-922b-9673b39fecbe.png)

**Comment by blackd** [comment]
the 2 top left buttons position is relative to the 0,0 coordinates of the screen.
in contrast the other buttons positions are relative to the 0,0 of the shown window.
this is why there is discrepancy when the scaling changes. 

I'm not sure if I can do something about that

**Comment by blackd** [comment]
at this point I won't adding such functionality
