### ISSUE TITLE
Can't scroll items from crafting table.

### ISSUE THREAD

**Issue by KostromDan** [blackd/Inventory-Profiles#316]
If we will try to scroll items from crafting table, as from chest, nothing happens.
It's clear installation, no cfg chages, only IPN installed.
![image](https://user-images.githubusercontent.com/90044015/230190466-f9e01888-f314-48eb-a120-023fe5f71ac3.png)
How this feature works in mouse tweaks:
https://user-images.githubusercontent.com/90044015/230192820-41c976a0-b7d4-4323-a51a-718fd40eecc5.mp4

**Comment by blackd** [comment]
works as intended
