### ISSUE TITLE
Feature request: auto sort

### ISSUE THREAD

**Issue by marie-bnl** [blackd/Inventory-Profiles#32]
A great feature would be to automatically sort the chest/inventory on some events like

- Open
- Modify (put, remove or move items)
- Close

To always keep my chests sorted without breaking my R key

**Comment by blackd** [comment]
Duplicate of #23.

Long story short.. it breaks things like stack management.

**Comment by marie-bnl** [comment]
Ooops sorry I didn't see #23, thanks for your answer anyway
