### ISSUE TITLE
Game crashed - chest opening 

### ISSUE THREAD

**Issue by Tilouux** [blackd/Inventory-Profiles#322]
My game crashed few seconds after i open chests, dont know how to fix that

here's my crash report :

https://mcpaste.io/8d80cd09aea84da3

**Comment by blackd** [comment]
First update to the latest version.

then attach the new logs if any to the issue ot make a gist.

include information which modpack is this.

And detailed information how to reproduce it.

**Comment by blackd** [comment]
probably fixed with 73005ea4b75b2f8488d3d5dedbf858104467fb93

if not reopen
