### ISSUE TITLE
Chest dumping bug.

### ISSUE THREAD

**Issue by Godwhitelight** [blackd/Inventory-Profiles#323]
Chest dumping not working.
the chest throws all is not working. I need to move all the items into my inventory and then drop them with that drop-all key bind.

**Comment by blackd** [comment]
Can you provide 

which minecraft version
mod version
mod loader

and list of all other mods

**Comment by Godwhitelight** [comment]
Minecraft version 1.19.4
Mod loader: fabric
Mod Version: latest 1.9.5
Mods:
Client Commands
Controlling fabric
Entity culling
fabric api 0.76.0
fabric feather latest
iris
sodium
and starlight

**Comment by blackd** [comment]
and also your config files

the content of config/inventoryprofilesnext folder

**Comment by blackd** [comment]
closing due to lack of interest by OP
