### ISSUE TITLE
Crash with clientcommands - LockedSlotKeeper assumes container doesn't change

### ISSUE THREAD

**Issue by Earthcomputer** [blackd/Inventory-Profiles#324]
Hi, I've looked briefly into a crash reported to clientcommands [here](https://github.com/Earthcomputer/clientcommands/issues/522) and I think there is an issue in `LockedSlotKeeper` where it implicity assumes the container doesn't change by storing some slot ids, although I didn't fully understand what's going on yet. Clientcommands changes the open container when a container GUI is opened [here](https://github.com/Earthcomputer/clientcommands/blob/db861bc0a29b59257d9acafb02f42dab354f1569/src/main/java/net/earthcomputer/clientcommands/command/FindItemCommand.java#L215). I was wondering if you could provide some insight into what's going on?

To reproduce, install clientcommands and inventory profiles next, join a world, place some dirt in a chest, then type `/cfinditem dirt` into chat.

**Comment by blackd** [comment]
Yeah `LockedSlotsKeeper` is a mess I'm trying to make my self clean for a long time.
It should detect if a GUI is open and stop doing any thing until it's closed. But my guess is it happens to fast to be detected.
The assumption is that i works on the normal player inventory which is available even if it's not open.

**Comment by onlinekomodo** [comment]
Oh my lord, the reason for the crashes was the version difference, updating libIPN and Inventory Profiles Next solved the issue
Edit: Welp, maybe not-

**Comment by blackd** [comment]
Well I'm happy it's fixed 😁

I have the new version spam on startup for a reason 🤣

edit Well it sounded too good lol

**Comment by onlinekomodo** [comment]
Yeaaaah, I was kinda afraid that it wasn't going to be easy... do you want to chat on Discord so we're not clogging Github?

**Comment by blackd** [comment]
yeap

**Comment by onlinekomodo** [comment]
Alright
FlameUser706#5060

**Comment by blackd** [comment]
https://discord.gg/23YCxmveUM

**Comment by blackd** [comment]
Soo the cause was pinned down to.... drumroll... 

the server being paper.

**Comment by blackd** [comment]
"Fix/Workaround" will be available in the next release. However 1.19.3 is no longer supported and will not receive the fix.
