### ISSUE TITLE
Crash while loading the world caused by Polish character in the name

### ISSUE THREAD

**Issue by LPDawid** [blackd/Inventory-Profiles#326]
**Crash while loading the world caused by Polish character in the name.**

### Environment
Steam Deck, SteamOS 3.4.6, Prism Launcher 6.3 (flatpak stable), Fabric Loader 0.14.19, Fabric Language Kotlin 1.9.4+1.8.21,
Minecraft 1.19.3, Fabric API 0.76.1, libIPN 2.0.4, Inventory Profiles Next 1.9.5
or
Minecraft 1.19.4, Fabric API 0.79.0, libIPN 2.0.6, Inventory Profiles Next 1.9.6

No other mod, plugin, data pack, shader, resource pack loaded.

### Behaviour
If I rename the world, it loads just fine.
If I disable only IPN itself, world loads just fine.
Polish character does not appear in save folder, only in level.dat.

### Logs
[crash-2023-04-27_18.58.14-client.txt](https://github.com/blackd/Inventory-Profiles/files/11346259/crash-2023-04-27_18.58.14-client.txt)
[latest.log.txt](https://github.com/blackd/Inventory-Profiles/files/11346261/latest.log.txt)

**Comment by blackd** [comment]
let me guess it's an appImage of Prism

**Comment by blackd** [comment]
reported to prism https://github.com/PrismLauncher/PrismLauncher/issues/1041

**Comment by LPDawid** [comment]
> let me guess it's an appImage of Prism

Actually not, it's flatpak

**Comment by blackd** [comment]
Well last time was AppImage

you can try starting it like LC_ALL=en_US.UTF-8 flatpackName
it might help

Any locale will do as long as it's .UTF-8

**Comment by LPDawid** [comment]
> Well last time was AppImage
> 
> you can try starting it like LC_ALL=en_US.UTF-8 flatpackName it might help
> 
> Any locale will do as long as it's .UTF-8

LC_ALL=en_US.UTF-8 fixes it, changing to pl_PL.UTF-8 (my default) crashes again

**Comment by blackd** [comment]
Well I can't really do anything about this.

Try using ATLauncher for example or the tar.gz version of PrismLauncher

I develop the mod on Linux with bg_BG.UTF-8 as default locale so I test with non ascii characters in the world name all the time

**Comment by LPDawid** [comment]
> Well I can't really do anything about this.
> 
> Try using ATLauncher for example or the tar.gz version of PrismLauncher
> 
> I develop the mod on Linux with bg_BG.UTF-8 as default locale so I test with non ascii characters in the world name all the time

Thank you for your help, and don't worry - I added LC_ALL=en_US.UTF-8 to my Prism shortcuts, Polish still works fine in both Prism and MC, so this is sort of fixed. I'm just concerned about other users that will encounter this problem ;)
