### ISSUE TITLE
Items are not picked up in the local game

### ISSUE THREAD

**Issue by PumpkinMai** [blackd/Inventory-Profiles#327]
I apologize in advance I do not know English and use a translator. My friend and I are playing a local game, we both have this mod and everything works, but when he throws me an object, I can't take it and it just lies on the ground. Help this is a mod setup or bug. Thank you very much in advance!

**Comment by blackd** [comment]
Do you have free space in the inventory and/or the hotbar? 

Locked slots don't count.

**Comment by PumpkinMai** [comment]
Yes, even when completely empty

**Comment by blackd** [comment]
what other mods do you have?

And what is the server?

**Comment by PumpkinMai** [comment]
List of mods:
InventoryProfilesNext-forge-1.19.4-1.9.4
kotlinforforge-4.1.0-all-1.19.4
libipn-forge-1.19.4-2.0.6
OptiFine_1.19.4_HD_U_I4

The server is local

**Comment by blackd** [comment]
Can you update Inventory Profiles Next to the latest version.

https://legacy.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4501639

**Comment by PumpkinMai** [comment]
Updated and still the same

**Comment by blackd** [comment]
who is the host of the game
other one the can't pickup items?

**Comment by PumpkinMai** [comment]
My friend is a host, he has the same mods.
We play together and that he and I do not pick up the things that we throw to each other.

**Comment by blackd** [comment]
OK
in the settings Mod Settings page disable locked slots

**Comment by PumpkinMai** [comment]
![image](https://user-images.githubusercontent.com/132100952/235247666-16cee8a6-107e-4173-923f-c89cba550327.png)

https://user-images.githubusercontent.com/132100952/235248595-5a2b4230-389a-4240-a7bc-78fef5240edd.mp4

**Comment by blackd** [comment]
I ment in the first page named Mod Settings


and I guess you both need to do it

**Comment by blackd** [comment]
![image](https://user-images.githubusercontent.com/333840/235249598-b880d6cb-e951-42f2-a894-30574612f75b.png)

**Comment by PumpkinMai** [comment]
We set the same settings all without success

**Comment by blackd** [comment]
OK remove the mod and test if it works

**Comment by blackd** [comment]
closing due to lack of interest by OP
