### ISSUE TITLE
Throw All Items bug

### ISSUE THREAD

**Issue by XxPaldo88xX** [blackd/Inventory-Profiles#329]
### Have you asked for help in discord?

NO

### Minecraft Version/s

1.19.3

### Modloader

Fabric

### Modloader Version

InventoryProfilesNext-fabric-1.19.3-1.9.5

### List of all other installed mods

![image](https://user-images.githubusercontent.com/123759235/237043509-16e580c5-2cc0-4d68-ba50-27aafa2368ca.png)

### Describe the problem

First of all, I would like you to know that I am translating with a translator

Not too long ago, pressing the Throw All Items key on a chest or shulker box threw away all of the contents of the chest, but now only one selected pile is discarded.

Of course, the original settings were not touched

### Steps to reproduce

.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [x] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
the defaut is to throw the items of the type under your mouse cursor.

this can be changed in the settings `Mod Settings` page.

If you need further support please use Discord.

**Comment by blackd** [comment]
if you hold shift while pressing the throw shortcut it  will throw everything

**Comment by XxPaldo88xX** [comment]
i solved it

Enabling Move All Under Cursor deletes all items. :)
