### ISSUE TITLE
Option to allow picked up items to go into hotbar instead of inventory like Vanilla 

### ISSUE THREAD

**Issue by CotOTK** [blackd/Inventory-Profiles#330]
Currently items go straight into the inventory,  I looked and could not find an option to turn that off.  It would be nice to have a toggle to make it work either way depending on the preference of the player.

**Comment by blackd** [comment]
circumventing the template doesn't grant you support questions privileges.

ask on discord

**Comment by CotOTK** [comment]
Wasn't trying to circumvent anything.  Sorry for bothering you.  Won't happen again.

**Comment by ajaxnotmeta** [comment]
![image](https://github.com/blackd/Inventory-Profiles/assets/135541817/2fee78a4-8892-435e-9beb-7432ebeccb9c)
for someone who had their discord already capped 100 servers
