### ISSUE TITLE
NBT Dump displays HT characters for \n

### ISSUE THREAD

**Issue by linuzzx** [blackd/Inventory-Profiles#333]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20

### Modloader

Fabric

### Modloader Version

0.14.21

### Operating System

Windows

### List of all other installed mods

amecs-1.3.9+mc.1.20-pre2.jar
better-selection-1.1.jar
bettermounthud-1.2.2.jar
blockmeter-1.10.1-HEAD.jar
cat_jam-1.0.2.jar
CITResewn-1.1.3+1.20.jar
CleanF3-0.4.0-mc1.20.jar
clientcommands-2.8.jar
cloth-config-11.0.99-fabric.jar
deathlog-0.3.2+1.20.jar
fabric-api-0.83.0+1.20.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
fallingleaves-1.15.0+1.19.4.jar
ForgeConfigAPIPort-v7.0.0-1.20-Fabric.jar
HeldItemTooltips-v7.0.0-1.20-Fabric.jar
ImmediatelyFast-1.1.13+1.20.jar
indium-1.0.18+mc1.20.jar
inspecio-1.8.1+1.20.jar
InventoryProfilesNext-fabric-1.20-1.10.3.jar
iris-mc1.20-1.6.4.jar
krypton-0.2.3.jar
libIPN-fabric-1.20-3.0.2.jar
lithium-fabric-mc1.20-0.11.2.jar
logcleaner-1.0.0.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
midnightlib-fabric-1.4.1.1.jar
mixintrace-1.1.1+1.17.jar
modmenu-7.0.1.jar
morechathistory-1.19.1-1.1.1.jar
name-visibility-1.1.0+1.19.4-1.20.jar
NBTac-FABRIC-1.20-1.1.2.jar
NoChatReports-FABRIC-1.20-v2.2.0.jar
nonarrator-1.0.1.jar
owo-lib-0.11.0+1.20.jar
Pick-Block-Pro-1.7.19-mc1.20.jar
pistorder-mc1.20-v1.5.0-fabric.jar
PuzzlesLib-v7.0.2-1.20-Fabric.jar
raised-fabric-23w16a-1.2.2.jar
reeses_sodium_options-1.5.1+mc1.20-build.74.jar
remember-my-txt-1.0.0+MC1.20.jar
RestoreChatLinks-1.19.3-0.2.0.jar
sectionsign-1.0.2.jar
showoperatortab-1.0.0.jar
shulkerboxtooltip-fabric-4.0.2+1.20.jar
sodium-extra-0.4.20+mc1.20-build.103.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
StackDeobfuscator-1.3.2+fabric.4bca927.jar
starlight-1.1.2+fabric.dbc156f.jar
tooltipfix-1.1.1-1.20.jar
truesight-1.1.0+1.20.jar
universal-shortcuts-1.2.1.jar
visuality-0.7.0+1.20.jar

### Describe the problem

When using NBT Dump it shows this weird character:
![grafik](https://github.com/blackd/Inventory-Profiles/assets/57060126/a0f53849-6c4d-4f19-aa48-a91f5e5304de)

### Steps to reproduce

1. hover over any item
2. use shortcut to dump nbt

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
it's \t and I probably won't change it.

ctrl+c is more useful anyway
