### ISSUE TITLE
Items locked in hotbar can still be moved using hotbar keys

### ISSUE THREAD

**Issue by OakSwingZZZ** [blackd/Inventory-Profiles#334]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.19

### Modloader

Fabric

### Modloader Version

0.14.8

### Operating System

macOS

### List of all other installed mods

litematica, xeros minimap/world map, boosted brightness, item scroller

### Describe the problem

If you hover over any other the slot/item in your inventory, and the item locked is in your hotbar, you can use your hotbar hotkeys to move the item even with no player interaction enabled
https://discord.com/channels/861171785897738240/861178646478585876/1117512842560684152

### Steps to reproduce

1. lock an item in your hotbar.
2. Open any inventory.
3. Use your hotbar key, 1-9 to move the item.
4. bypasses locked slots.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
fixed in 1.10.3
