### ISSUE TITLE
Hotkey failure after switching input method with Windows key

### ISSUE THREAD

**Issue by xuwuwudi** [blackd/Inventory-Profiles#338]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.16.5

### Modloader

Forge

### Modloader Version

36.2.39

### Operating System

Windows

### List of all other installed mods

-

### Describe the problem

Collation key failure after switching input method with Windows key

### Steps to reproduce

Hotkey failure after switching input method with Windows key

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
This one will have to go through discord before being accepted at all. Too much missing information.

**Comment by xuwuwudi** [comment]
> This one will have to go through discord before being accepted at all. Too much missing information.

It told me that Unable to accept discord invitation
Has the invitation link on the curseforge page expired？

**Comment by blackd** [comment]
https://discord.gg/23YCxmveUM

although the one on Curseforge is permanent

**Comment by xuwuwudi** [comment]
![image](https://github.com/blackd/Inventory-Profiles/assets/84704462/66f3314b-1aad-4e6d-b90d-356c8c155d13)
Maybe it's a problem on my end

**Comment by blackd** [comment]
what's your discord id

**Comment by xuwuwudi** [comment]
> what's your discord id

Nihilityless#8364

**Comment by blackd** [comment]
I had 2 accounts with that name banned
try again

**Comment by xuwuwudi** [comment]
> I had 2 accounts with that name banned try again

Okay, now I'm in

**Comment by blackd** [comment]
do accept the rules
and read the server-access channel
