### ISSUE TITLE
Use Quick Villager Trading when the backpack is full, the game will report an error

### ISSUE THREAD

**Issue by clincded** [blackd/Inventory-Profiles#339]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.14.21

### Operating System

Windows

### List of all other installed mods

iris-mc1.20-1.6.4
WI-Zoom-1.4-MC1.20.1
FpsReducer2-fabric-1.20-2.5
lithium-fabric-mc1.20.1-0.11.2
continuity-3.0.0-beta.2+1.20
sodium-fabric-mc1.20-0.4.10+build.27
sodium-extra-0.4.20+mc1.20-build.103
reeses_sodium_options-1.5.1+mc1.20-build.74
fast-chest-1.4+1.20
indium-1.0.18+mc1.20
modmenu-7.0.1
RoughlyEnoughItems-12.0.625
tweakeroo-fabric-1.20.1-0.17.0
appleskin-fabric-mc1.20-2.5.0
worldedit-mod-7.2.15
fabric-carpet-1.20-1.4.112+v230608
journeymap-1.20-5.9.8-fabric
minihud-fabric-1.20.1-0.27.0
invhud.fabric.1.20-3.4.13
architectury-9.0.8-fabric
cloth-config-11.0.99-fabric
malilib-fabric-1.20.1-0.16.0
badpackets-fabric-0.4.1
fabric-language-kotlin-1.9.5+kotlin.1.8.22
libIPN-fabric-1.20-3.0.2
litematica-fabric-1.20.1-0.15.0
wthit-fabric-8.1.0 
Neat-1.20-35-FABRIC
InventoryProfilesNext-fabric-1.20-1.10.4

### Describe the problem

[minecraft-exported-crash-info-2023-06-19T08-34-47.zip](https://github.com/blackd/Inventory-Profiles/files/11782968/minecraft-exported-crash-info-2023-06-19T08-34-47.zip) 
All mod, click green to report error
[minecraft-exported-crash-info-2023-06-19T08-58-04.zip](https://github.com/blackd/Inventory-Profiles/files/11783055/minecraft-exported-crash-info-2023-06-19T08-58-04.zip) 
All mod, dot red to report error
[minecraft-exported-crash-info-2023-06-19T09-04-29.zip](https://github.com/blackd/Inventory-Profiles/files/11783086/minecraft-exported-crash-info-2023-06-19T09-04-29.zip)
This one only contains InventoryProfilesNext, and it still reports an error

single player or purpur will report an error

### Steps to reproduce

1、Fill up your backpack and inventory, emerald or otherwise
2、Red or green
![image](https://github.com/blackd/Inventory-Profiles/assets/137013448/98126146-749d-421d-87ef-60fb4f26a9d5)
3、Red or green
![image](https://github.com/blackd/Inventory-Profiles/assets/137013448/706b95a0-735e-4d7c-97a9-03e87a72086c)
4、error， game no nresponse

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
Unfortunately there is nothing in the logs that shows any kind of error.
And your description of the problem is confusing. Does the game crash or does it freeze? 

Will it be possible to post a video of the crash.

**Comment by clincded** [comment]
https://github.com/blackd/Inventory-Profiles/assets/137013448/fec1db1f-d94b-48c7-a8fc-c3d1cf5999cd

Sorry, I am Chinese, I don't know how to describe this question in English

**Comment by clincded** [comment]
When the player's backpack has been filled with blocks in the toolbar, and then use this feature, the bug will be repeated
Sorry, my English is very poor, I can only use translation software

**Comment by clincded** [comment]
When the player's backpack and toolbar are filled with blocks, and then use this feature, the bug will appear again.
Sorry, my English is very poor, I can only use translation software

**Comment by blackd** [comment]
looks like the video is enough
