### ISSUE TITLE
dependencies error on fabric 1.20.1

### ISSUE THREAD

**Issue by Dimazhan** [blackd/Inventory-Profiles#341]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.14.21

### Operating System

Windows

### List of all other installed mods

fabric-api-0.84.0+1.20.1.jar
fabric-language-kotlin-1.9.6+kotlin.1.8.22.jar
libIPN-fabric-1.20-3.0.1.jar
InventoryProfilesNext-fabric-1.20-1.10.5.jar

### Describe the problem

Game crashes during startup

InventoryProfiles require minimum version of libIPN 3.0.2, but current latest verion is 3.0.1!!

> Picked up _JAVA_OPTIONS: 
> [17:57:23] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
> [17:57:23] [main/WARN]: Mod resolution failed
> [17:57:23] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE inventoryprofilesnext 1.10.5 {depends libipn @ [>=3.0.2 <4.0.0]}, ROOT_FORCELOAD_SINGLE inventoryprofilesnext 1.10.5]
> [17:57:23] [main/INFO]: Reason: [HARD_DEP inventoryprofilesnext 1.10.5 {depends libipn @ [>=3.0.2 <4.0.0]}]
> [17:57:23] [main/INFO]: Fix: add [], remove [], replace [[libipn 3.0.1] -> add:libipn 3.0.2 ([[3.0.2,4.0.0)])]
> [17:57:23] [main/ERROR]: Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> 	 - Replace mod 'libIPN' (libipn) 3.0.1 with any version between 3.0.2 (inclusive) and 4.0.0 (exclusive).
> Unmet dependency listing:
> 	 - Mod 'Inventory Profiles Next' (inventoryprofilesnext) 1.10.5 requires any version between 3.0.2 (inclusive) and 4.0.0 (exclusive) of mod 'libIPN' (libipn), but only the wrong version is present: 3.0.1!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

### Steps to reproduce

download and run

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
yeah right there is not 3.0.2 version..... the template SAYS GO ASK ON DISCORD FIRST 

So either try looking better or go ask on discord.
