### ISSUE TITLE
Crossbow NBT is broken for Profiles

### ISSUE THREAD

**Issue by LunerticDev** [blackd/Inventory-Profiles#342]
### Have you asked for help on discord?

YES

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

Fabric 0.14.21

### Operating System

Windows

### List of all other installed mods

antighost-1.20-fabric0.83.0-1.1.5.jar
appleskin-fabric-mc1.20-2.5.0.jar
architectury-9.1.10-fabric.jar
authme-7.0.1+1.20.jar
BetterF3-7.0.0-Fabric-1.20-pre6.jar
blur-3.1.0.jar
Boat-Item-View-Fabric-1.20.1-0.0.5.jar
borderless-mining-1.1.8+1.20.1.jar
chatpatches-201.5.2.jar
cloth-config-11.1.106-fabric.jar
fabric-api-0.85.0+1.20.1.jar
fabric-language-kotlin-1.10.0+kotlin.1.9.0.jar
indium-1.0.21+mc1.20.1.jar
InventoryProfilesNext-fabric-1.20-1.10.6.jar
iris-mc1.20-1.6.4.jar
Jade-1.20-fabric-11.2.0.jar
libIPN-fabric-1.20-3.0.2.jar
litematica-fabric-1.20.1-0.15.3.jar
malilib-fabric-1.20.1-0.16.1.jar
modmenu-7.1.0.jar
owo-lib-0.11.1+1.20.jar
replaymod-1.20.1-2.6.13.jar
RoughlyEnoughItems-12.0.626.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
status-effect-bars-1.0.3.jar
symbol-chat-1.20.1-1.1.0.jar
watson-fabric-1.15.0+1.20.1.jar
WorldEditCUI-1.20+01.jar
XaeroPlus-Fabric-1.20.1-12-WM1.30.6-MM23.5.0.jar
XaerosWorldMap_1.30.6_Fabric_1.20.jar
Xaeros_Minimap_23.5.0_Fabric_1.20.jar
yet-another-config-lib-fabric-3.0.3+1.20.jar
zoom-o-matic-1.1.0-1.20-1.20.1.jar

### Describe the problem

Crossbow's NBT cannot be specified for profiles so they cannot be set to refill loaded crossbows.  Tested only on a Pufferfish multiplayer server.

Used  {Charged:1b,ChargedProjectiles:[{Count:1b,id:"minecraft:arrow"}]} to specify the loaded projectile and that the crossbow was charged (used Ctrl-c from this mod to copy the NBT from the inventory directly)

Error recieved:

Loading Profile settings failed: SyntaxErrorException(line=40, pos=2, msg=extraneous input '"minecraft:crossbow{Charged:1b,ChargedProjectiles:[{Count:1b,id:"' expecting {<EOF>, 'profile'})

(I was asked to submit a bug report by the discord as this is a known issue that needs to be addressed)

### Steps to reproduce

Try to specify an crossbow with the following NBT in a hotbar slot
HOT2
	"minecraft:crossbow{Charged:1b,ChargedProjectiles:[{Count:1b,id:"minecraft:arrow"}]}"

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
actually NBT is not really supported only enchantments and potion effects are.

I'll keep the issue I case I figure out how to include full NBT in the lexer.

**Comment by blackd** [comment]
this is fixed in all 1.21/.1 versions
