### ISSUE TITLE
[Settings] Move "pick items directly into the inventory" from "locked slots" tab to "tweaks" tab

### ISSUE THREAD

**Issue by zeid0ne** [blackd/Inventory-Profiles#344]
### Have you asked for help in discord?

NO

### Describe your desired feature.

![image](https://github.com/blackd/Inventory-Profiles/assets/38461940/3e141197-7674-4482-a141-e6f4d736f594)

Hi, posting here first cause i cant access canals on discord, sorry if i missed something (see image).

**My feature request is simple :**

In the settings, move "pick items directly into the inventory" from "locked slots" tab to "tweaks" tab.

**Why ?**

Cause i had trouble finding this option, cause its not very related to locked slots for users. I am not the only one : https://www.reddit.com/r/feedthebeast/comments/wgj6hk/is_there_a_mod_that_puts_picked_up_items_in_your/.

Thanks for all

**Comment by blackd** [comment]
you need to accept the rules before you see the channel that explains how to access the rest of the server.

actually it's related because it's acting like the slots are locked

**Comment by blackd** [comment]
I'll be reversing the default state to disabled in the next release
