### ISSUE TITLE
Log spam when connecting to beta 1.7.3 server with ViaFabricPlus

### ISSUE THREAD

**Issue by helpimnotdrowning** [blackd/Inventory-Profiles#345]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.41.21

### Operating System

Windows

### List of all other installed mods

|Mod|Version|
|---|---|
|Fabric API|0.86.1+1.20.1|
|Fabric Language Kotlin|1.10.8+kotlin.1.9.0|
|IPN|1.10.6|
|libIPN|3.0.2|
|ViaFabricPlus|2.8.2|

### Describe the problem

When joining a beta 1.7.3 server (also probably any server pre-Combat Update, since there's no offhand[^1]) through [ViaFabricPlus](https://github.com/ViaVersion/ViaFabricPlus), the game log is constantly spammed (every frame?) with an `IndexOutOfBoundsException`. Gameplay itself is not affected.

[^1]: Since the logs mention `org.anti_ad.mc.ipnext.event.AutoRefillHandler$ItemSlotMonitor`, I believe this to be a bug where IPN believes there to always be an offhand & ViaFabricPlus removes it entirely when connecting to old versions. I haven't looked into the code itself, so it's just an educated guess.
[latest.log](https://github.com/blackd/Inventory-Profiles/files/12245980/latest.log)

### Steps to reproduce

1. Create a beta 1.7.3 server (I used a Craftbukkit b1.7.3 jar from the [Internet Archive](https://archive.org/details/minecraft-beta-server-jars ), the normal jar here doesn't seem to work for me)
2. Launch the game with the above mod list
3. In the multiplayer menu, click on the top-right "ViaFabricPlus" button and select the server version from the list
4. Join the beta server
5. Witness the logs flooding with `java.lang.IndexOutOfBoundsException: Index 45 out of bounds for length 45` and its stack trace

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
IPN has never been compatible with versions of minecraft below 1.14 and as such assumptions are made for the availability of some game features. As such there is no expectations for IPN to be able to work on such versions.

The right direction for this issue is towards the mod that offers the possibility for the 1.20 client to be "compatible" with 1.7 server.

It's impossible, or at least it will be very time consuming, to make IPN compatible with such setup.

**Comment by helpimnotdrowning** [comment]
Now that I think about it you're probably right, since it's ViaFabric that's breaking core game features and not masking it in some way. Ill raise the issue with them instead.

**Comment by helpimnotdrowning** [comment]
Issue fixed on ViaFabric's side in ViaVersion/ViaFabricPlus@d35054f35cc6f3b9ac7c002111bbad192e762803 !
