### ISSUE TITLE
"Move all items" does not work with Crafting Tables

### ISSUE THREAD

**Issue by unilock** [blackd/Inventory-Profiles#348]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.19.2, 1.20.1

### Modloader

Fabric, Forge, Quilt

### Modloader Version

Fabric: 0.14.22
Forge: 43.2.14
Quilt: 0.20.0-beta.11

### Operating System

macOS

### List of all other installed mods

Fabric 1.20.1:
- Fabric API: 0.86.1
- Fabric Language Kotlin: 1.10.8
- libIPN: 3.0.2

Forge 1.19.2:
- (too many to count)

Quilt 1.20.1:
- QFAPI / QSL: 7.1.1 / 6.1.1
- Quilt Kotlin Libraries: 2.1.2
- libIPN: 3.0.2

### Describe the problem

When using the "Move All Items" hotkey in a Crafting Table, only one stack of items is transferred rather than all possible stacks of items.

(Note that, during testing, I had the "Only focused Item type" hotkey set to the same keybinding as "Move All Items", in order to only move the type of item my mouse cursor was hovering over. However, removing this keybind had no effect on the issue described here.)

### Steps to reproduce

1. Enter a singleplayer world in creative mode.
2. Give yourself several stacks of the same item, for example, 3 stacks of Cobblestone.
3. Open a Chest.
4. Press the "Move All Items" hotkey while hovering over the Cobblestone in your inventory. The default is R + T.
5. All 3 stacks of Cobblestone are moved to the chest.
6. Move the Cobblestone back to your inventory.
7. Open a Crafting Table.
8. Press the "Move All Items" hotkey while hovering over the Cobblestone again.
9. Only 1 stack of Cobblestone is moved.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
works as intended.

 if you feel that this is not the proper behaviour feel free to talk to us on discord.

**Comment by unilock** [comment]
No, I'd rather not join yet another Discord server for something so menial. If this is a "wontfix", then it looks like [Mouse Wheelie](https://modrinth.com/mod/mouse-wheelie) has this feature - I'll just use that instead.

**Comment by blackd** [comment]
well as you wish.
I prefer direct communication because I wish to understand the uses case behind the request and how do people think something should behave.

**Comment by unilock** [comment]
Sorry, my last response was rude. I'm just prejudiced against when projects insist on all communication going through e.g. Discord, since it makes it much more difficult to index / search for information.

My use case, personally, would be when crafting large amounts of ["storage blocks"](https://minecraft.fandom.com/wiki/Category:Compacted_blocks) at once, such as Hay Bales from Wheat or Blocks of Coal from Coal, both of which are materials I tend to accumulate extensively.

This feature would also be also useful when crafting large amounts of e.g. Chests, since I could simply fill the crafting table with Planks with one "move all" click and remove the center stack of Planks with another "quick move" click, instead of arduously clicking a stack of Planks and dragging right-click across the 8 relevant slots of the crafting interface, only to accidentally fill in the wrong slot, and have to make several more clicks to correct the recipe, only to have to repeat the process when going to craft even more Chests. (OK, maybe this is a little dramatic, but hopefully it gets my point across.)

I am aware of the "auto-crafting" checkbox, but it is slightly less convenient to use, since I keep it turned off by default (to avoid accidentally crafting several stacks of buttons or what have you), and because it has a tendency to not automatically refill the crafting input. (Maybe this warrants a second issue...)

**Comment by blackd** [comment]
Well IPNs auto crafting is not on by default. The default behaviour is to just refill the crafting grid.
Sometimes it might not work due to the server not willing to process that many packets. This can be mitigated by setting `Mod Setting->Wait ticks before next craft` to something more then 1.

this is how I use the full auto crafting https://www.youtube.com/watch?v=BHEnDOWltsQ

**Comment by blackd** [comment]
And the reason I insist on discord is so I can asses the situation and decide if issue will be needed.
Also the mod has so many options that it might be possible to "fix"  some of the issues, caused by uncooperative servers, that might not need fixing in the general case.

**Comment by blackd** [comment]
@unilock this add on mod https://modrinth.com/mod/invtweaks-emu-for-ipn
offers functionality to move items to the crafting grid

**Comment by unilock** [comment]
The problem I have with auto-crafting is that, when quickly repeatedly shift-clicking the crafting output to craft stacks at a time, the crafting input occasionally isn't automatically refilled. Is that something that might be fixed by increasing the auto-crafting tick delay?

As for InvTweaks Emu for IPN, it does "move all items" to the crafting grid, but it will only move up to a stack at a time - for example, if I have 4 slots of 16 cobblestone, all cobblestone will be transferred to the crafting grid, but if I have 5 slots of 16 cobblestone, only 4 of the 5 slots will be transferred. Is that a bug?

**Comment by blackd** [comment]
>  the crafting input occasionally isn't automatically refilled. Is that something that might be fixed by increasing the auto-crafting tick delay?

yes the delay is between the shift click and the attempt to restock the grid

**Comment by blackd** [comment]
> if I have 4 slots of 16 cobblestone, all cobblestone will be transferred to the crafting grid, but if I have 5 slots of 16 cobblestone, only 4 of the 5 slots will be transferred. Is that a bug?

It's possible that is a bug can you describe the key combination you are using
