### ISSUE TITLE
Crash when using  'throw all' (r + m) keybind

### ISSUE THREAD

**Issue by triphora** [blackd/Inventory-Profiles#349]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.14.21

### Operating System

macOS

### List of all other installed mods

Found in logs below

### Describe the problem

The game crashes when using the 'throw all' keybind (r + m).

Log is available [HERE, in the spoiler](https://empireminecraft.com/threads/mod-help-inventory-profiles-next-crashing.87186/#post-1629222). I would copy-paste it, but I am on mobile and whenever I try to select text on that page it jumps back to the top.

Here's a bit of the stacktrace, remapped:
```
java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
at net.minecraft.util.thread.LockHelper.crash(LockHelper.java:84)
at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom.java:49)
at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom.java:27)
at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld.java:382)
at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld.java:363)
at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1942)
at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
at net.minecraft.client.main.Main.main(Main.java:250)
```
Which suggests that this may be something from vanilla acting haywire because of IPN.

### Steps to reproduce

1. Use the 'throw all' keybind (r + m)

### Additional context

I have not opened this issue on Discord because I am a mod developer (and contributor to this mod) and do not need to be told what is a bug and what is not.

I have asked the person reporting to attempt to reproduce using only IPN. Considering the vanilla-only stacktrace/thread dumps, without any unobf mixin method names, though, I somewhat doubt this is related to interaction with other mods, though

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [x] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
I've seen this before but it was cased by sodium.

A wild guess is that keybinds of litematica and IPN are bumping heads. I suggest you change the defaut r+m to something that doesn't involve M or other litematica first keys.

**Comment by triphora** [comment]
Will get back to you when the reporter gets back to me about reproducing using only IPN. Probably worth changing the default keybind in that case.

**Comment by blackd** [comment]
also it might be mac specific which makes it impossible to fix since I don't have access to a mac

**Comment by triphora** [comment]
Looks like it can be reproduced with only IPN

https://empireminecraft.com/threads/mod-help-inventory-profiles-next-crashing.87186/#post-1629265

**Comment by blackd** [comment]
well it's mac specific then since I can't reproduce it on either Linux or windows. 

This will be so annoying to track.

**Comment by blackd** [comment]
Can I have to config file

**Comment by triphora** [comment]
https://hst.sh/eximeripoh.json

**Comment by blackd** [comment]
I guess the interval between clicks is required by the server?

If not will it be possible they try without it.

**Comment by blackd** [comment]
I'll try to fix this in the release that will be out latter today
but since I can't really test it it's just a guess work.

**Comment by triphora** [comment]
Yes, 1.10.7 fixes it. Thanks for the very quick response.
