### ISSUE TITLE
Move all issue

### ISSUE THREAD

**Issue by marie-bnl** [blackd/Inventory-Profiles#35]
Sometimes when I try to move all the items of a type with the "Move all" button it just does nothing and puts back the item in my inventory

**Comment by blackd** [comment]
I guess you mean 
Holding an item and clicking on the move all button. 
This as far as I know has always worked only from container to the inventory. And this is actually unintentional side effect of clearing the cursor before starting the moving :)

**Comment by marie-bnl** [comment]
Yes, so you confirm it's an actual issue that should be worked on

**Comment by blackd** [comment]
not really, but I'll leave this open if at some point I have time for it.

**Comment by blackd** [comment]
This can't really be fixed I can't find reliable way to do this
