### ISSUE TITLE
Crashes the game at startup

### ISSUE THREAD

**Issue by Bear228** [blackd/Inventory-Profiles#350]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Forge

### Modloader Version

InventoryProfilesNext-forge-1.20-1.10.6

### Operating System

Windows

### List of all other installed mods

![2023-08-11_23-17-53](https://github.com/blackd/Inventory-Profiles/assets/70435982/ecf8ec73-0b77-47bb-83be-1e22c38f5068)

### Describe the problem

The game starts loading and just writes about the crash of the game because of your mod

### Steps to reproduce

1.Start game

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
This is exactly the type of question you should ask on discord.
