### ISSUE TITLE
Change inventory sort order through GUI

### ISSUE THREAD

**Issue by TheMeskimoze** [blackd/Inventory-Profiles#351]
### Have you asked for help in discord?

YES

### Describe your desired feature.

adding an option to change the chest sort order from the GUI of the chest without opening the config every time.
 for example sometimes i want to sort chest in different ways like some chests in the default creative order and some other chests in item count.
 my suggestion that it doesn't have to be fancy or add new GUI buttons (would be cool if possible), Just the sort inventory button when you hover over it it says the current sort method and shift clicking  (or any similar approach) would change the sort method without sorting and just clicking will sort.
 example included of how i imagine it (for demonstration only as it doesn't look like the default GUI)
 
![Screenshot 2023-08-20 023813 copy](https://github.com/blackd/Inventory-Profiles/assets/47092090/836c4fdd-9ff3-480f-a93e-6e352fc2ce0f)

PS : if you want to go fancy or so we can add an option in the config that when it's enabled if you click the sort button it will give you a list of the sort methods (you can also apply from the config which methods to be added in this list ) and you choose from this list how the chest is going to be sorted (dont have a visualization for this)

**Comment by Beethoven-n** [comment]
seconded! i run a modded minecraft server, and it'd be nice to accommodate the users who don't wanna touch rules.txt or profiles.txt.

**Comment by blackd** [comment]
[sortorder.webm](https://github.com/blackd/Inventory-Profiles/assets/333840/541a0298-62e8-44c3-b226-ae6f644ab5ed)
