### ISSUE TITLE
The mod version forge-1.19-1.10.6 incompatible with libIPN 4.0

### ISSUE THREAD

**Issue by magcicada** [blackd/Inventory-Profiles#353]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.19.2

### Modloader

Forge

### Modloader Version

43.2.21

### List of all other installed mods

InventoryProfilesNext-forge-1.19-1.10.6.jar
libIPN-forge-1.19-4.0.0.jar

### Describe the problem

Inventory-Profiles forge-1.19-1.10.6 incompatible with libIPN 4.0

### Steps to reproduce

as Describe said

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
works as expected use v 3 of libIPN

the new IPN that needs 4 will be out in couple of hours
