### ISSUE TITLE
Put same enchantements with different levels together

### ISSUE THREAD

**Issue by marie-bnl** [blackd/Inventory-Profiles#36]
I have a chest of enchanted books and it successfully sorts them by enchantement (the "Knockback II" are at the same place for example), but if I have a "Knockback I" and a "Knockback II" they are not put together and are very far from each other, it would be cool to put them together

**Comment by blackd** [comment]
By default items are sorted the same way as the creative inventory.
But sorting is fully customizable... the original author attempted to explain how https://github.com/jsnimda/Inventory-Profiles/wiki/Add-a-Custom-Rule
