### ISSUE TITLE
lite version

### ISSUE THREAD

**Issue by pizzav-xyz** [blackd/Inventory-Profiles#360]
### Have you asked for help in discord?

YES

### Describe your desired feature.

a version which only has the inventory sort buttons 
![image](https://github.com/blackd/Inventory-Profiles/assets/103120356/a492d7d0-c1e8-4424-b935-9b2f26df10d0)

**Comment by blackd** [comment]
not accepted

**Comment by ajaxnotmeta** [comment]
why? i also feel some features kinda bloated and some peeps want only those things
p.s and this is the only mods that works with forge as of now

**Comment by blackd** [comment]
1. I don't have the time to maintain another version of the mod.
2. it's not that hard to just disable all other features.

**Comment by pizzav-xyz** [comment]
> 1. I don't have the time to maintain another version of the mod.
> 2. it's not that hard to just disable all other features.

you can just make it for 1.20.1 and the comm will maintain it

**Comment by blackd** [comment]
yeah like anyone have even tried to help.

**Comment by blackd** [comment]
and before "it's too complex that's why no one tries to help"
removing every other feature and just leaving the sort will remove around 10% of the code.

**Comment by ajaxnotmeta** [comment]
> 1. I don't have the time to maintain another version of the mod.
> 
>     2. it's not that hard to just disable all other features.

1. understandable
2. the wording is too technical tbh, and the UI sometimes made me want to puke possibly becasue theres duplicates between tabs and category inside the menu making it harder to search when you dont know what are you doing (feels like blender before 2.8 update) and that doesnt help with the fact that the default settings were very unlike Vanilla, especially that drop item put in inventory instead hotbars wich supposed to be false by default

**Comment by blackd** [comment]
> 2\. the wording is too technical tbh, and the UI sometimes made me want to puke possibly becasue theres duplicates between tabs and category inside the menu making it harder to search when you dont know what are you doing (feels like blender before 2.8 update) and that doesnt help with the fact that the default settings were very unlike Vanilla, especially that drop item put in inventory instead hotbars wich supposed to be false by default

feel free to change the tool tips to be more understandable and make a pull request. Or even make documentation what the options do and I'll include it in the mod.

About the item pickup... would have you even be aware the mod has settings gui let alone that it was possible to puck up items in the inventory.  But by this point it has served it's purpose and I'll probably set it to false by default in the next release.

**Comment by ajaxnotmeta** [comment]
> > 2. the wording is too technical tbh, and the UI sometimes made me want to puke possibly becasue theres duplicates between tabs and category inside the menu making it harder to search when you dont know what are you doing (feels like blender before 2.8 update) and that doesnt help with the fact that the default settings were very unlike Vanilla, especially that drop item put in inventory instead hotbars wich supposed to be false by default
> 
> feel free to change the tool tips to be more understandable and make a pull request. Or even make documentation what the options do and I'll include it in the mod.
> 
> About the item pickup... would have you even be aware the mod has settings gui let alone that it was possible to puck up items in the inventory. But by this point it has served it's purpose and I'll probably set it to false by default in the next release.

i am aware, but since the UI were basicly a wall of text and feel cluttered its hard to search what i want to do or make it behave the way i want! and i must say thanks to you for making that pick up feature as false by default the next update! 🙏

as for the pull request i still dont know much about how github or git works and make this accout just so i can report bugs and/or asking for help in many FOSS projects i use daily

**Comment by blackd** [comment]
> 2\. becasue theres duplicates between tabs

there are no duplicates 



> i am aware, but since the UI were basicly a wall of text and feel cluttered

At it's core the mod just simulates player input as fast as possible. Some servers don't really like this so the need for so many options to tweak how it's done.
Since the mod is pure client side in some cases even the most basic functions need some tweaking in some cases. Resulting a very complex Settings. 

If you have an idea how to organise them differently I'm open for suggestions.

**Comment by RashidFTW** [comment]
> 2. it's not that hard to just disable all other features.

I am sorry, maybe I am missing something, but this is simply not true! It is hard, options for one feature are scattered across multiple tabs, even then for most things, you can either simply hide it from showing or unbind it's hotkey, is that considered disabling, idk, I guess?

Also, the extra features like item-scrolling (not even mentioned on mod page) & auto-refill provided by this mod are not a niche and have many sole-mod alternatives. It's inconsiderate to assume players are not using other mods, and to not provide disable toggles, all the while having them enabled and interfering with other mods right from the get go. 

if I am wrong and it's indeed _not that hard_ to disable them. Wouldn't adding a toggle option to turn off all the extra stuff be a great compromise solution? No need for maintaining two mods and players don't have to spend hours (I am serious) going thought the overwhelming number of settings scattered across different tabs.

> If you have an idea how to organise them differently I'm open for suggestions.

The features specific options need to actually stick to their own tabs. Keep everything related to a single feature on one page, **GUI options, hotkeys options, and all**. At the top of each feature page there should be a single toggle to disable that feature, period.
