### ISSUE TITLE
"Pick Items Directly into the Inventory" option sometimes voids items

### ISSUE THREAD

**Issue by edensiiln** [blackd/Inventory-Profiles#363]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.14.22

### Operating System

Linux

### List of all other installed mods

Fabric API 0.89.3+1.20.1
Fabric Language Kotlin 1.10.10+kotlin.1.9.10
inventory profiles next 1.10.7
libipn 4.0.0
origins 1.10.0
origins: classes 1.7.0

### Describe the problem

When "Pick Items Directly into the Inventory" is true and your inventory is nearly full, selecting an origin from the origins mod to gain multiple 'starting items' will void any of those items that can't find a spot in your inventory. they are not added to your hotbar or even dropped on the ground. this may work in similar situations with vanilla/other mods, but is so far untested.

### Steps to reproduce

First, ensure the option "Locked Slots>Pick Items Directly into the Inventory" is set to true (as it is by default).
Then, with only one slot open in an otherwise full inventory (not necessarily hotbar), use an orb of origin to select an origin that gives you multiple starting items, such as the explorer from origins:classes. Note the missing items.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
This is something that should be handled server side.
moving an item from the hotbar to the inventory must not result the item being destroyed.
There is nothing I can do about it you should report it to the mod that generates the items.

**Comment by edensiiln** [comment]
thank you. it seemed to me that this mod was the more likely culprit, but I'll report it to the other one then
