### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DelviousCrafts** [blackd/Inventory-Profiles#364]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.19.2

### Modloader

Forge

### Modloader Version

43.3.0 & 43.3.2

### Operating System

Windows

### List of all other installed mods

Kotlin for Forge: 3.12.0
LiblPN: 4.0.0

### Describe the problem

Version 1.10.8 crashes on startup. 

[Latest Log](https://gist.github.com/DelviousCrafts/83a1b75e9873ac516c8c26d144af4ed6)

[Debug Log](https://gist.github.com/DelviousCrafts/ce8eec7e3778a17cfc6fa6315e1cc8b2)

### Steps to reproduce

- install version 1.10.8
- attempt to launch
- crash

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
yeah I'm working on this

**Comment by guivnf** [comment]
I'm getting the same crash. Any temporary fix?

**Comment by blackd** [comment]
yeah I removed the forge builds from curseforge and Modrinth

**Comment by guivnf** [comment]
I'm guessing you won't support forge anymore?

**Comment by BamsyTheSergal** [comment]
i was getting this on 1.20.1 aswell.

**Comment by guivnf** [comment]
> i was getting this on 1.20.1 aswell.

Yep this seems to be an issue with all the latest builds marked with neoforge support. I tried it on 1.19.4 and got the same crash

**Comment by blackd** [comment]
well I'm considering dropping forge
it's pain in the ass and always something doesn't work properly
but for now I removed them so people don't get crashes

**Comment by guivnf** [comment]
> well I'm considering dropping forge it's pain in the ass and always something doesn't work properly but for now I removed them so people don't get crashes

what's the current most stable build for 1.20.1 then?
would it be this one? 
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4810838

**Comment by blackd** [comment]
1.10.7
