### ISSUE TITLE
Game crashes when used in conjunction with "Sounds" mod

### ISSUE THREAD

**Issue by neonjuno** [blackd/Inventory-Profiles#373]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.15.3

### Operating System

Windows

### List of all other installed mods

Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.2.1
		ambientsounds: AmbientSounds 5.3.5
		architectury: Architectury 9.1.12
		autohud: Auto HUD 6.3.2+1.20.1
			yaclx: YetAnotherConfigLibExtensions 1.6+1.20
		balm-fabric: Balm 7.2.1
		better_climbing: Better Climbing 3
		betterclouds: Better Clouds 1.3.12+1.20.1
		bettercombat: Better Combat 1.8.3+1.20.1
		betterspawnercontrol: Better Spawner Control 4.4
		bettertridents: Better Tridents 8.0.1
		blockrunner: Block Runner 8.0.2
		blossom: Blossom 1.0.7
		bottledair: Bottled Air 2.3
		bottleyourxp: Bottle Your Xp 3.3
		breakfree: Break Free 1.2.0
		bridgingmod: Bridging Mod 2.2.0+1.20.1.fabric
		brokenleadwarner: Broken Lead Warner 1.1.1+1.20.x
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.2.7
		chickensshed: ChickensShed 1.5.0+1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.26
		companion: Companion 5.1.0
		completeconfig: CompleteConfig 2.5.0
			completeconfig-base: completeconfig-base 2.5.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.5.0
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.5.0
		controlling: Controlling For Fabric 12.0.2
		creativecore: CreativeCore 2.11.10
			net_minecraftforge_eventbus: eventbus 6.0.3
		cryingghasts: Crying Ghasts 3.3
		cull-less-leaves: Cull Less Leaves 1.3.0
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		doubledoors: Double Doors 5.2
		easyanvils: Easy Anvils 8.0.1
		easymagic: Easy Magic 8.0.1
		easyshulkerboxes: Easy Shulker Boxes 8.0.1
			puzzlesapi: Puzzles Api 8.1.4
		eatinganimationid: Eating Animation 1.20+1.9.5
		emi: EMI 1.0.28+1.20.1+fabric
		emi_enchanting: EMI Enchanting 0.1.0+1.20.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		fallingleaves: Falling Leaves 1.15.4
		ferritecore: FerriteCore 6.0.1
		firstperson: FirstpersonModel 2.2.4
		forgeconfigapiport: Forge Config API Port 8.0.0
		glowing-torchflower: Glowing Torchflower 1.0.0
		grindenchantments: Grind Enchantments 3.1.2+1.20
			codec-config-api: Codec Config API 1.0.2+1.19.3
		guarding: Guarding 2.3.3
			mm: Manningham Mills 2.3
			scribe: Scribe 1.20.1-0.5.0-alpha
		harvestwithease: Harvest with ease 8.0.0.2
		highlight: Highlight 2.0.1
			resourcefullib: Resourceful Lib 2.0.7
				com_teamresourceful_yabn: yabn 1.0.3
		horsebuff: HorseBuff 2.1.2
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.8+1.20.4
			net_lenni0451_reflect: Reflect 1.3.1
		indium: Indium 1.0.27+mc1.20.1
		interactic: Interactic 0.2.0+1.20
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 6.1.1+1.20.1
		kiwi: Kiwi Library 11.3.0
		kleeslabs: KleeSlabs 15.0.0
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn 1.2.0
		libipn: libIPN 4.0.1
		lightoverlay: Light Overlay 8.0.0
		lithium: Lithium 0.11.2
		logical_zoom: Logical Zoom 0.0.20
		malilib: MaLiLib 0.16.3
		map_atlases: Map Atlases 2.6.0
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		modern_beta: Modern Beta Fabric 6.4.1+1.20
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.8.71
		mru: Mineblock's Repeated Utilities 0.4.0+1.20
		music_control: Music Control 1.6.3+1.20.1
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		nametagtweaks: Name Tag Tweaks 3.2
		nnvf: No Night Vision Flickering 0.1.3_1.20
		nostalgic_tweaks: Nostalgic Tweaks 2.0.0-Beta-8.4.1
			me_xdrop_fuzzywuzzy: fuzzywuzzy 1.4.0
		notenoughanimations: NotEnoughAnimations 1.6.4
		optigui: OptiGUI 2.1.7
			optiglue: OptiGlue 2.1.7-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		particlerain: Particle Rain 2.0.8
		particletweaks: Particle Tweaks 1.1.3-Fabric+1.20.1-unstable
		passablefoliage: Passable Foliage 1.20.1-fabric-8.2.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.1
			kirin: Kirin UI 1.15.4+1.20
		puzzleslib: Puzzles Lib 8.1.11
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		raised: Raised 3.1.0
		reacharound: Reacharound 1.1.2
		realisticsleep: Realistic Sleep 1.10.1+mc1.20-1.20.1
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.1-build.95
		rrls: Remove Reloading Screen 3.2.0-1.20.1-fabric
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.2
		searchables: Searchables 1.0.2
		seasons: Fabric Seasons 2.3+1.20
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		sounds: Sounds 0.4.0+1.20.1
		spawnanimations: Spawn Animations 1.9.4+mod
		spelunker: Spelunker 1.5.3-mc1.20
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		textile_backup: Textile Backup 3.1.2-1.20
			com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
			org_apache_commons_commons-compress: commons-compress 1.22
			org_tukaani_xz: xz 1.9
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.8
		treechop: HT's TreeChop 0.18.3
		trimeffects: Trim Effects 1.1.0-fabric
		universal-graves: Universal Graves 3.0.0+1.20.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.3+1.20.1
			polymer-core: Polymer (Core) 0.5.15+1.20.1
				polymer-networking: Polymer (Networking) 0.5.15+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.15+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.15+1.20.1
				polymer-common: Polymer (Common) 0.5.15+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.15+1.20.1
			predicate-api: Predicate API 0.2.1+1.20.1
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			sgui: sgui 1.2.2+1.20
		universalenchants: Universal Enchants 8.0.0
			extensibleenums: Extensible Enums 7.0.1
		veinmining: Vein Mining 1.2.1+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		visuality: Visuality 0.7.1+1.20
		visualworkbench: Visual Workbench 8.0.0
		whats_that_slot: What's That Slot? 1.3.4+1.20.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

### Describe the problem

When sorting or scrolling items while using the "[Sounds](https://modrinth.com/mod/sound)" mod with "Item Click Sounds" on, the game will sometimes crash. Single player world.

Crash logs:
[crash-2023-12-25_22.30.39-client.txt](https://github.com/blackd/Inventory-Profiles/files/13767972/crash-2023-12-25_22.30.39-client.txt)
[crash-2023-12-25_22.02.00-client.txt](https://github.com/blackd/Inventory-Profiles/files/13767973/crash-2023-12-25_22.02.00-client.txt)
[crash-2023-12-25_21.52.44-client.txt](https://github.com/blackd/Inventory-Profiles/files/13767974/crash-2023-12-25_21.52.44-client.txt)

### Steps to reproduce

- Install IPN
- Install Sounds
- Try using IPN until it crashes

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [x] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
Hi,

I think you should report this to Sounds, IPN is just using normal MC API just very fast.
So since Sounds changes how vanilla Minecraft sound system works it probably causes the crash.

I'll keep this open for now.

**Comment by neonjuno** [comment]
Alright, thank you for the answer, I've opened a new issue on the Sounds repository.
