### ISSUE TITLE
[Conflict] This mod conflicts with Eldritch End

### ISSUE THREAD

**Issue by tiigerbones** [blackd/Inventory-Profiles#376]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.15.3

### Operating System

Windows

### List of all other installed mods

[3D Skin Layers](https://tauri.localhost/project/3dskinlayers/?i=test_realms_1.0.0)
[AppleSkin](https://tauri.localhost/project/appleskin/?i=test_realms_1.0.0)
[Architectury API](https://tauri.localhost/project/architectury-api/?i=test_realms_1.0.0)
[AzureLib](https://tauri.localhost/project/azurelib/?i=test_realms_1.0.0)
[CIT Resewn](https://tauri.localhost/project/cit-resewn/?i=test_realms_1.0.0)
[Cloth Config API](https://tauri.localhost/project/cloth-config/?i=test_realms_1.0.0)
[Dynamic FPS](https://tauri.localhost/project/dynamic-fps/?i=test_realms_1.0.0)
[Eldritch End](https://tauri.localhost/project/eldritch-end/?i=test_realms_1.0.0)
[Fabric API](https://tauri.localhost/project/fabric-api/?i=test_realms_1.0.0)
[Fabric Language Kotlin](https://tauri.localhost/project/fabric-language-kotlin/?i=test_realms_1.0.0)
[FerriteCore](https://tauri.localhost/project/ferrite-core/?i=test_realms_1.0.0)
[Indium](https://tauri.localhost/project/indium/?i=test_realms_1.0.0)
[Necronomicon API](https://tauri.localhost/project/necronomicon/?i=test_realms_1.0.0)
[Sodium](https://tauri.localhost/project/sodium/?i=test_realms_1.0.0)
[Sodium Extra](https://tauri.localhost/project/sodium-extra/?i=test_realms_1.0.0)
[libIPN](https://tauri.localhost/project/libipn/?i=test_realms_1.0.0)

### Describe the problem

While trying to get rid of some of the problematic conflicts from my modpack i found that these 2 mods dont play nice, nothing too game breaking but surely annoying.
Inventory profiles seems to put the ui from Eldritch End to the back whenever Inventory profiles is present
[Eldritch End](https://modrinth.com/mod/eldritch-end/version/0.2.30)
[Inventory Profiles](https://modrinth.com/mod/inventory-profiles-next/version/MYaRwBOZ)

### Steps to reproduce

Download the stated mods
Open up a singleplayer world and open up your inventory
Hover over the eldritch end icon next to the player model

![Screenshot 2024-01-03 165941](https://github.com/blackd/Inventory-Profiles/assets/101901291/96ae4d50-b8ee-4f9e-93b3-694f58246cc2)

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [x] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
I don't see any IPN UI components in the provided screenshot!?

You should have asked on discord as the temple insisted! It sounds like you are having problems with overlapping GUI elements? IPN has this covered by its GUI editor.
If above assumptions are incorrect please reopen the issue if you just need help accessing said GUI editor ask on discord.

**Comment by tiigerbones** [comment]
realized i was replying to the wrong mod.
still gotta try the gui editor, ill reopen if that doesnt fix it

edit: i will have a look at that editor though.

**Comment by tiigerbones** [comment]
@blackd 
checked the options provided by pressing r + g and theres not much i can do to fix this
it seems that IPN puts items ahead of certain UI

all you need to do is download 
[Eldritch End](https://modrinth.com/mod/eldritch-end/version/0.2.30)
[Inventory Profiles](https://modrinth.com/mod/inventory-profiles-next/version/MYaRwBOZ)
to see for yourself.
![image](https://github.com/blackd/Inventory-Profiles/assets/101901291/1295b28d-7797-4102-8ac8-d33320bb7ea9)

**Comment by blackd** [comment]
IPN doesn't change the draw order/layered context

The slots over/underlay is painted only if there are locked locked slots. And the buttons are drown after the whole GUI has finished drawing.
With the 1.20 changes the proper layered draw context is used.

You should report this to Eldritch End too so they can check what's going on too.
