### ISSUE TITLE
Would like support for customising where buttons are displayed in a particular GUI.

### ISSUE THREAD

**Issue by EmptyDreams** [blackd/Inventory-Profiles#377]
### Have you asked for help in discord?

NO

### Describe your desired feature.

Since I don't have access to the relevant channels in discord (I don't normally use discord, so I may have made a mistake somewhere), I'll have to post the issue directly on github. hope you understand.

As shown in the picture, when the Traveller's Backpack and the IPN work together, the buttons of the IPN will cover part of the interface of the backpack.

![image](https://github.com/blackd/Inventory-Profiles/assets/44894906/78cf1821-1747-4457-8f4f-ddd61eb1222c)

So I would like IPN to add a feature that allows the player to freely adjust the position and arrangement of the buttons in a particular GUI, as a solution to the compatibility issue for all GUIs that contain a similar problem.

**Comment by blackd** [comment]
read the rules channel

but for your question press r+g while the GUI is opened

**Comment by EmptyDreams** [comment]
> read the rules channel
> 
> but for your question press r+g while the GUI is opened

Thank you very much for your help.
