### ISSUE TITLE
the modrinth page says nothing about required dependencies

### ISSUE THREAD

**Issue by SalTeyJek004** [blackd/Inventory-Profiles#378]
### Have you asked for help on discord?

NO

### Minecraft Version/s

irelevant

### Modloader

Fabric

### Modloader Version

irelevant

### List of all other installed mods

irelevant

### Describe the problem

i have not found any list of the required dependencies on modrinth, this would be both nice to have and is easy to add

### Steps to reproduce

https://modrinth.com/mod/inventory-profiles-next
go here ^

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [x] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
Every version has it's own dependency list.

**Comment by SalTeyJek004** [comment]
i see, this was not something i knew about modrinth
you should put "you can find the required mods for a specific version on that versions page" to the mod description page
