### ISSUE TITLE
"Items Allowed in Hotbar" doesn't work well with used tools

### ISSUE THREAD

**Issue by xaliazhar** [blackd/Inventory-Profiles#379]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.4

### Modloader

Fabric

### Modloader Version

0.15.1-1.20.4

### Operating System

Windows

### List of all other installed mods

IPN and its dependencies

### Describe the problem

https://github.com/blackd/Inventory-Profiles/assets/58647884/712e7dfb-b10b-48b2-9cf2-1b53bf1b24b2

The item id specified in the "Items Allowed In Hotbar" field, if the tool's durability is reduced by at least 1 (used), does not work, this is annoying when using trident with loyalty

### Steps to reproduce

1. Have the same type new tools and used tools
2. Add the id of items into "Items Allowed In Hotbar" (ex: minecraft:trident)
3. Set to true "Pick Items Directly Into  The Inventory"
4. Drop them, then pickup
5. -- The used tools will be in Inventory and the new tools in hotbar

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
works as intended.
you can fine tune the autorefill for tools in the autorefill tab.

**Comment by xaliazhar** [comment]
> works as intended. you can fine tune the autorefill for tools in the autorefill tab.

tried, but still, what settings should I set?

**Comment by blackd** [comment]
depending on what type of tools you want to preserve.
you can disable auto refill for non enchanted tools and set tools with maximum durability bellow certain values to be allowed to break.

read the tool tips of the options
