### ISSUE TITLE
Game crashes in a specific world

### ISSUE THREAD

**Issue by llrluis** [blackd/Inventory-Profiles#38]
Hi, I love this mod, but I have a problem.

When I open a specific world the game crashes, I thought it was some incompatibility with another mod but I tried only to test it with this one and the problem persists.

I don't know if you can help me since it is a particular problem :(

Game Version: 1.17.1 - Fabric
Mod Version: Inventory Profiles Next 0.8.5

I attach the complete error log:
[crash-2021-08-09_13.30.21-client.txt](https://github.com/blackd/Inventory-Profiles/files/6956618/crash-2021-08-09_13.30.21-client.txt)

And the world in case you want to perform some tests:
[BUSINESS CENTER _ Trading Hall.zip](https://github.com/blackd/Inventory-Profiles/files/6956637/BUSINESS.CENTER._.Trading.Hall.zip)

Thank you very much for your support <3

**Comment by blackd** [comment]
Well, yes the world loads for me without problems.
Also the error doesn't go through the mod code.

Have you tried to load the world without this mod but with fabric and fabric api?

**Comment by llrluis** [comment]
It's weird, but I have tested it only with fabric and fabric api with no issues. even do a clean install and the problem only occurs when the mod is active.

I imagine that it must be an isolated problem, I will try to copy the schematic of the world and try to load it in another to verify that it is not a problem of corrupt generation.

**Comment by blackd** [comment]
tbh if you are comfortable with code and stuff the only thing I can suggest is downloading the code and running the game in the debugger

**Comment by marie-bnl** [comment]
I am able to reproduce it

**Comment by marie-bnl** [comment]
It seems to come from the `/` in the name of the world. The mod at some point tries to write or locate the file `lockSlots-BUSINESS CENTER / Trading Hall.txt`, which is not a valid path. The `/` should be replaced by a `_` here.

**Comment by marie-bnl** [comment]
After removing the `/` from the world name, I am able to start the world without problems (nice building :wink:)

**Comment by blackd** [comment]
Sounds like a "windows" problem 

But the thing is that part of the code is protected and should handle all errors related to file operations

**Comment by marie-bnl** [comment]
So will you let this bug unfixed?

**Comment by blackd** [comment]
read above your message

**Comment by marie-bnl** [comment]
Yes I read it, but may it be a Windows problem or not, the problem is still there and should be fixed, no? And the fix replacing "/" by "_" seems pretty simple

**Comment by blackd** [comment]
![lol](https://user-images.githubusercontent.com/333840/130233760-094c2f8f-69b7-45d0-8f6c-96d02564fa15.png)

**Comment by marie-bnl** [comment]
Ah yes sorry I didn't see there was a commit in the close message, sorry for the time loss.
