### ISSUE TITLE
1.18 Synthetic too laggy

### ISSUE THREAD

**Issue by zc1108aaa** [blackd/Inventory-Profiles#380]
### Have you asked for help in discord?

NO

### Describe your desired feature.

1.18 Synthetic too laggy
[latest.log](https://github.com/blackd/Inventory-Profiles/files/13947499/latest.log)
1.20 doesn't get stuck
[latest.log](https://github.com/blackd/Inventory-Profiles/files/13947495/latest.log)

**Comment by blackd** [comment]
Yeah this type of issues is why ASK ON DISCORD is the first advice.

Either describe the issue in details here or go  to discord and explain!

this issue will be closed unless one of the above is done in timely manner

**Comment by zc1108aaa** [comment]
1.18 Synthesis once, card twice

https://github.com/blackd/Inventory-Profiles/assets/155424398/2db04a5c-61d6-4ab2-a9ec-d05a493d969a

**Comment by blackd** [comment]
this means nothing to me.

try using words and describe the problem. 

try only with IPN and the mod in question 


post link to the mod that you think causes the problem.

**Comment by zc1108aaa** [comment]
1.18 Synthesis once, card twice

https://github.com/blackd/Inventory-Profiles/assets/155424398/7a6f01ab-e15a-4d7d-ba0c-a8dab0908054

**Comment by zc1108aaa** [comment]
1.18 added REI , More sluggish

**Comment by zc1108aaa** [comment]
Version 1.20, 9 groups, one group at a time, 1 second put in, a few seconds synthesized

1.18, click on the left item to synthesize,With REI,Just put it in, 64, synthesis takes one minute,

Click on the item card below for a few seconds to put it in, click on the synthesis card for one minute, and then hold it for a few more seconds to synthesize

**Comment by zc1108aaa** [comment]
Suspected to be a problem with REImod
