### ISSUE TITLE
informal item stack size

### ISSUE THREAD

**Issue by goldstargloww** [blackd/Inventory-Profiles#381]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.15.3

### Operating System

Windows

### List of all other installed mods

- advancementplaques 1.4.11
- amecs 1.3.10+mc.1.20.1
- appleskin 2.5.1+mc1.20
- architectury 9.1.12
- athena 3.1.1
- audioplayer 1.20.1-1.8.7
- authme 7.0.2+1.20
- autoclicker-fabric 1.20.1-1.8.0-build.25
- autofish 0.9.10-SNAPSHOT
- beenfo 1.20-fabric0.83.0-1.3.3
- betterf3 7.0.2
- betterladdersmod 0.0.2.1.20.1
- betterstats 3.7+fabric-1.20.1
- blahaj 0.3.2
- blockmeter 1.11.0
- blockus 2.7.10+1.20.1
- boatiview 0.0.5
- borderlessmining 1.1.8+1.20.1
- c2me 0.2.0+alpha.11.0
- cameraoverhaul 1.4.0-fabric-universal
- cat_jam 1.2.1
- centered-crosshair 1.0.6+b2
- chat_heads 0.10.30
- chipped 3.0.1
- citresewn 1.1.3+1.20
- clean_tooltips 1.0
- cloth-config 11.1.118
- coloredfishingline 1.20-1.0.2
- comforts 6.3.4+1.20.1
- continuity 3.0.0-beta.4+1.20.1
- controlling 12.0.2
- cosmetic-armor 1.6.0
- craterlib 1.1.1
- customsplashscreen 2.1.1
- damagevignette 2.0.2
- deathlog 0.3.2+1.20
- deftulib 1.7.0
- dynamic_fps 3.3.3
- ears 1.4.6
- elytraslot 6.3.0+1.20.1
- emi 1.1.0+1.20.1+fabric
- emi_enchanting 0.1.0+1.20.1
- emitrades 1.2.1+mc1.20.1
- emojitype 2.2.3+1.20.4
- enhancedblockentities 0.9+1.20
- enhancedgroups 1.20.1-1.5.2
- entity_texture_features 5.2.1
- entityculling 1.6.2-mc1.20.1
- fabric-api 0.91.0+1.20.1
- fabricloader 0.15.3
- fabrictailor 2.1.2
- fadeless 1.0.1
- ferritecore 6.0.1
- feytweaks 1.20-1.2.7
- fishing_ruler 1.0.2-mc1.20+
- flowerymooblooms 2.0.0
- fluidvoidfading 1.1.3
- forgeconfigapiport 8.0.0
- freecam 1.2.1+1.20
- friendsandfoes 2.0.7
- fwaystones 3.3.2+mc1.20.1
- gamemenuremovegfarb 2.1.2
- held-item-info 1.5.0
- highlight 2.0.1
- iceberg 1.1.18
- immediatelyfast 1.2.8+1.20.4
- immersive_paintings 0.6.7+1.20.1
- indium 1.0.27+mc1.20.1
- infinite-music 0.3.0
- infwithmend 1.0.2
- inventoryprofilesnext 1.10.9
- iris 1.6.11
- itemswapper 0.5.3-mc1.20.1
- jade 11.7.0
- java 17
- journeymap 5.9.18
- krypton 0.2.3
- lambdynlights 2.3.2+1.20.1
- langsplit 1.20.1-2.4-beta
- languagereload 1.5.10+1.20.1
- lazydfu 0.1.3
- libipn 4.0.1
- litematica 0.15.3
- lithium 0.11.2
- malilib 0.16.3
- mavapi 1.1.3
- mavm 1.2.4
- memoryleakfix 1.1.5
- midnightcontrols 1.8.2+1.20
- minecraft 1.20.1
- minihud 0.27.0
- modelfix 1.14
- modmenu 7.2.2
- mods-command 1.1.3
- morechathistory 1.1.1
- moreculling 1.20.4-0.21.0
- moremcmeta 1.20.1-4.4.6
- moremcmeta_emissive_plugin 1.20.1-2.0.4
- moremobvariants 1.2.2
- namepain 1.5.3
- nicer-skies 1.3.0
- no-screenshot-message 1.0.0
- notenoughanimations 1.7.0
- notes 1.20.1-2.1.0-fabric
- noxesium 1.0.3+9b339b0
- nrn 1.20.1-1.0.0
- owo 0.11.2+1.20
- pack_it_up 0.3.1+1.20.1
- patchouli 1.20.1-84-FABRIC
- puzzle 1.5.2+1.20
- radiantgear 2.1.0+1.20.1
- raised 3.1.1
- reacharound 1.1.2
- reeses-sodium-options 1.6.5+mc1.20.1-build.95
- replanter 1.3
- resourcefullib 2.1.20
- rprenames 0.7.2
- screenfx 1.4.0+1.20
- screenshotclipboard 1.0.9
- seamless 2.2.2
- searchables 1.0.2
- showmeyourskin 1.6.11+1.20
- shulkerboxtooltip 4.0.4+1.20.1
- simple-rpc 3.2.4
- sit 1.20-24
- skinlayers3d 1.6.2
- sodium 0.5.3
- sodium-extra 0.5.1+mc1.20.1-build.112
- statement 4.2.9+1.14.4-1.20.4
- status 1.20.1-1.0.5
- status-effect-bars 1.0.3
- styledchat 2.2.3+1.20.1
- suggestion_tweaker 1.20-1.5.1
- switchy 2.9.1+1.20
- switchy-inventories 1.8.2+1.19
- switchy-proxy 1.7.0+1.20
- switchy-status 1.0.1+1.19
- switchy_teleport 1.2.5+1.20
- talkbubbles 1.0.8
- things 0.3.3+1.20
- titlefixer 1.0+1.20.1
- tooltipfix 1.1.1-1.20
- trinkets 3.7.1
- twigs 3.1.0
- vectorientation 1.0.1a
- vmp 0.2.0+beta.7.102
- voicechat 1.20.1-2.4.32
- walllanterns 1.6.1+1.20.1
- waveycapes 1.3.2
- wmitaf 3.2.0
- yet_another_config_lib_v3 3.2.1+1.20
- zoomify 2.11.2

### Describe the problem

using [pack it up](https://modrinth.com/mod/pack-it-up), orepacks for example allow you to store items up to 256 per stack instead of 64
when it reaches 128 or more, the item just stops rendering

![image](https://github.com/blackd/Inventory-Profiles/assets/103953305/314b7e62-eb19-4ccd-a2f7-c3896c0e16d3)
![image](https://github.com/blackd/Inventory-Profiles/assets/103953305/509dfe51-971f-41b8-b0af-04921c0de583)

and tends to throw an error like this (but not every time)
`[Inventory Profiles Next] Informal item stack 101x raw_copper{}`

i get why this happens because stacks over 64 usually aren't allowed, but some mods do allow for them and it creates incompatibilities

### Steps to reproduce

1. get an orepack
2. try to put more than 127 items in a stack

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
IPN can't operate on oversized stacks. This is a limitation for being only client side.

About the rendering issue I doubt it's IPN fault. Have you tested without IPN installed to see if the items render proper?

**Comment by goldstargloww** [comment]
probably should've checked that honestly, thanks for answering anwyay - it renders with just ipn + pack it up + their dependencies, so you were right on that one, any idea what mods might be causing the issue?

**Comment by blackd** [comment]
sodium
screenfx
tooltip fix

**Comment by goldstargloww** [comment]
none of those seem to be causing the issue still :/ any other thoughts ^^"? or should i try something like binary searching?
