### ISSUE TITLE
"Stop Auto refill" key doesn't work caused other than tool breaking.

### ISSUE THREAD

**Issue by ALFEECLARE** [blackd/Inventory-Profiles#382]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Forge

### Modloader Version

47.1.44

### Operating System

Windows

### List of all other installed mods

AutoElytra-2.0.0.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
EasierVillagerTradingRebuild-1.2.0.jar
EspAnvil-2.0.jar
horsestatsmod-MC1.20.x-1.4.7.jar
InventoryHotswap-1.4.jar
InventoryProfilesNext-forge-1.20-1.10.6.jar
justzoom_forge_1.0.2_MC_1.20.1.jar
konkrete_forge_1.6.1-2_MC_1.20.jar
kotlinforforge-4.4.0-all.jar
libIPN-forge-1.20-3.0.2.jar
torohealth-1.20-forge-2.jar
XrayMod-2.3.1.jar

### Describe the problem

When a slot becomes empty for reasons other than tool damage, the IPN will force automatic refilling even if you press the key to stop automatic refilling.

### Steps to reproduce

1.In survival gamemode, give player two stones. one setted in hotbar, another in inventory.
2.set IPN "Stop Auto Refill key" as CTRL.
3.with pressing CTRL key, throw a stone in hotbar.
It's expected the slot would be null empty, but actually, the slot is automatically refilled by stone from inventory.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
works as intended
it's in the title "Disable Autorefill for Tools While Holding" so it's intended only for tools.

**Comment by ALFEECLARE** [comment]
Oh, I overlooked it.
I'll close this.

Actualy, I would like a function to temporarily stop automatic replenishment for all items, not just tools. 
But I'll create new thread for it.
