### ISSUE TITLE
Shields don't replace when broken

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#386]
### Have you asked for help on discord?

YES

### Minecraft Version/s

1.20.4

### Modloader

Fabric

### Modloader Version

0.15.7

### Operating System

Windows

### List of all other installed mods

fabric-api-0.96.4+1.20.4
fabric-language-kotlin-1.10.18+kotlin.1.9.22
InventoryProfilesNext-fabric-1.20.3-1.10.9
iris-mc1.20.4-1.6.17
journeymap-1.20.4-5.9.20-fabric
libIPN-fabric-1.20.3-4.0.1
lighty-fabric-2.1.2+1.20.3
sodium-fabric-0.5.8+mc1.20.4
viafabricplus-3.0.6

### Describe the problem

[latest.log](https://github.com/blackd/Inventory-Profiles/files/14182782/latest.log)
When a damaged shield is destroyed, IPN won't replace it with a new one, unless "Differentiate By NBT" is disabled.

### Steps to reproduce

Disable "Replace Tools Before They Break".
Have an almost broken shield in your hand, and a new one in your inventory.
Summon a zombie and block it until the shield is destroyed.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
can't reproduce with 1.21
and versions below 1.21 are no longer supported
