### ISSUE TITLE
繁體中文

### ISSUE THREAD

**Issue by TeaCupTwe** [blackd/Inventory-Profiles#387]
### Have you asked for help in discord?

YES

### Describe your desired feature.

將來會新增繁體中文嗎?

**Comment by blackd** [comment]
there is support already

https://github.com/blackd/Inventory-Profiles/blob/all-in-one/shared-sources%2Fsrc%2Fmain%2Fresources%2Fassets%2Finventoryprofilesnext%2Flang%2Fzh_tw.json

how complete it is depends on people who donate time to translate it
