### ISSUE TITLE
Auto Refill Doesn't work when GUI is open

### ISSUE THREAD

**Issue by lostallmymoney** [blackd/Inventory-Profiles#388]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.4

### Modloader

Fabric

### Modloader Version

Fabric 0.15.7

### List of all other installed mods

A few... not sure it is relevant but it's stopping me from using baritone with Auto Refill. Thanks.

### Describe the problem

When any GUI is open, the auto refill function will not work. Cannot let baritone use auto-refill.

### Steps to reproduce

Place blocks with baritone, try to auto-refill..

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
as far as I know baritone has it's own auto refill... or at least something like that.
And in general combination with baritone is not supported because of the sheer amount of changes baritone does.

**Comment by lostallmymoney** [comment]
It does, #allowInventory .

**Comment by blackd** [comment]
Oh I just noticed that you have a GUI opened. This will disable auto refill baritone or not.
