### ISSUE TITLE
The problem with tetra ,not crash

### ISSUE THREAD

**Issue by fkyah3** [blackd/Inventory-Profiles#389]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Forge

### Modloader Version

47.2.20

### List of all other installed mods

[list.txt](https://github.com/blackd/Inventory-Profiles/files/14455701/list.txt)

### Describe the problem

problem not crash, is the tetra workbench is seen as a container, and i hope have some way to disable it

### Steps to reproduce

https://youtu.be/KQiewmbMkNQ
1open tetra workbench
2Pack your backpack
3item It's sorted into the tetra workbench

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
These kind of questions is why the template insist you first ask on discord.
This is not a support forum.

press r+g while the GUI in question is open.
If you need further help ask on discord.
