### ISSUE TITLE
Blacklisting items applies more than one blacklisting.

### ISSUE THREAD

**Issue by lostallmymoney** [blackd/Inventory-Profiles#390]
### Have you asked for help in discord?

NO

### Describe your desired feature.

Here's the issue: Let's say I have a cheap tool that I want to be automatically replaced when  finished (auto refill) But I do not want tool protection, I can only blacklist for both, not keep the auto refill while removing the tool protection. Thanks

**Comment by blackd** [comment]
works as intended.

use the other tool replacement options. like allow non enchanted tools to break
