### ISSUE TITLE
Bug along AutoTools mod : Messes with the mod

### ISSUE THREAD

**Issue by lostallmymoney** [blackd/Inventory-Profiles#391]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.4

### Modloader

Fabric

### Modloader Version

Latest fabric.

### List of all other installed mods

AutoTools

### Describe the problem

When using Keep selected slot: OFF in Autotools, it will try to auto-refill the tools when AutoTools switches back your items.
So it ends up not switching back.

### Steps to reproduce

Install IPM and AutoTools. Try Keep selected slot: OFF and Switch Back: ON. Along with auto-refill ON in IPM.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
tbh this is better handled if auto tools uses the IPN API when IPN is present.

here is an example how to do that  https://github.com/nyuppo/hotbarcycle/tree/master/src/main/java/com/github/nyuppo/compat

**Comment by lostallmymoney** [comment]
I added my tools to the blacklist instead. That should do it but they might break now !
________________________________
