### ISSUE TITLE
Sorting by creative (default) doesn't work.

### ISSUE THREAD

**Issue by Mr-Oca** [blackd/Inventory-Profiles#392]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.4

### Modloader

Fabric

### Modloader Version

0.15.7

### Operating System

Linux

### List of all other installed mods

none

### Describe the problem

Sorting by default (creative) doesn't work, it sort by name.

### Steps to reproduce

Install the mod. Try.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
this is a support question please ask on discord

**Comment by blackd** [comment]
can't reproduce 
and versions bellow 1.21 are no longer supported
