### ISSUE TITLE
Feature request: Add configurable key that stops item scrolling when held 

### ISSUE THREAD

**Issue by RashidFTW** [blackd/Inventory-Profiles#393]
### Have you asked for help in discord?

NO

### Describe your desired feature.

Use case: the [Easy Shulker Box](https://modrinth.com/mod/easy-shulker-boxes) mod allows you to scroll through the slots of a container item when it's in your inventory without opening it (to select what to extract from it). 

However when scrolling while a container (chest) is open, the scrolling triggers the Item scrolling feature of this mod, which moves the item to the other container. I think adding a modifier key that when held, prevents the Item scrolling feature from triggering would fix this conflict and allow both features to be used in tandem depending on what the player needs to happen (move the item or scroll through it's contents).

Demo of container item scrolling feature: 

https://github.com/blackd/Inventory-Profiles/assets/160150516/728f9726-ea84-4f6e-b08b-82d5ac7d6941

Demo of issue (can only scroll in one direction, scrolling in the other moves the item):

https://github.com/blackd/Inventory-Profiles/assets/160150516/33f552c9-3e21-412e-b713-9383b4af6871

**Comment by RashidFTW** [comment]
Just tried out the temporary disable in the latest version, works perfectly and as expected. Didn't expect it to roll out so soon, Thanks a bunch! 😄

**Comment by blackd** [comment]
oh I forgot to mention this in the announcement
ah well ;)
