### ISSUE TITLE
Block placement in chest when item block is picked up

### ISSUE THREAD

**Issue by HepNinja** [blackd/Inventory-Profiles#397]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20

### Modloader

Fabric

### Modloader Version

1.10.9

### Operating System

macOS

### List of all other installed mods

Tweakeroo, litematica

### Describe the problem

When in a chest, I select a block from my inventory. The mod immediately puts a single block in the chests inventory. It does the opposite thing when clicking in the chest as well. Additionally, If I click after the probelm occurs, more blocks are added to the opposite inventory and are not in stacks but like 62 items. Ive tried uninstalling all other mods but this and error still occurs. Thanks

### Steps to reproduce

When in a chest, I select a block from my inventory. The mod immediately puts a single block in the chests inventory. It does the opposite thing when clicking in the chest as well. Additionally, If I click after the probelm occurs, more blocks are added to the opposite inventory and are not in stacks but like 62 items. Ive tried uninstalling all other mods but this and error still occurs. Thanks

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
I'm 100% sure this is not done by IPN. 
I'll close this please ask for support in our discord server.
