### ISSUE TITLE
Chest and Shulker Box look bad in Inventory

### ISSUE THREAD

**Issue by zhjc2021** [blackd/Inventory-Profiles#4]
list of installed mods: Fabric API 0.36.0  mod menu 2.0.2  inventoryprofilesnext-fabric-1.17-0.7.2
![QQ截图20210621214435](https://user-images.githubusercontent.com/86242797/122773328-dbf67e00-d2da-11eb-93c5-a03c9360130d.png)
![QQ截图20210621214512](https://user-images.githubusercontent.com/86242797/122773400-eb75c700-d2da-11eb-8ced-5364991c68f1.png)

**Comment by Tygoar** [comment]
#3 linking previous issue, pretty sure its been fixed awaiting build @blackd ?

**Comment by blackd** [comment]
I looks like it's fixed with #3 yes. 

I'm currently working no automatic deployments to curseforge and modrinth alongside the github release.
So if it works new release should be pushed everywhere next few commits
