### ISSUE TITLE
Add option to disable scroll wheel behavior

### ISSUE THREAD

**Issue by frenchiveruti** [blackd/Inventory-Profiles#400]
### Have you asked for help in discord?

YES

### Describe your desired feature.

Hello, the mod "Inventory tweaks" has a feature to not only move items onto containers **but also into furnaces/other**, this is very useful.
The problem?
Inventory Profiles also has a MW feature, only for containers, and it can't be disabled.  
Can a toggle option be included in future versions?

Thanks.

**Comment by blackd** [comment]
you can just remove the shortcuts in the key binds tab

**Comment by blackd** [comment]
Also no one have asked about this in discord for a long time. Why lie?
