### ISSUE TITLE
ipn warning tool replace failed.

### ISSUE THREAD

**Issue by vikemi** [blackd/Inventory-Profiles#403]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.4

### Modloader

Fabric

### Modloader Version

fabric api

### Operating System

macOS

### List of all other installed mods

i have xaeros map xaeros minimap  sodium mod menu

### Describe the problem

how to fix the ipn warning tool replace failed. i mean to really replace same tool after almost breaking.

### Steps to reproduce

i don't know what it means

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
this is exactly the type of question you should ask on discord.
