### ISSUE TITLE
Picking up items and putting them in backpacks 

### ISSUE THREAD

**Issue by zc1108aaa** [blackd/Inventory-Profiles#404]
### Have you asked for help in discord?

NO

### Describe your desired feature.

Picking up items and putting them in backpacks

Vanilla, put the shortcut bar. The backpack is empty, and the shortcut bar has become a trash bin

Suggest putting the picked items in the backpack instead of the shortcut bar

No, put it in a nearby box

**Comment by blackd** [comment]
ask on discord about this they will help you to find the option for it.
