### ISSUE TITLE
Permission to release an unoffical 1.20.6 version?

### ISSUE THREAD

**Issue by ImFalling** [blackd/Inventory-Profiles#405]
Hi!

Love you guys' work. My friends started a 1.20.6 server recently and I'm addicted to inventory sorting, so I took it upon myself to try to compile a jar file that works for 1.20.6. 

I don't know Kotlin or Fabric or Minecraft code really, but I managed to get it running (seemingly stable) with your libIPN for 1.20.5. 

Due to my inexperience I sort of massacred the neat code base you have here, so I don't think you'd appreciate a pull request in its current state. Let me know if you'd like me to try though.

**To the question**: I've already had someone notice my fork, asking me to send them the jar file if I was successful. Is it okay if I add it to the releases on my fork? I won't post it anywhere else, and all the credits and mod info are preserved, my name is nowhere in the mod files. 

I look forward to hearing from you, and will respect your decision on the matter.

Best wishes,
//Frick

**Comment by blackd** [comment]
I'm very interested in your code. Specially if you had profiles and villagers working too.

**Comment by blackd** [comment]
if you want to release it go ahead

**Comment by ImFalling** [comment]
Sorry for the delayed response, didn't expect you to get back so quick!

I didn't focus on the profiles, mostly just wanted the sorting to be honest. I did try creating a profile just now and got a NullPointerException, so the profiles are not working at this time. 
I also tried talking to a villager and got a game crash. 

I don't know the full extent of what this mod is capable of, so I don't really know what to test. 
Thank you for notifying me of these areas, I'll take another look before releasing it.

**Comment by blackd** [comment]
You know what
I can give you the current 1.21 state
that has sorting and villagers covered and you can backport it to 1.20.6

**Comment by ImFalling** [comment]
That would be very cool! Let me know how to go about getting the code and I'll do my best :)

**Comment by ImFalling** [comment]
Hi,

I believe I've solved the villager crash now, which I felt was a higher priority than profiles.
I'll release it in its current state, but I'll take a look at the profiles later. 
I'd love to see your new implementations, I've just read a bunch of type definitions and found workarounds, really.

Thanks for being so communicative and for your continued support of this wonderful mod :)

**Comment by blackd** [comment]
the 1.21 port is in the repo.
I think I won't be updating the lower version after 1.21 release. I had to fork the common part of the sources. But you never know may be it will be possible to merge them again.

If you need help or something I prefer discord for more real time communication.

**Comment by ImFalling** [comment]
Got it, I'll take a look. I'll hit you up on Discord if I have any questions. 

Take care :)
