### ISSUE TITLE
Villager autotrade Shopkeepers compatibility

### ISSUE THREAD

**Issue by ninjaguardian** [blackd/Inventory-Profiles#407]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.4

### Modloader

Fabric

### Modloader Version

0.15.10

### Operating System

Windows

### List of all other installed mods

AdvancementPlaques-1.20.4-fabric-1.6.1.jar
animatica-0.6+1.20.jar
appleskin-fabric-mc1.20.3-2.5.1.jar
better-clouds-1.5.8+1.20.4.jar
BetterF3-9.0.2-Fabric-1.20.4.jar
bettermounthud-1.2.2.jar
BetterPingDisplay-Fabric-1.20.4-1.1.1.jar
betterstats-3.9.7+fabric-1.20.4.jar
blur-3.2.0.jar
bounced-4.1.0-fabric1.20.3.jar
capes-1.5.3+1.20.2-fabric.jar
chat_heads-0.12.2-fabric-1.20.3.jar
citresewn-1.1.5+1.20.4.jar
cloth-config-13.0.121-fabric.jar
continuity-3.0.0-beta.5+1.20.2.jar
Controlify-2.0.0-beta.8+1.20.4.jar
Controlling-fabric-1.20.4-15.0.5.jar
cubes-without-borders-1.1.0+1.20.jar
Debugify-1.20.4+1.1.jar
dynamic-fps-3.4.3+minecraft-1.20.0-fabric.jar
e4mc-4.0.1+1.19.4-fabric.jar
eating-animation-1.20+1.9.61.jar
emi-1.1.6+1.20.4+fabric.jar
emitrades-fabric-1.3.0+mc1.20.4.jar
enhancedblockentities-0.9.1+1.20.2.jar
entityculling-fabric-1.6.4-mc1.20.4.jar
entity_model_features_fabric_1.20.4-2.0.2.jar
entity_texture_features_fabric_1.20.4-6.0.1.jar
explosive-enhancement-1.2.2-1.20.x.jar
fabric-api-0.97.0+1.20.4.jar
fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
fabricskyboxes-0.7.3+mc1.20.2.jar
fabrishot-1.12.1.jar
fallingleaves-1.15.6+1.20.1.jar
fastquit-3.0.0+1.20.4.jar
ferritecore-6.0.3-fabric.jar
filenames.txt
ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
fsb-interop-1.3.6+mc1.20.2-build.52.jar
Gamma-Utils-1.7.19-mc1.20.4.jar
Iceberg-1.20.4-fabric-1.1.18.jar
ImmediatelyFast-Fabric-1.2.14+1.20.4.jar
indium-1.0.30+mc1.20.4.jar
InventoryProfilesNext-fabric-1.20.3-1.10.10.jar
iris-1.7.0+mc1.20.4.jar
Jade-1.20.4-fabric-13.3.1.jar
jei-1.20.4-fabric-17.3.0.52.jar
lambdynamiclights-2.3.4+1.20.4.jar
language-reload-1.6.1+1.20.4.jar
LegendaryTooltips-1.20.2-fabric-1.4.5.jar
libIPN-fabric-1.20.3-4.0.2.jar
lithium-fabric-mc1.20.4-0.12.1.jar
main-menu-credits-1.1.2.jar
make_bubbles_pop-0.2.0-fabric-mc1.19.4+.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
mixintrace-1.1.1+1.17.jar
ModDetectionPreventer+1.20.4-1.2.0.jar
modelfix-1.14-fabric.jar
modernfix-fabric-5.17.0+mc1.20.4.jar
modmenu-9.2.0-beta.2.jar
morechathistory-1.3.0.jar
moreculling-1.20.4-0.24.0.jar
MouseTweaks-fabric-mc1.20-2.26.jar
nbttooltip-1.8.1-(1.20.4).jar
NoChatReports-FABRIC-1.20.4-v2.6.1.jar
notenoughanimations-fabric-1.7.3-mc1.20.4.jar
nvidium-0.2.6-beta.jar
optigui-2.3.0-beta.2.jar
paginatedadvancements-2.4.2.jar
plagues-chat-timestamps-1.0.2+1.20.jar
polytone-1.20.4-1.18.8-fabric.jar
Prism-1.20.4-fabric-1.0.6.jar
puzzle-1.6.1+1.20.4.jar
reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
replaymod-1.20.4-2.6.15.jar
rrls-4.0.3+mc1.20.4-fabric.jar
Searchables-fabric-1.20.4-1.0.6.jar
shulkerboxtooltip-fabric-4.0.8+1.20.4.jar
sodium-extra-0.5.4+mc1.20.4-build.116.jar
sodium-fabric-0.5.8+mc1.20.4.jar
spark-1.10.61-fabric.jar
tooltipfix-1.1.1-1.20.jar
wakes-0.2.4.jar
waveycapes-fabric-1.4.7-mc1.20.4.jar
worldedit-mod-7.3.0.jar
WorldEditCUI-1.20.3+01.jar
XaerosWorldMap_1.38.4_Fabric_1.20.4.jar
Xaeros_Minimap_24.1.1_Fabric_1.20.4.jar
yet-another-config-lib-fabric-3.3.2+1.20.4.jar
YetAnotherConfigLib-3.4.2+1.20.4-fabric.jar
yosbr-0.1.2.jar
Zoomify-2.13.4+1.20.4.jar

### Describe the problem

The server I am playing on uses Paper version git-Paper-496 (MC: 1.20.4) with Shopkeepers plugin v2.19.0 and the global bookmark and autotrade buttons don't work.

### Steps to reproduce

Setup paper server with a non-villager shopkeeper and try to click the buttons.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [x] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
doesn't work with shopkeepers or with  normal villagers?

**Comment by ninjaguardian** [comment]
It doesn't work with non-vilager [Shopkeepers](https://dev.bukkit.org/projects/shopkeepers)

Normal villagers -> work
Shopkeeper villagers -> work
Any other shopkeeper (pig, cow, zombie, etc.) -> doesn't work

**Comment by blackd** [comment]
ah, works as intended then

**Comment by ninjaguardian** [comment]
So, it shows up but doesn't work? And if it's not supposed to work with shopkeepers, why with the villager does it work?

**Comment by blackd** [comment]
I guess showing the overlay if it's not a villager might be considered a bug.
but there us no safe way of making it work for non villagers

**Comment by ninjaguardian** [comment]
Even if they use the villager UI system? I think it may be because it is trying to find the profession of the non-villager but ok.

**Comment by ninjaguardian** [comment]
I could try asking on shopkeeper's support site and see their approach to this issue.

**Comment by blackd** [comment]
they can't do anything about it.
IPN detects the click on villager to get the UUID of the entity and some other information.
Then when a packet to open the trading gui is received the data is merged with what comes with the gui.

expecting every entity to potentially open trading gui will lead to problems

**Comment by ninjaguardian** [comment]
Oh ok then. Well thanks for helping!
