### ISSUE TITLE
Is this part of inventory profiles next?

### ISSUE THREAD

**Issue by funnycubeguy** [blackd/Inventory-Profiles#408]
If this part of IPN? I was randomly banned for asking this question...

Can't seem to find the options or if it's part of IPN? or another mod? Its a extract button bottom right

Need help thanks

![Screenshot from 2024-06-05 09-32-08](https://github.com/blackd/Inventory-Profiles/assets/9994438/be82c53e-58cb-42a6-8971-647071a58893)

**Comment by blackd** [comment]
you were banned for pinging me
as I've said should have read the rules.

**Comment by funnycubeguy** [comment]
> you were banned for pinging me as I've said should have read the rules.

Can you answer the question at least? Thanks It me me replying to you

**Comment by funnycubeguy** [comment]
Oh well something bad must've happened to you if you're that upset over me replying to you. Hope you figure your life out...
