### ISSUE TITLE
Incompatibility with Dank Storage 

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#41]
Hello,
Can you try to fix the sorting method using [dank storage](https://www.curseforge.com/minecraft/mc-mods/dank-storage-fabric) mod?

Logs: https://pastebin.com/gpZHZKhE
Screenshot: https://i.imgur.com/FpCeeVK.png

Thanks,
Regards,
Szu.

**Comment by iliyababin** [comment]
I can second this issue.

The same error occurs when using [Fabric Carpet](https://github.com/gnembon/fabric-carpet) "stackableShulkerBoxes" rule, which allows empty shulker boxes to stack to 64.

Can provide logs if needed.

**Comment by blackd** [comment]
@Deluxepter this is different issue report it separately

**Comment by blackd** [comment]
@szumaster Unfortunately it's not really possible to support dank storage without tight integration between the mods.

The best I can suggest is to change 
```
Gui Settings
    Add inventory buttons to all in game screens
```
to *false*

and use the dank storage sort function

For the next release this will be false by default anyway.

**Comment by ghost** [comment]
I disable gui buttons, this applies to the keyboard shortcut, but thanks for the answer :)

**Comment by blackd** [comment]
disabling the buttons also disables the shortcuts

**Comment by blackd** [comment]
I'll keep this open if at some point I have time to think of a way to fix it

**Comment by blackd** [comment]
@szumaster If you apply the configuration I suggested. When you press R this mod will sort the player inventory  and will not attempt to sort Dank's storage.

**Comment by ghost** [comment]
You got right, i only disable inventory_buttons. Thanks!,  I am very grateful for your help :)

**Comment by ghost** [comment]
sorry to write here, but I have a question about your mod, can you give me permission to use it in my modpack?

**Comment by blackd** [comment]
of course you can.
it will be nice if you link back to the mod.

**Comment by ghost** [comment]
I give full information include your nick, mod website, github and ofc official thanks, thank you :)

**Comment by ghost** [comment]
Also found issue with ExpandedStorage mod, using any sorting method in iron chest - sort the items but on the other page, Can you look at this?

**Comment by blackd** [comment]
I'm unable to do anything about the paginated ExpandedStorage. 
I suggest that in video settings you set GUI Scale to 3 or lower so the full content of the chests

**Comment by ghost** [comment]
It's a problem with your mod or expanded?

**Comment by blackd** [comment]
with Expanded Storage the problem exists only in the 1.17.x version the 1.16 works fine so I would say it's in their mod

**Comment by blackd** [comment]
Pull requests have been posted to DankStorage for both 1.16 and 1.17 version
 https://github.com/Tfarcenim/DankStorageFabric/pull/36 https://github.com/Tfarcenim/DankStorageFabric/pull/35
 
 I consider this issue "fixed". In case they refuse to merge  see #54

**Comment by blackd** [comment]
@szumaster  Please post an issue in Expanded Storage from my test only chests with 2 pages are affected.

**Comment by ghost** [comment]
I plan on exposing an api for getting information about the current screen e.g. the first slot on screen, width of screen and height of screen. As for not sorting multiple pages you could prevent sorting slots which are off screen however I do have a bug to fix in regards to the player inventory slots being out of order.

**Comment by blackd** [comment]
Hi,
Yes it will be very useful to have such information especially for the column and row sorting to work properly but I'm not sure about sorting each page as a separate thing.

And may be other storage enhancement mod will be interested in implementing something like that. I wonder how feasible is to have all agree on single API.

**Comment by ghost** [comment]
Not sure if others would be willing to implement it, but I could make such an api for vanilla (dispenser, droppers, chests, hoppers) and my mod, I have had a similar request quite recently so if you would like we could continue discussing it there rather than a closed issue: https://github.com/NinjaPhenix/container-library/issues/7

Will likely expose enough to get an accurate representation of my screens so you can sort how ever you wish afterwards.
