### ISSUE TITLE
Lock slots per world/server reverting after relog

### ISSUE THREAD

**Issue by RandomGgames** [blackd/Inventory-Profiles#410]
### Have you asked for help on discord?

YES, CONFIRMED BUG

### Minecraft Version/s

1.21

### Modloader

Fabric

### Modloader Version

Fabric 0.15.11-1.21

### Operating System

Windows

### List of all other installed mods

fabric-api-0.100.1+1.21.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
InventoryProfilesNext-fabric-1.21-2.0.0.jar
libIPN-fabric-1.21-5.0.0.jar

### Describe the problem

Locked slots set in a world when "Unique per world/server" is True, upon relog disappear / revert to global locked slots if the file exists.
Going through a portal makes them re-appear until next relog.

### Steps to reproduce

Set unique per world to true
set some lock slots
relog
notice lock slots did not stay

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [x] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
fixed release will fallow shortly

**Comment by AngelOfCreation** [comment]
This does not appear to be fixed in the latest 1.20.1 release on Forge.
