### ISSUE TITLE
Buckets of axolotl can't be sorted and produces error message

### ISSUE THREAD

**Issue by Lumelore** [blackd/Inventory-Profiles#412]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21

### Modloader

Fabric, Quilt

### Modloader Version

Fabric Loader Version: 0.15.11
Quilt Loader Version 0.26.0

### Operating System

Linux

### List of all other installed mods

appleskin-fabric-mc1.21-3.0.2.jar
architectury-13.0.1-fabric.jar
athena-fabric-1.21-4.0.0.jar
BetterF3-11.0.1-Fabric-1.21.jar
chat_heads-0.12.3-fabric-1.21.jar
cloth-config-15.0.127-fabric.jar
Clumps-fabric-1.21-18.0.0.1.jar
CustomPlayerModels-Fabric-1.21-0.6.17c.jar
dynamic-fps-3.4.3+minecraft-1.21.0-fabric.jar
enhancedblockentities-0.10.1+1.21.jar
entityculling-fabric-1.6.6-mc1.21.jar
fabric-api-0.100.1+1.21.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
fallingleaves-1.16.0+1.21.jar
ferritecore-7.0.0-fabric.jar
gahtmod-1.1.2-mc1.21.jar
ImmediatelyFast-Fabric-1.2.18+1.21.jar
indium-1.0.33+mc1.21.jar
InventoryProfilesNext-fabric-1.21-2.0.0.jar
iris-1.7.1+mc1.21.jar
jamlib-fabric-1.0.9+1.21.jar
libIPN-fabric-1.21-5.0.0.jar
modmenu-11.0.0-beta.2.jar
rightclickharvest-fabric-4.2.0+1.21.jar
sodium-fabric-0.5.9+mc1.21.jar
sound-physics-remastered-fabric-1.21-1.4.3.jar

### Describe the problem

Trying to sort a chest with buckets of axolotl in it produces an error message in chat and the chest does not get sorted. It is single player.

The error message in chat is the following and can be seen on line 243 of the log:

java.lang.ClassCastException: class net.minecraft.class_9279 cannot be cast to class net.minecraft.class_2520 (net.minecraft.class_9279 and net.minecraft.class_2520 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @38364841)

[latest.log](https://github.com/user-attachments/files/15879940/latest.log)

### Steps to reproduce

Try to sort a chest with buckets of axolotl in them. I used the R key but I don't know if that matters.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
this is a know problem

**Comment by blackd** [comment]
fixed release will fallow shortly
