### ISSUE TITLE
Axolotl Buckets cause error when sorting chest

### ISSUE THREAD

**Issue by pdebetta** [blackd/Inventory-Profiles#419]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21

### Modloader

Fabric

### Modloader Version

0.15.11-1.21

### Operating System

Windows

### List of all other installed mods

advanced-xray-fabric-21.0.0.jar, appleskin-fabric-mc1.21-3.0.2.jar, architectury-13.0.1-fabric.jar, authme-8.0.0+1.21.jar, autoswitch-9.0.1.jar, badpackets-fabric-0.8.1.jar, balm-fabric-1.21-21.0.7.jar, beehivetooltip-1.21-1.3.0.jar, betterstats-3.11.1+fabric-1.21.jar, cloth-config-15.0.127-fabric.jar, collective-1.21.0-7.61.jar, componentviewer-fabric-1.1.2+1.21.jar, continuity-3.0.0-beta.5+1.21.jar, entityculling-fabric-1.6.6-mc1.21.jar, EssentialGUI-1.10.0+1.21.jar, essential_1-3-2-7_fabric_1-21.jar, fabric-api-0.100.3+1.21.jar, fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar, ferritecore-7.0.0-fabric.jar, ForceLowerCaseCommandsFabric-1.1.0.jar, freecam-fabric-1.3.0-beta1+mc1.21.jar, fullbrightnesstoggle-1.21.0-4.0.jar, Gamma-Utils-1.9.20-mc1.21.jar, glowing-entities-version-3.0-1.21.jar, indium-1.0.33+mc1.21.jar, inventoryhud.fabric.1.21-3.4.22.jar, InventoryProfilesNext-fabric-1.21-2.0.0.jar, iris-1.7.1+mc1.21.jar, Ksyxis-1.3.2.jar, libIPN-fabric-1.21-5.0.0.jar, lighty-fabric-3.0.0-beta.3+1.21.jar, litematica-fabric-1.21-0.18.999-sakura.4.jar, lithium-fabric-mc1.21-0.12.5.jar, malilib-fabric-1.21-0.19.999-sakura.2.jar, modmenu-11.0.0.jar, morechathistory-1.3.1.jar, NoFog-1.3.6+1.16.5-1.21.jar, reeses_sodium_options-1.7.2+mc1.21.jar, RoughlyEnoughItems-16.0.729-fabric.jar, shulkerboxtooltip-fabric-5.0.2+1.21.jar, sodium-extra-0.5.7+mc1.21.jar, sodium-fabric-0.5.9+mc1.21.jar, tcdcommons-3.11+fabric-1.21.jar, voicechat-fabric-1.21-2.5.17.jar, WI-Zoom-1.5-MC1.21.jar, worldedit-mod-7.3.4-beta-01.jar, wthit-fabric-12.2.0.jar, XaerosWorldMap_1.38.8_Fabric_1.21.jar, Xaeros_Minimap_24.2.1_Fabric_1.21.jar, YetAnotherConfigLib-3.5.0+1.21-fabric.jar

### Describe the problem

When sorting a chest with axolotl buckets, no sorting happens and the following error occurs:

java.lang.ClassCastException: class net.minecraft.class_9279 cannot be cast to class net.minecraft.class_2520 (net.minecraft.class_9279 and net.minecraft.class_2520 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @69b794e2)

### Steps to reproduce

Place axolotl bucket in chest. Click sort inventory button. Fails regardless of sort order selected.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
use the latest version
