### ISSUE TITLE
Item replacement fails and does not disappear.

### ISSUE THREAD

**Issue by pil0lo** [blackd/Inventory-Profiles#421]
### Have you asked for help in discord?

NO

**Comment by pil0lo** [comment]
Item replacement fails and does not disappear.

![1](https://github.com/user-attachments/assets/60dc8964-319d-4e94-b8bf-7fef8a74516f)

**Comment by blackd** [comment]
how long it will stay is controlled by minecraft it self.

IPN just tells minecraft code show this to the user.

as the template for this issue said for support requests ask on discord.
