### ISSUE TITLE
I type /lay to sleep on server

### ISSUE THREAD

**Issue by matesoss** [blackd/Inventory-Profiles#422]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21

### Modloader

Fabric

### Modloader Version

1.21

### Operating System

Windows

### List of all other installed mods

journeymap, REI, barrel roll

### Describe the problem

I play on survival server and when i type to chat /lay (sleep) my helmet on me (netherite) start switching with turtle helmet (in my inventory) idk how to fix it.

### Steps to reproduce

i dont know :|

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
and what was the result when you tested without IPN?

and with IPN only?

**Comment by matesoss** [comment]
> and what was the result when you tested without IPN?
> 
> and with IPN only?

When I run without, it gave me crashlog that said, that i need IPNlib

**Comment by blackd** [comment]
just remove both Inventory profiles next and libIPN

and see if it still happens

**Comment by matesoss** [comment]
Okay

**Comment by matesoss** [comment]
Nope, my helmet doesnt switch anymore :|

**Comment by blackd** [comment]
so go to discord so we can continue our conversation.

**Comment by matesoss** [comment]
Okay
