### ISSUE TITLE
1.19.2 version 1.10.10 GUI interference 

### ISSUE THREAD

**Issue by Demonspawnzzz** [blackd/Inventory-Profiles#423]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.19.2 

### Modloader

Forge

### Modloader Version

Forge 43.4.0

### Operating System

Windows

### List of all other installed mods

Ice and fire, Citadel, and Paragliders

### Describe the problem

Hello, I'm playing on 1.19.2 version 1.10.10. There's some GUI bug I'm experiencing, Its interfering with Ice and Fire's dragon GUI (when you shift click to see the dragon details) along with paragliders goddess trade thing. If there's any chance of this getting fixed that would be helpful I love this mod so much ;w; 

### Steps to reproduce

I'm not too sure how this could be fixed seeing as its a GUI interference. Ill be reporting this to both mods it interferes with too so everyone is aware ^^

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
yeah as I've said in the CurseForge comments discord is the place for support questions 
https://discord.gg/23YCxmveUM
