### ISSUE TITLE
"Swipe Move Crafting Result Slot" tweak is not working

### ISSUE THREAD

**Issue by ttrafford7** [blackd/Inventory-Profiles#424]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21, IPN release 2.0.2

### Modloader

Fabric

### Modloader Version

100.7

### Operating System

Windows

### List of all other installed mods

![image](https://github.com/user-attachments/assets/364c9626-a893-4e99-b943-5571880cb520)

### Describe the problem

Can't swipe results from crafting result slot

### Steps to reproduce

Place an iron block into crafting bench or your inventory crafting slots and try to swipe down iron ingots from the result slot

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
I don't understand what you mean by "swipe down the result slot"

**Comment by ttrafford7** [comment]
scroll down with mouse wheel on a crafting result slot to move crafted stuff down to the inventory

**Comment by blackd** [comment]
This has never been implemented

**Comment by blackd** [comment]
This has never been implemented I think

**Comment by ttrafford7** [comment]
there’s literally such tweak in the config

**Comment by blackd** [comment]
where? if it doesn't say scrolling or mouse wheel then we have some sort of misunderstanding.

**Comment by ttrafford7** [comment]
what does that tweak do then?

**Comment by ttrafford7** [comment]
I’ve noticed that such feature exists in InvTweaks Emu. Can it be moved to the main IPN mod? Because there’s no point in using it only for this functionality as IPN covers all other needs

**Comment by blackd** [comment]
can you join our discord. I still think we are talking about different things
