### ISSUE TITLE
Item swap won't work.

### ISSUE THREAD

**Issue by yarber8** [blackd/Inventory-Profiles#425]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1 Fabric

### Modloader

Fabric

### Modloader Version

0.16.0, 0.15.11

### Operating System

Linux

### List of all other installed mods

appleskin-fabric-mc1.20.1-2.5.1
BetterF1-1.0
BetterThirdPerson-Fabric-1.20-1.9.0
cloth-config-11.1.118-fabric
fabric-api-0.92.2+1.20.1
fabric-language-kotlin-1.11.0+kotlin.2.0.0
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
freecam-fabric-modrinth-1.2.1+1.20
Gamma-Utils-1.7.16-mc1.20.1
IAS-Fabric-1.20.1-9.0.0
IBEEditor-1.20-2.2.8-fabric
indium-1.0.34+mc1.20.1
InventoryProfilesNext-fabric-1.20-1.10.10
iris-1.7.2+mc1.20.1
Jade-1.20-fabric-11.10.0
JadeAddons-1.20.1-fabric-5.2.5
libIPN-fabric-1.20-4.0.2
lithium-fabric-mc1.20.1-0.11.2
ModernUI-Fabric-1.20.1-3.10.1.4-universal
modmenu-7.2.2
notenoughanimations-fabric-1.7.4-mc1.20.1
reeses_sodium_options-1.7.2+mc1.20.1-build.101
sodium-extra-0.5.4+mc1.20.1-build.115
sodium-fabric-0.5.11+mc1.20.1
WorldEditCUI-1.20+01
worldedit-mod-7.2.15
YetAnotherConfigLib-3.5.0+1.20.1-fabric
Zoomify-2.14.0+1.20.1

### Describe the problem

Item swap won't work.

### Steps to reproduce

It works without other mods, can you please fix it?

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [x] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
please ask on discord.
