### ISSUE TITLE
Villager trade ignores costs

### ISSUE THREAD

**Issue by McMattmue** [blackd/Inventory-Profiles#429]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21

### Modloader

Fabric

### Modloader Version

0.15.11

### Operating System

Windows

### List of all other installed mods

1.21-MacroKeybinds-fabric-1.3.1.jar
architectury-13.0.6-fabric.jar
BetterPingDisplay-Fabric-1.21-1.1.1.jar
Boxlib-fabric-14.2.2.jar
brb-1.10.0-rc5+1.21.jar
chatsigninghider-fabric-1.21.1-1.0.5.jar
cloth-config-15.0.128-fabric.jar
CoordinatesDisplay-fabric-13.0.0.jar
entityculling-fabric-1.6.6-mc1.21.jar
fabric-api-0.102.0+1.21.jar
fabric-language-kotlin-1.12.0+kotlin.2.0.10.jar
FpsReducer2-fabric-1.21-2.9.jar
inventoryhud.fabric.1.21-3.4.24.jar
InventoryProfilesNext-fabric-1.21-2.0.4.jar
iris-1.7.3+mc1.21.jar
Jade-1.21-Fabric-15.1.5.jar
jei-1.21-fabric-19.8.2.99.jar
libIPN-fabric-1.21-6.0.2.jar
light-overlay-12.0.0.jar
litematica-fabric-1.21-0.18.999-sakura.26.jar
malilib-fabric-1.21-0.20.0.jar
maptooltip-fabric-1.21-rc1-4.0.0.jar
modmenu-11.0.1.jar
morechathistory-1.3.1.jar
placeholder-api-2.4.1+1.21.jar
rebind-all-the-keys-1.5.2+1.21.jar
resourcepackchecker-fabric-1.21.1-1.2.2.jar
seedcrackerX-2.15.0.jar
serverpack-priority-1.0.2-1.21.jar
shulkerboxtooltip-fabric-5.0.4+1.21.jar
sodium-extra-0.5.7+mc1.21.jar
sodium-fabric-0.5.11+mc1.21.jar
text-utilities-fabric-1.7.0+1.21.jar
visiblebarriers-1.21-2.0.15.jar

### Describe the problem

Everything works as it did for me in 1.20, but after reading the new feature:
> Villager bookmarks now support cost items with changed components. This is useful with some shop plugins.
I expected it to be in a way, that only the exacly same offer would be marked.

### Steps to reproduce

Have for example:
Villager A: Book + 7 Emeralds -> Unbreaking III
Villager B: Book + 8 Emeralds -> Unbreaking III

Mark the trade of villager A as global.
Check villager B.
Even thought the cost are not the same, both are now marked, which can be really costly.
Can of course also happen with local trade, since the librarians can offer the same books up to 3 times.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
Well this is by design. I didn't expect people to buy books in bulk.
It's more for trading carrots, potatoes and pumpkins, where the some difference in the prices is expected.

**Comment by blackd** [comment]
works as intended
