### ISSUE TITLE
Changing the setting to enable/disable picking up items in locked slots does nothing

### ISSUE THREAD

**Issue by Krebs-Cycle** [blackd/Inventory-Profiles#43]
Version 0.8.0 to 0.9.0
Fabric API: 0.37.2
1.16.5

Changing the "Enable picking items into empty locked slots" setting to either true or false does not change any pickup behavior when testing in singleplayer. The item always gets picked up in the unlocked slots rather than the locked slots even when the setting is set to true.

**Comment by blackd** [comment]
fabric or forge?

**Comment by Krebs-Cycle** [comment]
Fabric
