### ISSUE TITLE
R+Y Hotkey activates in other mods' text boxes

### ISSUE THREAD

**Issue by Tisawesomeness** [blackd/Inventory-Profiles#430]
### Have you asked for help on discord?

YES

### Minecraft Version/s

1.21

### Modloader

Fabric

### Modloader Version

0.15.11

### Operating System

Windows

### List of all other installed mods

Fabric API
Fabric Language Kotlin
Inventory Profiles Next
libIPN
ModMenu

### Describe the problem

The `r+y` hotkey works even in text boxes, such as when typing "inventory" in the Mod Menu search bar. This does not happen with IPN's own text boxes.

!["Reloading configuration..." printed in chat after "inventory" is typed in the mod menu search bar](https://github.com/user-attachments/assets/f59ba0b2-6a2b-43f7-b0c7-383fd6a08879)

### Steps to reproduce

1. Join a singleplayer world
2. Open Mod Menu
3. Select the mod search text box
4. Press `r+y`
5. Notice that the configuration is reloaded as shown by chat

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
works as intended
