### ISSUE TITLE
when auto refill is disabled auto refill icons are still displayed

### ISSUE THREAD

**Issue by Tisawesomeness** [blackd/Inventory-Profiles#431]
### Have you asked for help in discord?

YES

### Describe your desired feature.

If auto refill is disabled, no slots will be refilled, so the purple refill indicators should be hidden to prevent confusion.

![image](https://github.com/user-attachments/assets/efdaedfb-b8ac-4e7b-a848-e62e68b8a804)
![image](https://github.com/user-attachments/assets/a5a2926a-4cc9-4166-b2e3-907a1a3d8d78)

**Comment by om3ga6400** [comment]
SAME

**Comment by ninjaguardian** [comment]
I agree!
