### ISSUE TITLE
[Feature] do not activate R+Y hotkey when typing in text boxes

### ISSUE THREAD

**Issue by Tisawesomeness** [blackd/Inventory-Profiles#432]
### Have you asked for help in discord?

YES

### Describe your desired feature.

When players type "inventory" to search for the mod within Mod Menu, typing "ry" sometimes registers as pressing `r` and `y` at the same time, causing the config to reload and a message to be printed to chat. This can cause unwanted accidental reloads (I've received a few complaints about this as a modpack dev). Ideally, the keybind shouldn't activate when the player is typing in a text box.

**Comment by blackd** [comment]
detecting if something has input focus is impossible.
specially for modded screens

Currently there is an attempt to detect the recipe search. but even it isn't 100% reliable.
