### ISSUE TITLE
How to disable item durability and purple icon on Hot main inventory?

### ISSUE THREAD

**Issue by MeoNguOfficial** [blackd/Inventory-Profiles#433]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21.0

### Modloader

Fabric

### Modloader Version

v2.0.4

### List of all other installed mods

![image](https://github.com/user-attachments/assets/73233fc6-4eab-4158-b2d6-6970d6ac880d)

### Describe the problem

This is not a problem, but i don't know how to disable icon purple on hot main inventory?
![image](https://github.com/user-attachments/assets/7d61ec0e-fb56-4233-a4cd-5ec8b57f7627)

### Steps to reproduce

This's a question

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
for support queries use discord
