### ISSUE TITLE
Some purple arrows show in the last version of the mod on the hotbar

### ISSUE THREAD

**Issue by wilebaldo** [blackd/Inventory-Profiles#437]
### Have you asked for help on discord?

NO

### Minecraft Version/s

Minecraft version 1.21

### Modloader

Fabric

### Modloader Version

fabric API version 0.102.0 + 1.21
fabric Loader 0.16.2

### Operating System

macOS

### List of all other installed mods

A lot of mods, but I tested all of them and the problem is with inventory Profile Next

### Describe the problem

In the hotbar and in the slots of the armor is show a purple arrows in the left top corner of all the slots.

this is happening only in the latest version of the mod, I downgrade one version and everything is show ok.

This is some picture to show the problem.

This is the normal with the version 2.0.3
![2024-08-25_11 02 25_edited](https://github.com/user-attachments/assets/3e64573f-ce07-4da4-acdb-4e74818a414c)

and this is with the new version 2.0.4
![2024-08-25_10 41 00_edited](https://github.com/user-attachments/assets/8d2ea056-2b65-4c1e-ab1e-f56a6baa6676)

### Steps to reproduce

simple install the last version of the mod on minecraft 1.21 and is show the issue. Go back to the previews version and don't show the problem.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
works as intended
you can turn them off in the settings

**Comment by wilebaldo** [comment]
> works as intended you can turn them off in the settings

Ok, and what is the option to disable it? I don't know about it before.

**Comment by Foxgott16** [comment]
> > works as intended you can turn them off in the settings
> 
> Ok, and what is the option to disable it? I don't know about it before.

Yeah would be interesting to know.

**Comment by Foxgott16** [comment]
> > works as intended you can turn them off in the settings
> 
> Ok, and what is the option to disable it? I don't know about it before.

Had the same Problem. 
 Here is the fix: 
![image](https://github.com/user-attachments/assets/8fb883d2-16d4-4f2e-8858-0b8f538ad52a)


SEO Stuff so people can find the solution too:
purple arrows hotbar, purple arrow quickbar facing down arrow

**Comment by TheD0ct0r101** [comment]
The config could definitely use some sort of rework. There was no indication that the purple arrows were a part of the Auto-Refill, and having to go through 100 different settings to trial-and-error disable them is frustrating. If its possible, having the config tool-tips display an image of what they enable/disable in addition to text would help greatly. Either that or a little icon next to settings to signify which UI element they influence.
