### ISSUE TITLE
Not saving locked slots on servers

### ISSUE THREAD

**Issue by jonnneehh** [blackd/Inventory-Profiles#438]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21.x

### Modloader

Fabric

### Modloader Version

fabric-loader-0.15.11-1.21

### Operating System

Windows

### List of all other installed mods

betterf1-Fabric-1.0-1.21.x.jar
BetterF3-11.0.0-Fabric-1.21.jar
BetterThirdPerson-Fabric-1.21-1.9.0.jar
blur-4.1.0.jar
cave_dust-3.0.0.jar
cherishedworlds-fabric-10.0.2a+1.21.1.jar
chesstracker-2.4.13+1.21.1.jar
cicada-lib-0.8.3+1.21-and-above.jar
collective-1.21.1-7.8.jar
eating-animation-1.21+9.7.2.jar
EffectTimerPlus-Fabric-1.21-2.1.jar
enhancedblockentities-0.10.1+1.21.jar
entity_model_features_fabric-1.21-1.3.0.jar
entity_texture_features_fabric_1.21-6.1.3.jar
fabric-api-0.103.0+1.21.jar
fabric-language-kotlin-1.11.0+kt2.0.0+1.21.1.jar
fallingleaves-1.16.2+1.21.jar
guifollowers-1.21-1.3.8.jar
indium-1.0.35+mc1.21.jar
InventoryProfilesNext-fabric-1.21-2.0.0.jar
iris-1.7.1+mc1.21.jar
libIPN-fabric-1.21-5.0.0.jar
lighty-fabric-3.0.0-beta.4+1.21.jar
lithium-fabric-mc1.21-0.12.5.jar
maceub3d-1.21-1.0.0.jar
mailb-fabric-1.21.0-0.0.2.jar
modelfix-1.21-1.6-fabric.jar
modmenu-11.0.0-rc.4.jar
MouseTweaks-fabric-mc1.21-2.0.26.jar
notenoughanimations-fabric-1.7.4-mc1.21.jar
Sakura-Ryoko-Litematica-Mod-Fabric-1.21.jar
Sakura-Ryoko-MiniHUD-Mod-Fabric-1.21.jar
Sakura-Ryoko-Tweakeroo-Mod-Fabric-Quit-1.21.jar
show-me-your-skin-1.11.3+1.21.jar
shulkertooltip-fabric-5.4.0+1.21.jar
skinlayers3d-fabric-1.6.7-mc1.21.jar
sodium-fabric-mc1.21.0-0.5.11.jar
YetAnotherConfigLib-3.5.0+1.21-fabric.jar

### Describe the problem

When I lock the slots in my inventory in a server (all servers I have tried, personal servers) the locked slots do not get kept. So when I exit the server and go back in, I have to relock the slots because the mod doesn't remember which slots I locked before I exited the server.

In singleplayer, it works perfectly fine. 

### Steps to reproduce

- Join server and lock the desired slots
- Disconnect from the server
- Reconnect back from the server
- BUG: Locked slots disappear and you have to relock it again.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
update IPN to the latest version
