### ISSUE TITLE
Item Categories for Profiles

### ISSUE THREAD

**Issue by Azarattum** [blackd/Inventory-Profiles#44]
It would be really nice to have item categories while configuring profiles. So the configs would be more generic, flexible and compatible with future versions.

```
profile Example activate HOT1
    HOT1
     @melee_weapon
    HOT2
     @pickaxe
     @axe
     @shovel
    HOT3
     @solid_blocks
    HOT6
     @ranged_weapon
    HOT9
     @food
```

I understand that it could be implemented with the current version, but that would require a tedious work to specify every item. Especially something like blocks or food. Moreover you'll have to update such config for every upcoming Minecraft version that adds new blocks, food or weapons.

**Comment by blackd** [comment]
Unfortunately implementing this is not really possible. Especially if we include modded in the picture.

Also I would advice against having too many alternatives for a single slot, because in the worst case scenario we would have exponential growth in time needed to find the item.
