### ISSUE TITLE
IPN reloading configuration Disable

### ISSUE THREAD

**Issue by djbingbing** [blackd/Inventory-Profiles#441]
![image](https://github.com/user-attachments/assets/39f17291-00ad-4cf4-9119-93f177660045)

I tried searching for a way to disable this from appearing in chat but i couldnt find a way to disable it from chat, Was hoping someone could assist me in this issue, i dont really want to be constantly seeing this message

**Comment by blackd** [comment]
My guess is you have bind reload config to some key you normally use for something else.

**Comment by djbingbing** [comment]
> My guess is you have bind reload config to some key you normally use for something else.

I'm not seeing an option to bind reload config key

**Comment by blackd** [comment]
![image](https://github.com/user-attachments/assets/032b18ef-7ada-4570-bfe0-332d5fc37c95)

**Comment by blackd** [comment]
close due to inactivity
