### ISSUE TITLE
[1.21.1][Neoforge] After 2.0.5 update sorting key does not work

### ISSUE THREAD

**Issue by ffuentesm** [blackd/Inventory-Profiles#442]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21.1

### Modloader

NeoForge

### Modloader Version

21.1.66

### Operating System

Windows

### List of all other installed mods

[1.21.txt](https://github.com/user-attachments/files/17348811/1.21.txt)
is a long list, but this error is not about mod compatibility. 

### Describe the problem

When I try to sort my inventory nothing happens and this error appears
![image](https://github.com/user-attachments/assets/fbd761f5-c7c7-4f34-875f-c9520f5cafa5)
I bound my inventory sort to W. I even tried using the UI button to sort and did not work.

### Steps to reproduce

play the game in the old mod version
update to the new 2.0.5 version
try to sort your inventory

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
fixed in v2.0.6
