### ISSUE TITLE
IPnext and travelsbackpack UI incompatible

### ISSUE THREAD

**Issue by TakimotoEirlo** [blackd/Inventory-Profiles#446]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.21.1

### Modloader

Forge

### Modloader Version

neoforge21.1.72

### Operating System

Windows

### List of all other installed mods

- Inventory Profiles Next
- Traveler's Backpack

### Describe the problem

Hello Developer,

While playing the mods you made, I encountered the following UI errors:

Mods:
- Inventory Profiles Next
- Traveler's Backpack

Issue demonstration:
- img A:
- img B:

It seems that the UI positioning data for the backpack may not be standardized. After IP Next modifies the button positions in the backpack UI, switching to a different backpack tier causes the UI positions to change. Ideally, there should be no changes to the UI positioning. I hope this explanation makes sense. Of course, this is a compatibility issue between the two mods, and I have also informed the other developer.

### Steps to reproduce

![IMG_20241023_125754](https://github.com/user-attachments/assets/92d7e258-a490-4827-b3e9-2166e692a9a0)
![IMG_20241023_125808](https://github.com/user-attachments/assets/f53a2b18-a340-40c1-a224-4621df2f3d5d)

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
works as intended.
From java point of view it's the same gui. And there is no generic way to determine if it's the small or the big one.
My suggestion is to move the buttons on the top.

**Comment by TakimotoEirlo** [comment]
top OK
