### ISSUE TITLE
[Feature Request] Some settings can be turned off by default

### ISSUE THREAD

**Issue by SuanOrange** [blackd/Inventory-Profiles#448]
### Have you asked for help in discord?

NO

### Describe your desired feature.

Some settings can be turned off by default
This mod has a lot of features, but some features are not needed for many players, and it is troublesome to turn them off one by one, I think it is possible to keep only some basic functions on at the beginning, such as the R key to organize the inventory, and the rest of the functions are turned off by default, allowing players to turn on the various functions they want according to their needs

**Comment by blackd** [comment]
this have came up again and again and if you have flowed the requirement to ask on discord first you could have read why I don't want to do it
