### ISSUE TITLE
Locked slots won't get saved

### ISSUE THREAD

**Issue by Daschi1** [blackd/Inventory-Profiles#45]
Issue:
I locked slots on a server, but after rejoining they aren't there anymore.

Version:
v1.0.0 (fabric-1.17.1)

**Comment by blackd** [comment]
Hi, 
I can't reproduce this. If you can please post the server name here. If you'd rather not post the server on such a public place please DM me on discord.

**Comment by Daschi1** [comment]
The server is private, but it is running paperspigot 1.17.1. Perhaps it has something to do with it running in offline mode?

**Comment by marie-bnl** [comment]
Are you accessing the server by its IP or domain name?

**Comment by Daschi1** [comment]
I am connecting to the server with sub.domain:port. Maybe it has something to do with it being a proxy and redirecting the connection to another port internally?

**Comment by marie-bnl** [comment]
You could try to connect to the server, lock some slots, quit it and see if the file for your server exists in 
```
C:\Users\USER\AppData\Roaming\.minecraft\config\inventoryprofilesnext
```
And if it has content in it

**Comment by Daschi1** [comment]
No such file is getting created.

**Comment by blackd** [comment]
Logs will be very helpful without them I probably won't be able to do anything to help you
