### ISSUE TITLE
Incompatible with Exposure

### ISSUE THREAD

**Issue by Fyoncle** [blackd/Inventory-Profiles#450]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

0.16.9

### Operating System

Windows

### List of all other installed mods

Elysium Days 6.0.0 Modpack

### Describe the problem

![image](https://github.com/user-attachments/assets/32d3965d-f2db-4b53-9ad0-df1e6fe6bd84)
Exposure's Album got sorting buttons bruh

### Steps to reproduce

1. Install IPN
2. Install Exposure
3. Open Album Item From Exposure Mod

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
press r+g while the gui is open set ignore to true.

**Comment by Fyoncle** [comment]
Thankkk you very much.

**Comment by Fyoncle** [comment]
Why reopen? Isn't it already perfect

**Comment by blackd** [comment]
still ill add it to the ~800 other GUIs that have special config that are build in the mod.

**Comment by Fyoncle** [comment]
> still ill add it to the ~800 other GUIs that have special config that are build in the mod.

Damnnnnnnnnnnnn, Meadow, Better Archeology and all the other mods gets also affected by IPN for some reason, idk why

**Comment by blackd** [comment]
because it's impossible to know/detect what the gui does, does it have slots at all, are they used for storage at all....
in most cases having the buttons on is the right decision so it's the default.
