### ISSUE TITLE
Throwing errors due to failure to control mixins via plugin

### ISSUE THREAD

**Issue by Linguardium** [blackd/Inventory-Profiles#454]
### Have you asked for help on discord?

NO

### Minecraft Version/s

N/A

### Modloader

Fabric, Forge, Quilt

### Modloader Version

N/A

### Operating System

Windows, macOS, Linux

### List of all other installed mods

N/A

### Describe the problem

[17:07:49] [main/WARN]: [MixinInfo#handleTargetError] @Mixin target dev.isxander.controlify.virtualmouse.VirtualMouseHandler was not found mixins.ipnext.json:MixinVirtualMouseHandler from mod inventoryprofilesnext

You are not preventing mixin application via a mixin config plugin so you fill logs with useless errors. please properly handle load state.

### Steps to reproduce

load game

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [X] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
It's just a warning during start up. I'm not adding code just to hide it.

**Comment by Linguardium** [comment]
Just to clarify your position, then.

You are aware that you are not properly handling loading of dependency mixins which causes errors in the log.
You have been notified that you are doing so and what the proper handling is.
At this point, you are intentionally causing errors with full knowledge of the cause and refusal to implement the provided solution.

Feel free to close this issue with refusal to fix, i guess. I still believe it's an issue, but if you are intent on your refusal to fix it, there's no reason to leave it open.

**Comment by blackd** [comment]
No,
My position is the since the parent class is not present there is no need to even try to load the mixin. So the logs are not my problem.

**Comment by Linguardium** [comment]
I see. Because you did something wrong and told a system to try to modify something that doesnt exist you are blaming that system for not ignoring you...and refusing to actually tell it what to load optionally.

I guess if it's just going to be a "everyone else's fault" thing, i'll close the issue myself. good luck with that attitude.
