### ISSUE TITLE
Incorrect Locked Slot UI Placement When Better Statistics Screen is present

### ISSUE THREAD

**Issue by Clownarchy** [blackd/Inventory-Profiles#456]
### Have you asked for help on discord?

YES

### Minecraft Version/s

1.21.3

### Modloader

Fabric

### Modloader Version

0.16.9

### Operating System

Windows

### List of all other installed mods

A lot of mods so I'm dropping screenshots for now, sorry!

![Screenshot 2024-12-14 235413](https://github.com/user-attachments/assets/d836515f-1a5d-4b48-aec4-ec08829fe0b3)
![Screenshot 2024-12-14 235429](https://github.com/user-attachments/assets/7629dc73-b36f-4a67-995f-14b5c5c52c38)
![Screenshot 2024-12-14 235444](https://github.com/user-attachments/assets/947d9564-a327-40c6-bea1-0c1a13375465)
![Screenshot 2024-12-14 235509](https://github.com/user-attachments/assets/5ae2709b-fc3e-4a9c-8d2e-7294296972c4)

### Describe the problem

When first joining a server, the first time you open your inventory the locked slot visuals will be in the wrong area. Re-opening the inventory fixes this.
![Screenshot 2024-12-14 163716](https://github.com/user-attachments/assets/530cbd3b-df49-4ec9-8c7e-0fba3c5a4946)

### Steps to reproduce

1. Create a game instance w/ Fabric (0.16.9) for 1.21.3
2. Install IPN 2.1.0 and libIPN 6.2.0 (and the other dependencies) 
3. Install "Better Statistics Screen" 3.13.4 and TCD Commons API 3.12.4
4. Launch game and create locked slots, leave the server
5. Re-join server, open inventory and observe position of locked slots (accidentally closing the inventory will fix this issue so be sure to not accidentally close the inventory)

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
Main reason for this behaviour is that when Better Statistics Screen mod is present first time the inventory is opened there is a miss match between the Screen and the ScreenHandler. For some reason the ScreenHandeler of the creative inventory is attached to the Screen of the PlayerInventory.

**Comment by blackd** [comment]
Looks like this will be handled in Better Statistics Screen
