### ISSUE TITLE
1.16.5 fabric crush

### ISSUE THREAD

**Issue by jkoi8529** [blackd/Inventory-Profiles#46]
In version 1.16.5 fabric, crush report said that 
"Errors were found!
Mod 'Inventory Profiles Next' (inventoryprofilesnext) requires any version of mod fabric-resource-loader-v0, which is missing!
You must install any version of fabric-resource-loader-v0."

It's still show this crush after I installed reportinstalled fabric-resource-loader-v0 and copied to mods.
How to solve it?

**Comment by blackd** [comment]
you need to install the whole Fabric API mod

**Comment by jkoi8529** [comment]
> you need to install the whole Fabric API mod

I had installed all Fabric mod. I also installed map mod, it will crash at this time.
If don't install inventoryprofilesnext, the game will run normally. Why?

**Comment by blackd** [comment]
you need to install this mod https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by jkoi8529** [comment]
Oh! Amazing! THX
