### ISSUE TITLE
[1.17] New Forge 1.10 version causes a crash Error 0 

### ISSUE THREAD

**Issue by ffuentesm** [blackd/Inventory-Profiles#53]
It doesn't say why but the New Forge 1.10 version does not let the game start. 

Also, you marked the fabric 1.10 version as a forge version.

**Comment by blackd** [comment]
HI, 
Can you upload the logs both debug.log and latest.log right after you try to start the game

**Comment by blackd** [comment]
OK This was a strange one the build system produced working jar 1 out of 10 builds... I've released new build that works.
