### ISSUE TITLE
Disable Sorting buttons when on horseback

### ISSUE THREAD

**Issue by keatit71** [blackd/Inventory-Profiles#58]
I use a mod that shows horse stats and it conflicts with inventory next sorting buttons if i could disable the buttons in the horse inventory that would stop the stats button conflicting.

**Comment by blackd** [comment]
you should report this to the other mod and they can use out API to change how we handle their screen.
Point them the the readme.md of this mod

**Comment by blackd** [comment]
I'm closing this since it will be handled FVT-fabric in https://github.com/Flourick/FVT-fabric/issues/50
