### ISSUE TITLE
Icons Don't Show Up and Chat is spammed with "Rule @default not found"

### ISSUE THREAD

**Issue by nibblecat1** [blackd/Inventory-Profiles#6]
Here are the Mods I was using:
![image](https://user-images.githubusercontent.com/86313743/122960385-f9623100-d348-11eb-9e67-4b18163fbbe8.png)

And a Screenie of the Issues:
![image](https://user-images.githubusercontent.com/86313743/122960492-126ae200-d349-11eb-9843-9979f0a7be6d.png)
![image](https://user-images.githubusercontent.com/86313743/122960581-27e00c00-d349-11eb-9e95-17da59cd49cf.png)

Here's the latest.log : 

[latest.log](https://github.com/blackd/Inventory-Profiles/files/6695865/latest.log)

EDIT: My "Inventoryprofilesnext' folder is empty. I double checked it with the normal 1.16.2 inventory profiles (which does not have this issue), and that is also empty. 
Also, unrelated, it doesn't sort enchanted books or nonstackables. I don't know if this is a feature or an issue related with this bug.

**Comment by blackd** [comment]
Hi,
I can't reproduce either of you problems. 



the mod was unable to load the embedded configuration file:

> [11:11:02] [Render thread/INFO]: [STDERR]: java.io.FileNotFoundException: inventoryprofilesnext:config/rules.txt
> [11:11:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_3304.method_14486(class_3304.java:65)


and a texture

> [11:11:36] [Render thread/WARN]: Failed to load texture: inventoryprofilesnext:textures/gui/gui_buttons.png
> java.io.FileNotFoundException: inventoryprofilesnext:textures/gui/gui_buttons.png


But more interesting is that minecraft it self can't load it's own file

> [11:11:03] [Worker-Main-5/ERROR]: Couldn't load truetype font minecraft:negative_spaces.ttf
> java.io.FileNotFoundException: minecraft:font/negative_spaces.ttf


So I guess there is something more going on. As a last resort I can suggest is reinstalling the game and deleting %USERPROFILE%\.minecraft folder **NOTE This will delete all of your saved world so don't do it if you care about them**

p.s. 
How sorting works depends on the embedded configuration file so I guess if it's not loaded sorting won't work properly

**Comment by nibblecat1** [comment]
Odd. I wonder why that's happening. So there's nothing else to be done besides reinstalling the game? I don't mind doing so, I'll just archive my worlds elsewhere on my laptop. Thanks for the help.

**Comment by blackd** [comment]
Please update here if it works

**Comment by nibblecat1** [comment]
Did not work. Deleted all the minecraft files and Reinstalled. Problem still occurs. Here's the log again
[latest.log](https://github.com/blackd/Inventory-Profiles/files/6704942/latest.log)

**Comment by blackd** [comment]
Hi

I was able to reproduce your problem, As a temporary solution please add this mod https://modrinth.com/mod/modmenu too.
You probably want it any ways since it adds a button to access all mods configurations in the main/pause menu

**Comment by nibblecat1** [comment]
Thank you! Will try!
