### ISSUE TITLE
Client-Server problem

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#60]
**Description:**

When the mod is present on the client and the client pings a forge server (that does not have the mod) it returns a red incompatibility "X" this is confusing to some users. When this incompatibility notice shows in the multiplayer menu there is also a warning in the clients latest.log that says:

_[29Oct2021 07:49:52.341] [Netty Client IO #5/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [inventoryprofilesnext]_

![redx](https://user-images.githubusercontent.com/82549089/139454227-e127dff1-5712-4278-aeeb-a347cea7e744.png)

So the solution to this problem is either for the mod author to make some changes to the code to disable the forge client-server check. Or the other solution is to install the mod on the server. The problem with that is that if the mod is installed serverside it causes the server to crash when loading up.

Server crash latest.log file: 
[latest.log](https://github.com/blackd/Inventory-Profiles/files/7442747/latest.log)

Thank you!

**Versions:**
Minecraft 1.16.5
Forge 1.16.5-36.2.6
InventoryProfilesNext-forge-1.16-1.1.1

**Comment by blackd** [comment]
every time I think I have fixed the server crash on forge it come back to haunt me.
I guess I'll try again.

**Comment by ghost** [comment]
> every time I think I have fixed the server crash on forge it come back to haunt me. I guess I'll try again.

@blackd Okay I that would be one solution. But maybe the better solution would be changing the Inventory-Profile mod so that it doesn't require that the server also have the mod installed, that is if the mod functions properly when only installed client-side. I think there is some sort of forge setting inside the mod code that makes that change, should be one line of code
