### ISSUE TITLE
With the "Sophisticated Backpack" mod, get error "infinite loop"

### ISSUE THREAD

**Issue by ncottrill** [blackd/Inventory-Profiles#61]
This works with most mods. But, when I try to sort within the "Sophisticated Backpack" for 1.17.1 backpack, I get an infinite loop error message and the backpack remains unsorted.

**Comment by blackd** [comment]
Hi,

I can't reproduce this. May be depends on the items you have in the back pack or on the upgrades you have installed.

**Comment by blackd** [comment]
This error usually happens whenever there are over-stacked items in the inventory.

**Comment by ncottrill** [comment]
> This error usually happens whenever there are over-stacked items in the inventory.

Yes, that is when the error occurs. However, the over-stack (Tier 1, Tier 2, Tier 3) is an important feature of the Sophisticated Backpack. I was able to use this mod, until I upgraded my backpack so that each stack was size 256

**Comment by blackd** [comment]
the problem with over-stacked items is that they break the vanilla click handling. And since this mod is client side only the sorting works by simulating clicks to move stacks around.

tbh I though I "fixed" it, by ignoring over-stacked slots, in #42, but I guess there are many types of over-stacking,

Anyway currently there is no way for this mod to sort such inventories,

**Comment by ncottrill** [comment]
Thank you for checking it out and seeing what could be done. I am pleased that this is a client side mod.

**Comment by blackd** [comment]
I still intend to fix the problem prevents IPN ignoring of over-stacked slots.

As a workaround there is configuration that you can edit to essentially tell IPN to ignore the back pack screens. 
In config/inventoryprofilesnext/ModIntegrationHints.json add:
```json
  "net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen" : {
    "ignore": true
  },
  "net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer" : {
    "ignore": true
  }
```

This will essentially disable IPN for all sophisticated backpacks even without over-stacking

**Comment by Modeeves** [comment]
Thank you so much for the time ^_^
I always love this mod! What an honor to speak to the owner.
Have a nice day!!!
