### ISSUE TITLE
 "Rule @default not found"

### ISSUE THREAD

**Issue by SkullDiamond** [blackd/Inventory-Profiles#62]
Every time I click Sort Inventory this message appears in the chat. Could be the forge version?

mod version: InventoryProfilesNext-forge-1.16-1.1.2.jar
minecraft: 1.16.5
Forge: 36.2.8

![2021-11-03_03 53 27](https://user-images.githubusercontent.com/79324102/140004410-518addbe-cb54-4c05-90cc-6e252db7934f.png)

**Comment by blackd** [comment]
Hi,

Can you attach the content of config/inventoryprofilesnext/ folder 
and the mod jar file

**Comment by blackd** [comment]
Also the latest.log and debug,log from the logs folder
this and the folder from the message above can be found here:

>    Windows: %appdata%\\.minecraft, or C:\Users\You\AppData\Roaming\\.minecraft
>    Linux: ~/.minecraft
>    MacOS: ~/Library/Application Support/minecraft

**Comment by SkullDiamond** [comment]
The config/inventoryprofilesnext/ folder the txt is empty. 
lastest log:[latest.log](https://github.com/blackd/Inventory-Profiles/files/7467822/latest.log)
jar:[InventoryProfilesNext-forge-1.16-1.1.2.zip](https://github.com/blackd/Inventory-Profiles/files/7467838/InventoryProfilesNext-forge-1.16-1.1.2.zip)

I didnt find any debug.log in the logs folder :(

**Comment by blackd** [comment]
OK it looks like it's the same issue as #65 just Optifine is somehow preventing the crash.

**Comment by blackd** [comment]
fixed in b4c23b6

**Comment by blackd** [comment]
released v1.1.3 on curseforge
