### ISSUE TITLE
[1.16.5] crash the game when creating a world

### ISSUE THREAD

**Issue by Mrthomas20121** [blackd/Inventory-Profiles#65]
Crash report : https://paste.gg/p/anonymous/09f7141d4c0b4e93a790d5df8e8e44e6
Inventory Profiles Version : 1.1.2
Running Forge Mod loader.
i don't know why it is happening but it's crashing. if i roll back to a previous version it doesn't crash anymore.
I have no idea what is causing it.

**Comment by blackd** [comment]
Which launcher do you use?
you java looks very old.

**Comment by Modeeves** [comment]
Same here. Before I even enter my world, it already crashed.

Here's a crash log: https://pastebin.com/uH5YMhyF

I hope it can help me recover my world.

I am using the latest version.

**Comment by blackd** [comment]
Downgrading the mod or upgrading java should fix it. Your world should be unaffected.

**Comment by Mrthomas20121** [comment]
i'm using the vanilla launcher through curseforge.

**Comment by Mrthomas20121** [comment]
as for the java version, i'm using the java version curseforge provide
![image](https://user-images.githubusercontent.com/34064092/140080776-6099ef34-dfda-41da-8d21-ee5f48d3c259.png)

**Comment by blackd** [comment]
I'll release a fix soon.

**Comment by blackd** [comment]
released v1.1.3 on curseforge
