### ISSUE TITLE
Hotkeys incompatible with MiniHUD Mod

### ISSUE THREAD

**Issue by liborioc** [blackd/Inventory-Profiles#66]
When turning on MiniHUD, specifically enabling the overlay with the selected hotkey, the hotkeys for Inventory Profiles stop working. It becomes no longer possible to use any hotkeys for Inventory Profiles.

**Comment by blackd** [comment]
Hi,
It's a general incompatibility with mods that use MaLiLib. I've been trying to find the cause for some time.
Temporary workaround is to press the first key for the last MaLiLib key combination while you have your inventory open.
