### ISSUE TITLE
Inventory sorting buttons in crayfish gun mod

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#67]
The inventory sorting buttons appear in crayfish gun mod user interface but it is not needed, could it be blacklisted so it doesn't appear there anymore?

![image](https://user-images.githubusercontent.com/82549089/141604003-5874e00b-8b41-4262-8d5f-65601eee4e22.png)

**Comment by blackd** [comment]
Hi
It will be better if crayfish gun mod authors use this mod API to hid the buttons. Can you please report it to them too.

And link the issue in their project here https://github.com/blackd/Inventory-Profiles/issues/54 So I can track their decision.

**Comment by blackd** [comment]
#82
