### ISSUE TITLE
[Request] Make item in locked slot can't be moved or dropped

### ISSUE THREAD

**Issue by mhzen** [blackd/Inventory-Profiles#69]
Similar to [slotlock](https://www.curseforge.com/minecraft/mc-mods/slotlock)

**Comment by blackd** [comment]
Hi,
If moving is disabled how is the player suppose to move them when they want to. Unlock move the item out and lock it again?

**Comment by mhzen** [comment]
yeah kind off

**Comment by blackd** [comment]
this doesn't sound like good user experience
but I guess I can make it configurable

**Comment by mhzen** [comment]
Thank you!

**Comment by blackd** [comment]
45ee36f adds new configuration that disables most user interaction with locked slots. 
All automated stuff still behave the same.

Will be released in 1.1.8
