### ISSUE TITLE
Issue with Swipe-To-Move & Auto Crafting

### ISSUE THREAD

**Issue by kkellogg378** [blackd/Inventory-Profiles#71]
Just updated from 1.1.5 to 1.1.8 and instantly noticed a bug with swipe to move to container. After messing with it, I've come to the conclusion that items (excluding the first item clicked) that share a column with a locked slot refuse to move when shift-click swiping across a row of the inventory.

**Comment by blackd** [comment]
please report one problem per issue

**Comment by kkellogg378** [comment]
okay, I'll make a separate one for the other bug
