### ISSUE TITLE
Continuous Crafting doesn't work with honey bottles as expected

### ISSUE THREAD

**Issue by kkellogg378** [blackd/Inventory-Profiles#72]
Continuous crafting works fantastically unless you're crafting honey out of honey bottles. After shift clicking the output item once, it leaves a single empty bottle in each of the four input slots and doesn't refill it with honey bottles

**Comment by blackd** [comment]
This looks like more of a minecraft bug. Shift+Click on the result slot doesn't clean the matrix for some reason and always leaves 4 empty bottles.

I'll look if I can do something about it, but the implementation of auto crafting is fairly complex already. So either it will take some time or won't be possible at all.

**Comment by blackd** [comment]
fixed in e771347098edfa63433627fbc1816759c26dc936
