### ISSUE TITLE
Disable autorefill for certain tool tiers

### ISSUE THREAD

**Issue by ST-DDT** [blackd/Inventory-Profiles#74]
Sometimes I just want to use up some bad tools such as a stone sword for harvesting bamboo instead of good ones.
It would be nice if there was an option to disable auto refill for some tool tiers. E.g. wood and store tier (without enchantments).
Auto refill should replace them if they break, but it should not try to save them.

**Comment by Shinigami92** [comment]
Could this help you? https://inventory-profiles-next.github.io/#:~:text=Lock%20item%20slots%20in%20place%20so%20that%20sorting%20ignores%20them

**Comment by ST-DDT** [comment]
Locking a slot doesnt seem to effect auto refill, but I would rather use something tier specific than slot specific.

**Comment by blackd** [comment]
although this looks like a sound proposal it will be possible top provide tiered behaviour only for vanilla minecraft and leave modded with broken feature.

I won't implement tiered support but, I can see how this can be frustrating, so if you have other suggestions that might help in this situation...

**Comment by ST-DDT** [comment]
Instead of explicit tiers, how about a list of item ids? `minecraft:stone_shovel` (or however it is named).
The notion of tiers (or at least) tool classes seem to exist at least. Because the broken stone tool was replaced by an iron one.

**Comment by Shinigami92** [comment]
> [...] harvesting bamboo [...]

Wasn't there a blocklist feature? So adding `bamboo` to blocklist would prevent item swap at all?

**Edit:** seems this was another plugin :thinking: don't know which one

**Comment by blackd** [comment]
the highest durability wins when choosing with what to change the almost broken tool.

Introducing new configuration file is not something I want to do. may be something more in the direction of temporary disabling it until the active tool is changed.

But generally this is an issue mostly in early game, when people get higher end  gear they tend not to care that much.

I will have to check if the efforts needed for implementing something like this are in line with the eventual usage.

**Comment by Shinigami92** [comment]
You mean `Netherite Sword` with `Mending` and `Unbreaking III`, could take a while to get there and until then I already build a whole house with `Scaffoldings` :thinking:

**Comment by blackd** [comment]
@Shinigami92 and yet the time most people spend playing without at least diamond gear is tiny compared to the time they spend with at least enchanted diamond gear. 

The time I can spend on this mod is limited and I'd rather spend it on features that are useful for most people most of the time.

So the best I can suggest is:
Toggle in the config to disable switching for non enchanted stuff. Non discriminating as: even netherite stuff will not be swapped.
Hotkey for temporary disabling switching until you change the selected tool.

**Comment by blackd** [comment]
**So** *Toggle in the config to disable switching for non enchanted stuff. Non discriminating as: even netherite stuff will not be swapped.* **it is.**

it will be available in the next release

**Comment by blackd** [comment]
Final decision:

You can now allow non enchanted items to break. But it will only work for items which have max durability below some value. The value is also configurable.
