### ISSUE TITLE
Quark backpack button overlap.

### ISSUE THREAD

**Issue by KKotik** [blackd/Inventory-Profiles#75]
Quark backpack button overlap.
![image](https://user-images.githubusercontent.com/45950781/144497451-595665e2-1dc8-4380-a260-fba7bcab86ea.png)

**Comment by KKotik** [comment]
It is from Quark Oddities addon.

**Comment by blackd** [comment]
we have api that other mods to move the buttons.  please report this to them and point them here https://javadoc.io/doc/org.anti-ad.mc/inventory-profiles-next/fabric-1.17.1-1.1.0/org/anti_ad/mc/ipn/api/IPNGuiHint.html

**Comment by KKotik** [comment]
Quark will not be updated anymore for 1.16, this is Vazkii statement.

**Comment by blackd** [comment]
Still it will be best if they include it in the 1.18 version.

**Comment by blackd** [comment]
for 1.16 you can add the snippet below after the first { in config/inventoryprofilesnext/ModIntegrationHints.json 

```json
    "vazkii.quark.addons.oddities.client.screen.BackpackInventoryScreen": {
        "buttonHints": {
            "SORT" : {
                "horizontalOffset": 1,
                "bottom": 72
            },
            "SORT_COLUMNS" : {
                "horizontalOffset": 13,
                "bottom": 60
            },
            "SORT_ROWS" : {
                "horizontalOffset": 13,
                "bottom": 60
            },
            "CONTINUOUS_CRAFTING" : {
                "bottom": 60
            },
            "MOVE_TO_CONTAINER": {
                "horizontalOffset": 13,
                "bottom": 60
            }
        }
    },
```

**Comment by KKotik** [comment]
Thank you!

**Comment by KKotik** [comment]
I will open issue on quark side, when Vazkii port 1.18 and it will have stabilization iteself! Got you!

**Comment by blackd** [comment]
I've added this to the default config If they decide to provide their own values in the code they will be used instead of the config.
