### ISSUE TITLE
[SUGGESTION] Disable mod on certain servers

### ISSUE THREAD

**Issue by srnyx** [blackd/Inventory-Profiles#76]
Soooo... I got banned on Hypixel for "cheating" and I think it's because of this mod (I accidentally sorted my inventory which sends a lot of packets).
A way to disable the mod (or maybe even just certain aspects of it) on certain servers would be amazing, thank you!

**Comment by blackd** [comment]
Hypixel considers this mod a macro provider or something. Also the Profiles are definitely cheating if used in bed wars or other pvp minigames. So my advice will be don't use this mod on Hypixel or other servers that blacklist it.
With that said

You can probably get away with sorting and moving stuff if you set "Add Interval Between Clicks" to true and the interval it self to something like 50 or more.

Note: Profiles do not obey this limits intentionally so switching can be detected :imp:

**Comment by srnyx** [comment]
> Hypixel considers this mod a macro provider or something. Also the Profiles are definitely cheating if used in bed wars or other pvp minigames. So my advice will be don't use this mod on Hypixel or other servers that blacklist it. With that said
> 
> You can probably get away with sorting and moving stuff if you set "Add Interval Between Clicks" to true and the interval it self to something like 50 or more.
> 
> Note: Profiles do not obey this limits intentionally so switching can be detected 👿

So you won't add some sort of way to automatically disable the mod when on a certain server?

**Comment by blackd** [comment]
About the suggested feature. 

The best way to implement something like that is to add support for per server configurations. However this will require major design changes plus whole new system for management of such configurations.

I'll keep it in mind, but for the time being I don't have the time needed for such change.
