### ISSUE TITLE
Move All Items Icon Button missing

### ISSUE THREAD

**Issue by Modeeves** [blackd/Inventory-Profiles#77]
Forge Version: 1.16.5
Mod Version: 1.16-1.2.0

Issue: The "Move All Items Icon Button" is missing whenever I open my backpack which is in the most previous version, that button was always visible. Specifically, I am using the Sophisticated Backpack. I carefully checked the configs (and I also tried testing it out on its own in the default settings by creating a new world) but that button is nowhere to be found anymore making it hard to move items by clicking them one by one into my backpack.

However, it would appear that it's working properly with all kinds of chests.

Here's my config:
https://pastebin.com/LVF0Fu1i

**Comment by blackd** [comment]
Hi
My test show that the button is there under the "A" button from the backpack UI.
You can configure a hotkey for move in Hotkeys -> Move All Items

**Comment by blackd** [comment]
or you can insert this snipped after the first { in config/inventoryprofilesnext/ModIntegrationHints.json

```json
    "net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen": {
        "buttonHints": {
            "MOVE_TO_PLAYER": {
                "horizontalOffset": 30
            },
            "SORT" : {
                "horizontalOffset": 30
            },
            "SORT_COLUMNS" : {
                "horizontalOffset": 30
            },
            "SORT_ROWS" : {
                "horizontalOffset": 30
            },
            "MOVE_TO_CONTAINER": {
                "bottom": 2
            }

        }
    },
```

**Comment by Modeeves** [comment]
Thank you so much for the time! I truly appreciate it and always adored your mod. Have a nice day!!! ^_^
