### ISSUE TITLE
Don't delete history versions on CurseForge

### ISSUE THREAD

**Issue by yuesha-yc** [blackd/Inventory-Profiles#78]
Why hide/delete all history versions of the mod on CF? 
This prevents players to download a modpack that uses a history version of your mod. 
If you don't know this, it's fine, change it.
If you know this: You cannot use this kind of method to enforce a modpack developer to upgrade your mod.
I would strongly not recommend people using this mod if this is the case. 
Also please add a config to your log-in update notification so player can choose to turn it off. 

Thank you.

**Comment by blackd** [comment]
Archiving the versions only prevents manual downloads everything that uses the API to download the files is not affected.
If I have deleted a version that is because it contains game breaking bug.

**Comment by blackd** [comment]
> Also please add a config to your log-in update notification so player can choose to turn it off.

Mod Settings -> Enable Update Checks

**Comment by blackd** [comment]
> Archiving the versions only prevents manual downloads everything that uses the API to download the files is not affected. If I have deleted a version that is because it contains game breaking bug.

at leas curseforge documentation states that.

**Comment by blackd** [comment]
I have tested several mod packs going back to version 0.8.6 of this mod and they all downloaded without problems both with curseforge app and ATlauncher.
Do you have any specific launcher in mind?

Also I can restore the versions you need. Generally I remove them to avoid confusion for players that download them directly.

**Comment by yuesha-yc** [comment]
This is just an suggestion. It is not a good habit to hide broken versions in development. People are more confused this way. Because people tracks versions. At least true for me. It is better to just state it on mod page.

I updated your mod. Thank you for your work.

**Comment by blackd** [comment]
So far I have released over 120 files and currently every new version adds 7 more.
I've started archiving them after I noticed that the downloads were all over the place. Since then I started to keep only the latest 2 versions available (most of the time). Even then around 30% of the downloads were the old version. The confusion of the people that download directly from the site is a real thing.

**Comment by yuesha-yc** [comment]
![image](https://user-images.githubusercontent.com/52098789/149113835-b1343988-39c1-422d-8737-ab47115cc239.png)
This is really annoying

**Comment by blackd** [comment]
I'll restore the version later when I have access to device where I'm logged in.

please keep me informed which versions you need and I won't achieve them
