### ISSUE TITLE
Inventory Profiles have to be remade on realms each play session

### ISSUE THREAD

**Issue by cestevens** [blackd/Inventory-Profiles#79]
When playing on a realm the IP isn't a fixed address and will draw from some pool of servers instead. This means I have to remake my profile config every time I start playing on the same realm.
![image](https://user-images.githubusercontent.com/54615873/146109748-a913ba87-b34e-4b15-bbdb-ef60199fc646.png)
What could be an easy(er) fix is adding a check box to always use the same profile list regardless of server IP?

**Comment by blackd** [comment]
Yes this is a known issue. I'm trying to find something unique for the realm before making it so all realms share a config.

Will you be willing to give me access to your realm so I can test?
