### ISSUE TITLE
[FEATURE] Add in game configuration for unknown screens.

### ISSUE THREAD

**Issue by Dr-WeiAL** [blackd/Inventory-Profiles#82]
For example
Applied Energistics 2
![image](https://user-images.githubusercontent.com/47446553/147226845-34018653-5e0c-4b58-b65b-cc8789c38af4.png)
Storage Drawers
![image](https://user-images.githubusercontent.com/47446553/147226961-2a32f899-b0f0-4970-8843-1f27a7df6ea7.png)
Farming for Blockheads
![image](https://user-images.githubusercontent.com/47446553/147227139-d668bb4d-22ba-47d3-9ee2-90e9440a80e8.png)

There are too many, can you make a custom configuration to disable buttons on some interfaces?

**Comment by blackd** [comment]
there is a custom configuration it's located config/inventoryprofilesnext/ModIntegrationHints.json

it supports moving the buttons and disabling all IPN operations the default file should contain all enough information on what is supported.

if you enable the debug you can get the class names of the screens and the containers 
Mod Settings -> debug set to true
then close the config and open it again
there will be Debugs section there you need to enable trace_logs

after that every time you open a screen the class name will be in the logs 

I will be very grateful if you contribute your config.
the current build in config is here https://github.com/blackd/Inventory-Profiles/blob/all-in-one/common/src/main/resources/assets/inventoryprofilesnext/config/ModIntegrationHints.json

**Comment by Dr-WeiAL** [comment]
> there is a custom configuration it's located config/inventoryprofilesnext/ModIntegrationHints.json
> 
> it supports moving the buttons and disabling all IPN operations the default file should contain all enough information on what is supported.
> 
> if you enable the debug you can get the class names of the screens and the containers Mod Settings -> debug set to true then close the config and open it again there will be Debugs section there you need to enable trace_logs
> 
> after that every time you open a screen the class name will be in the logs
> 
> I will be very grateful if you contribute your config. the current build in config is here https://github.com/blackd/Inventory-Profiles/blob/all-in-one/common/src/main/resources/assets/inventoryprofilesnext/config/ModIntegrationHints.json

I tried it, and it did work, but there are too many GUIs that need to be changed. Is there a similar way to add a whitelist GUI?

**Comment by blackd** [comment]
There is no whitelist. 
I am thinking about adding in game gui to configure the mod for the currently active screen, but I haven't started yet. 
The best case scenario is the mods to use our API to mark their UIs. But I have little success, so far just we have couple mods using it like Better End/Nether

**Comment by Dr-WeiAL** [comment]
> There is no whitelist. I am thinking about adding in game gui to configure the mod for the currently active screen, but I haven't started yet. The best case scenario is the mods to use our API to mark their UIs. But I have little success, so far just we have couple mods using it like Better End/Nether

I think we can make a white list, because there are not many GUIs to sort out, most of which are storage class mod. Rather than canceling the display in the GUI one by one, let it have a choice of which GUIs can be sorted.

**Comment by blackd** [comment]
implementing a whitelist won't be a problem. 

But there is more to just enable or disable. Applied Energistics 2 for example has storage and non storage. but they all are represented by a single class. Some other offer oversized stacks which we can't really support without help from their developers. I'm exploring several different ways to handle these how ever it takes time.

Also there is a setting that will disable ipn for all non vanilla screens and containers. Gui Settings -> Enable for all screen.. or something like that

**Comment by blackd** [comment]
If you have list of mods that provide just storage I would appreciate it if you post it here too.

**Comment by Dr-WeiAL** [comment]
> If you have list of mods that provide just storage I would appreciate it if you post it here too.

I am using version 1.18.1. At this stage, there are relatively few mods. The ones I am using need to be sorted out:

sophisticatedbackpacks
expandedstorage
storagecabinet

It seems that only these need to be sorted 
The interface of other mods I added shouldn’t need to be sorted

**Comment by blackd** [comment]
expandedstorage should work fine if you use the full UI and have gui scaling set to 2

**Comment by blackd** [comment]
sophisticatedbackpacks is one of the complicated cases. if you don't use the overstaking it's fine otherwise the sorting will just ignore slots with more the normal number of items

**Comment by Dr-WeiAL** [comment]
> expandedstorage should work fine if you use the full UI and have gui scaling set to 2

These mods show that everything is normal when using the sorting function. The problem is that there are too many other mods that do not need the sorting function. 

Ok. . I think I should talk about this in discord, there is too much talk here

**Comment by blackd** [comment]
there is a beta version of the in game gui editor

https://github.com/blackd/Inventory-Profiles/suites/5167505514/artifacts/156575350

if you want to try it and give feedback.

**Comment by Dr-WeiAL** [comment]
> there is a beta version of the in game gui editor
> 
> https://github.com/blackd/Inventory-Profiles/suites/5167505514/artifacts/156575350
> 
> if you want to try it and give feedback.

This is really great! But there are still some problems.
First of all, it has an additional sorting button in the creative mode inventory, and it cannot be canceled.
![image](https://user-images.githubusercontent.com/47446553/152458691-caa99d3c-12ce-40c3-95bc-dcb33d056bc1.png)
Secondly it doesn't seem to be able to hide a single button? Only hide all or show all.
For example, some mods add something like a furnace. According to the vanilla furnace, there is only a button to move matching items, but it is either fully hidden or fully displayed.
![image](https://user-images.githubusercontent.com/47446553/152459199-802a773a-7505-438b-b2f9-d7ea8709609a.png)
![image](https://user-images.githubusercontent.com/47446553/152459216-e58d78d7-ffba-460c-8f6a-3c5453802d34.png)
Also, its button settings don't seem to be saved? When setting the next GUI, the settings of the previous GUI are invalid. 

hmmm.... Only these problems have been found at this stage, and I will add them when there are others.

**Comment by blackd** [comment]
about stuff not being saved
can you post the content of config/inventoryprofilesnext/integrationhits folder

**Comment by blackd** [comment]
* Vanilla screens are still under development.
* Currently there are no plans to make it possible to hide individual buttons

**Comment by Dr-WeiAL** [comment]
I thought you were offline at this time, I said on discord

**Comment by blackd** [comment]
well it's ready watch out for new release shortly
