### ISSUE TITLE
Tooltip Bug with Roughly Enough Itmes 

### ISSUE THREAD

**Issue by pewblaze** [blackd/Inventory-Profiles#85]
The Tooltip is behind REI -> its a little bit hard to read ^^"
I tested it without the mod & it fixes it.

![2021-12-31_16 46 46](https://user-images.githubusercontent.com/96242065/147831349-cff2fd3e-6638-4a47-b87d-f30caf644a77.png)

**Comment by blackd** [comment]
yeap it's an know issue.
There will be a fix tomorrow probably

**Comment by blackd** [comment]
fixed, for now, in 1.2.3
