### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by srnyx** [blackd/Inventory-Profiles#87]
https://srnyx.sucks-at.life/r/gvyh650txa.mp4

**Comment by blackd** [comment]
my guess is you have bind the sort on some key/button you are pressing or the sort button is stuck

**Comment by blackd** [comment]
although a video can replace 1000 words some explanation what exactly are you doing will help

**Comment by srnyx** [comment]
> my guess is you have bind the sort on some key/button you are pressing or the sort button is stuck

I mean why are some items becoming ghost items and not being sorted, only becoming visible once I click on the slot where they should be.
Or other times where things like the Rotten Flesh is duplicated but it's actually the saplings.

**Comment by blackd** [comment]
ah what server is this?

set Mod Settings -> Add Interval Between Clicks to true

and increase the interval below until it get resolved

**Comment by srnyx** [comment]
> ah what server is this?

My own

> set Mod Settings -> Add Interval Between Clicks to true
> 
> and increase the interval below until it get resolved

Anyway to fix it server-side?

**Comment by blackd** [comment]
usually this happens on servers with aggressive packet per interval of time limits or other packet count  optimisations/restrictions

vanilla, paper, fabric and forge servers usually behave properly but some of paper forks can cause problems 

or if the server has very limited CPU power

**Comment by blackd** [comment]
can you confirm that this is server problem and close the issue?

**Comment by srnyx** [comment]
> can you confirm that this is server problem and close the issue?

Ah yes sorry. Pretty sure this is related to https://github.com/dmulloy2/ProtocolLib/issues/1475
