### ISSUE TITLE
Scroll mouse wheel to add/remove items from/to inventory by one

### ISSUE THREAD

**Issue by ScrewTSW** [blackd/Inventory-Profiles#89]
Something I'm really missing is the ability to just hover over an item stack, and move them from my hotbar into my inventory or from inventory into a container by one with every mouse wheel scroll.

This is something that InventoryTweaks has done incredibly well in the past and would be a super welcome addition.

**Comment by blackd** [comment]
This pop up every now and then so I guess I'll implement something similar.

I just generally don't want to just implement features from other mods

**Comment by ScrewTSW** [comment]
@blackd that's understandable, but it's a genuinely insanely useful feature. In my opinion it's something that should have been in the base game a long time ago.

**Comment by ScrewTSW** [comment]
Nevermind, just found out that MouseTweaks has fabric release alongside forge one https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks

**Comment by blackd** [comment]
i know but unfortunately both mods don't play well together in some cases.

**Comment by blackd** [comment]
done in version 1.7.0 of the mod

**Comment by xuwuwudi** [comment]
I'm glad you still added this feature, but I still want to ask how to turn it off

**Comment by blackd** [comment]
just remove the shortcuts in the key binds page

**Comment by xuwuwudi** [comment]
> just remove the shortcuts in the key binds page

Oh I didn't notice. Thank you very much
