### ISSUE TITLE
[SUGGESTION] Add option to sort Alphabetically, Rarity, Item Count, Item Tags or Item Type.

### ISSUE THREAD

**Issue by aaronfilarca** [blackd/Inventory-Profiles#92]
Add option to sort Alphabetically, Rarity, Item Count, Item Tags or Item Type.

**Comment by blackd** [comment]
### Supported out of the box:
* Alphabetically - set "Mod Settings -> Sort Order" to Item Name
### Supported with custom rules see [docs](https://inventory-profiles-next.github.io/custom-rules/add/) and some more [docs](https://inventory-profiles-next.github.io/custom-rules/natives/)
* Tags
* Item Type
### Minecraft has no real concept for:
* Rarity

**Comment by aaronfilarca** [comment]
How about item count? By sorting the items by how much of it is present in the inventory.
It would be possible to add rarity by having items names and item tags in a dictionary with keys as tier and values as a list of items sorted by how easy the item is to obtain and how much playtime you need to get that item. Similar on how a crafting table as starting tier, an enchanting table as mid tier, and dragon egg/elytra as end game tier

**Comment by blackd** [comment]
### The problem with *Rarity* is that it's relative and depends on external factors

* other mods - adding new items will change how *Rarity* is evaluated in unpredictable ways 
* player experience
* player preferences 
* player view on what is hard for them to do 

So I guess the custom rules are the right way to support this too.

### Stacks and Slots

IPN works on stack level so to sort by item count with the current sort engine it would mean to ignore the items and just compare the stack sizes. This will lead to random arrangement of types.  I'm sure you don't want this.

I will check how feasible is to implement something like this as a Post action (see Gui Settings -> Post Action)
