### ISSUE TITLE
Continuous crafting with different durabilities.

### ISSUE THREAD

**Issue by koocgum** [blackd/Inventory-Profiles#97]
Continuous crafting should allow you to quickly merge items with different durabilities (except the ones in a locked slot) as for now; you need to do it manually.

**Comment by blackd** [comment]
duplicate with #95

**Comment by blackd** [comment]
Continuous crafting now works with different durabilities, However it doesn't make a difference if the item has no damage or it at 1 point. 
If used to merge items you will end with 1 item.

**Comment by blackd** [comment]
well I'll consider this done 
just don't use auto because you will end up with only 1 item
